select count(*) as cnt from ACL_SIGUMGO_SLV
where 1=1
and CRT_CAN_G in (2, 33)
and trxdt like '2024%'


select * from ACL_SIGUMGO_SLV
where 1=1
and CRT_CAN_G in (2, 33)
and trxdt like '2024%'


-- 원주시 공영개발 특별회계 자금운용내역이 조회되지 않는 이유

SELECT  BB.SIGUMGO_HOIKYE_C,
  BB.HOIKYE_NM NUGYE_HOIGYE_NAME,
  NVL(SUM(SEIB_SUIP2),0) NUGYE_SEIB_SUIP,
  NVL(SUM(SEIB_BANNAB2),0) NUGYE_SEIB_BANNAB,
  NVL(SUM(SEIB_GYEONGJEONG_IB2),0) NUGYE_SEIB_GYEONGJEONG_IB,
  NVL(SUM(SEIB_GYEONGJEONG_JI2)*-1,0) NUGYE_SEIB_GYEONGJEONG_JI,
  NVL(SUM(SECHUL_BAEJEONG2),0) NUGYE_SECHUL_BAEJEONG,
  NVL(SUM(SECHUL_HWANSU2)*-1,0) NUGYE_SECHUL_HWANSU,
  NVL(SUM(SECHUL_JI2),0) NUGYE_SECHUL_JI,
  NVL(SUM(SECHUL_BANNAB2)*-1,0) NUGYE_SECHUL_BANNAB,
  NVL(SUM(SECHUL_GYEONGJEONG_IB2),0) NUGYE_SECHUL_GYEONGJEONG_IB,
  NVL(SUM(SECHUL_GYEONGJEONG_JI2),0) NUGYE_SECHUL_GYEONGJEONG_JI,
  NVL(SUM(SEIB_GYULSANBF_IIB2),0) NUGYE_SEIB_GYULSANBF_IIB,
  NVL(SUM(SECHUL_GYULSANBF_IWOL2),0) NUGYE_SECHUL_GYULSANBF_IWOL,
  NVL(SUM(DEP2),0) NUGYE_DEP,
  NVL(SUM(HWANIB2),0) NUGYE_HWANIB,
  NVL(SUM(MIICHE2),0) NUGYE_MIICHE,
  NVL(SUM(SEIB_SUIP),0) ILGYE_SEIB_SUIP,
  NVL(SUM(SEIB_BANNAB),0) ILGYE_SEIB_BANNAB,
  NVL(SUM(SEIB_GYEONGJEONG_IB),0) ILGYE_SEIB_GYEONGJEONG_IB,
  NVL(SUM(SEIB_GYEONGJEONG_JI)*-1,0) ILGYE_SEIB_GYEONGJEONG_JI,
  NVL(SUM(SECHUL_BAEJEONG),0) ILGYE_SECHUL_BAEJEONG,
  NVL(SUM(SECHUL_HWANSU)*-1,0) ILGYE_SECHUL_HWANSU,
  NVL(SUM(SECHUL_JI),0) ILGYE_SECHUL_JI,
  NVL(SUM(SECHUL_BANNAB)*-1,0) ILGYE_SECHUL_BANNAB,
  NVL(SUM(SECHUL_GYEONGJEONG_IB),0) ILGYE_SECHUL_GYEONGJEONG_IB,
  NVL(SUM(SECHUL_GYEONGJEONG_JI),0) ILGYE_SECHUL_GYEONGJEONG_JI,
  NVL(SUM(SEIB_GYULSANBF_IIB),0) ILGYE_SEIB_GYULSANBF_IIB,
  NVL(SUM(SECHUL_GYULSANBF_IWOL),0) ILGYE_SECHUL_GYULSANBF_IWOL,
  NVL(SUM(DEP),0) ILGYE_DEP,
  NVL(SUM(HWANIB),0) ILGYE_HWANIB,
  NVL(SUM(MIICHE),0) ILGYE_MIICHE  
FROM
(
 SELECT   
     HOIGYE_CODE,
     SIGUMGO_ORG_C,
     NVL(SUNP_AMT,0) + NVL(TAX_BAEJUNG_IP_AMT,0) + NVL(IWOL_GONGGEUM,0)                                   
    - (NVL(SUNP_AMT,0) - NVL(TAX_SUNP_IP_AMT,0) + NVL(IWOL_MIJUNGSAN,0)) AS SEIB_SUIP,             
    NVL(GWAON_PROC_JI_AMT,0) AS SEIB_BANNAB,             
    NVL(TAX_IP_CRT_IP_AMT,0) AS SEIB_GYEONGJEONG_IB,             
    NVL(TAX_IP_CRT_JI_AMT,0) AS SEIB_GYEONGJEONG_JI,             
    NVL(BIZPLC_BAEJUNG_JI_AMT,0) AS SECHUL_BAEJEONG,             
    NVL(BIZPLC_GAM_BAEJUNG_IP_AMT,0) AS SECHUL_HWANSU,             
    NVL(TAXO_JI_AMT,0) AS SECHUL_JI,             
    NVL(TAXO_RTRN_AMT,0) AS SECHUL_BANNAB,             
    NVL(KWA_CRRC_IP_AMT,0) AS SECHUL_GYEONGJEONG_IB,             
    NVL(KWA_CRRC_JI_AMT,0) AS SECHUL_GYEONGJEONG_JI,             
    NVL(GA_IWOL_IP_AMT,0) AS SEIB_GYULSANBF_IIB,             
    NVL(GA_IWOL_JI_AMT,0) AS SECHUL_GYULSANBF_IWOL,             
    NVL(DEP_MK_JI_AMT,0) + NVL(IWOL_GONGGEUM_DEP,0) AS DEP,             
    NVL(DEP_HJI_AMT,0) AS HWANIB,             
    NVL(SUNP_AMT,0) - NVL(TAX_SUNP_IP_AMT,0) + NVL(IWOL_MIJUNGSAN,0) AS MIICHE,   
    0 AS SEIB_SUIP2,             
    0 AS SEIB_BANNAB2,             
    0 AS SEIB_GYEONGJEONG_IB2,             
    0 AS SEIB_GYEONGJEONG_JI2,             
    0 AS SECHUL_BAEJEONG2,             
    0 AS SECHUL_HWANSU2,             
    0 AS SECHUL_JI2,             
    0 AS SECHUL_BANNAB2,             
    0 AS SECHUL_GYEONGJEONG_IB2,             
    0 AS SECHUL_GYEONGJEONG_JI2,             
    0 AS SEIB_GYULSANBF_IIB2,             
    0 AS SECHUL_GYULSANBF_IWOL2,             
    0 AS DEP2,             
    0 AS HWANIB2,             
    0 AS MIICHE2   
 FROM
 (
  SELECT   
      C.SIGUMGO_HOIKYE_C AS HOIGYE_CODE    
     ,A.SIGUMGO_ORG_C
     ,SUM(TAX_SUNP_IP_AMT) AS TAX_SUNP_IP_AMT         
     ,SUM(TAX_BAEJUNG_IP_AMT) TAX_BAEJUNG_IP_AMT       
     ,SUM(GWAON_PROC_JI_AMT) AS GWAON_PROC_JI_AMT      
     ,SUM(TAX_IP_CRT_IP_AMT) AS TAX_IP_CRT_IP_AMT        
     ,SUM(TAX_IP_CRT_JI_AMT) AS TAX_IP_CRT_JI_AMT        
     ,SUM(BIZPLC_BAEJUNG_JI_AMT) AS BIZPLC_BAEJUNG_JI_AMT     
     ,SUM(BIZPLC_GAM_BAEJUNG_IP_AMT) AS BIZPLC_GAM_BAEJUNG_IP_AMT  
    ,SUM(TAXO_FUND_BAEJUNG_JI_AMT)
     +SUM(TAXO_HNDO_BAEJUNG_JI_AMT)
     +SUM(TAXO_FUND_GETBK_JI_AMT)
     +SUM(TAXO_HNDO_JICHUL_JI_AMT)
     +SUM(TAXO_HNDO_GETBK_JI_AMT)  AS TAXO_JI_AMT      
    ,SUM(TAXO_RTRN_AMT) AS TAXO_RTRN_AMT         
    ,SUM(KWA_CRRC_IP_AMT) AS KWA_CRRC_IP_AMT        
    ,SUM(KWA_CRRC_JI_AMT) AS KWA_CRRC_JI_AMT        
    ,SUM(GA_IWOL_IP_AMT) AS GA_IWOL_IP_AMT         
    ,SUM(GA_IWOL_JI_AMT) AS GA_IWOL_JI_AMT         
    ,SUM(DEP_MK_JI_AMT) AS DEP_MK_JI_AMT          
    ,SUM(DEP_HJI_AMT) AS DEP_HJI_AMT           
    ,0 AS SUNP_AMT                
    ,0 AS IWOL_GONGGEUM              
    ,0 AS IWOL_MIJUNGSAN              
    ,0 AS IWOL_MMDA               
    ,0 AS IWOL_GONGGEUM_DEP             
  FROM RPT_TXIO_DDAC_TAB A,  ACL_SIGUMGO_MAS  B, RPT_AC_BY_HOIKYE_MAPP C
  WHERE  A.SGG_ACNO = B.FIL_100_CTNT2
  AND A.ICH_SIGUMGO_HOIKYE_C = B.ICH_SIGUMGO_HOIKYE_C
  AND A.SIGUMGO_ORG_C = B.SIGUMGO_ORG_C  
  AND B.FIL_100_CTNT2 = C.SIGUMGO_ACNO(+)
  AND B.SIGUMGO_HOIKYE_YR = C.SIGUMGO_HOIKYE_YR(+)
  AND B.SIGUMGO_ORG_C = C.SIGUMGO_C(+)    
  AND A.ICH_SIGUMGO_GUN_GU_C = '0' 
 AND CASE WHEN A.SIGUMGO_HOIKYE_YR = 9999 THEN TO_NUMBER(SUBSTR(A.BAS_DT,1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR) END  = '2024'
  AND A.BAS_DT BETWEEN '20240522' AND '20240522' 
  AND A.SIGUMGO_ORG_C  = '130'
  AND B.MNG_NO = 1
  GROUP BY C.SIGUMGO_HOIKYE_C, A.SIGUMGO_ORG_C
  UNION ALL
  SELECT  TO_CHAR(ICH_SIGUMGO_HOIKYE_C) HOIGYE_CODE    
    ,A.SIGUMGO_ORG_C
    ,0 TAX_SUNP_IP_AMT         
    ,0 TAX_BAEJUNG_IP_AMT       
    ,0 AS GWAON_PROC_JI_AMT       
    ,0 AS TAX_IP_CRT_IP_AMT        
    ,0 AS TAX_IP_CRT_JI_AMT        
    ,0 AS BIZPLC_BAEJUNG_JI_AMT      
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT     
    ,0 TAXO_JI_AMT          
    ,0 AS TAXO_RTRN_AMT        
    ,0 AS KWA_CRRC_IP_AMT        
    ,0 AS KWA_CRRC_JI_AMT        
    ,0 AS GA_IWOL_IP_AMT        
    ,0 AS GA_IWOL_JI_AMT        
    ,0 AS DEP_MK_JI_AMT        
    ,0 AS DEP_HJI_AMT         
    ,SUM(JIBANGSE_AMT)  AS SUNP_AMT     
    ,0             
    ,0             
    ,0             
    ,0             
   FROM   RPT_TXI_DDAC_TAB A
   WHERE  A.SIGUMGO_HOIKYE_YR = ( '2024' ) 
     AND A.SIGUMGO_ORG_C = '130'
     AND A.SUNAP_DT BETWEEN '20240522' AND '20240522'
     AND A.ICH_SIGUMGO_GUN_GU_C = 0    
     GROUP BY ICH_SIGUMGO_HOIKYE_C, A.SIGUMGO_ORG_C
  UNION ALL
  SELECT  TO_CHAR(HOIGYE_CODE) HOIGYE_CODE    
    ,GEUMGO_CODE
    ,0 TAX_SUNP_IP_AMT         
    ,0 TAX_BAEJUNG_IP_AMT       
    ,0 AS GWAON_PROC_JI_AMT       
    ,0 AS TAX_IP_CRT_IP_AMT        
    ,0 AS TAX_IP_CRT_JI_AMT        
    ,0 AS BIZPLC_BAEJUNG_JI_AMT      
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT     
    ,0 TAXO_JI_AMT          
    ,0 AS TAXO_RTRN_AMT        
    ,0 AS KWA_CRRC_IP_AMT        
    ,0 AS KWA_CRRC_JI_AMT        
    ,0 AS GA_IWOL_IP_AMT        
    ,0 AS GA_IWOL_JI_AMT        
    ,0 AS DEP_MK_JI_AMT        
    ,0 AS DEP_HJI_AMT         
    ,0             
    ,SUM(CASE WHEN GUBUN_CODE = 1 THEN AMT1 ELSE 0 END)   
    ,SUM(CASE WHEN GUBUN_CODE = 5 THEN AMT1 ELSE 0 END)   
    ,SUM(CASE WHEN GUBUN_CODE = 4 THEN AMT1 ELSE 0 END)   
    ,SUM(CASE WHEN GUBUN_CODE = 2 THEN AMT1 ELSE 0 END)             
   FROM   RPT_HOIGYE_IWOL A
   WHERE  A.HOIGYE_YEAR = ( '2024' - 1 ) 
     AND A.GEUMGO_CODE = '130'            
     AND A.GUBUN_CODE IN (1, 2, 4, 5)  
     AND A.KIJUNIL BETWEEN '20240522' AND '20240522'   
     AND A.GUNGU_CODE = 0     
     GROUP BY HOIGYE_CODE, GEUMGO_CODE
 ) 
 UNION ALL 
 
 SELECT   
    HOIGYE_CODE,    
    SIGUMGO_ORG_C,
    0 AS SEIB_SUIP,             
    0 AS SEIB_BANNAB,             
    0 AS SEIB_GYEONGJEONG_IB,             
    0 AS SEIB_GYEONGJEONG_JI,             
    0 AS SECHUL_BAEJEONG,             
    0 AS SECHUL_HWANSU,             
    0 AS SECHUL_JI,             
    0 AS SECHUL_BANNAB,             
    0 AS SECHUL_GYEONGJEONG_IB,             
    0 AS SECHUL_GYEONGJEONG_JI,             
    0 AS SEIB_GYULSANBF_IIB,             
    0 AS SECHUL_GYULSANBF_IWOL,             
    0 AS DEP,             
    0 AS HWANIB,             
    0 AS MIICHE, 
    NVL(SUNP_AMT,0) + NVL(TAX_BAEJUNG_IP_AMT,0) + NVL(IWOL_GONGGEUM,0)                                   
    - (NVL(SUNP_AMT,0) - NVL(TAX_SUNP_IP_AMT,0) + NVL(IWOL_MIJUNGSAN,0)) AS SEIB_SUIP2,             
    NVL(GWAON_PROC_JI_AMT,0) AS SEIB_BANNAB2,             
    NVL(TAX_IP_CRT_IP_AMT,0) AS SEIB_GYEONGJEONG_IB2,             
    NVL(TAX_IP_CRT_JI_AMT,0) AS SEIB_GYEONGJEONG_JI2,             
    NVL(BIZPLC_BAEJUNG_JI_AMT,0) AS SECHUL_BAEJEONG2,             
    NVL(BIZPLC_GAM_BAEJUNG_IP_AMT,0) AS SECHUL_HWANSU2,             
    NVL(TAXO_JI_AMT,0) AS SECHUL_JI2,             
    NVL(TAXO_RTRN_AMT,0) AS SECHUL_BANNAB2,             
    NVL(KWA_CRRC_IP_AMT,0) AS SECHUL_GYEONGJEONG_IB2,             
    NVL(KWA_CRRC_JI_AMT,0) AS SECHUL_GYEONGJEONG_JI2,             
    NVL(GA_IWOL_IP_AMT,0) AS SEIB_GYULSANBF_IIB2,             
    NVL(GA_IWOL_JI_AMT,0) AS SECHUL_GYULSANBF_IWOL2,             
    NVL(DEP_MK_JI_AMT,0) + NVL(IWOL_GONGGEUM_DEP,0) AS DEP2,             
    NVL(DEP_HJI_AMT,0) AS HWANIB2,             
    NVL(SUNP_AMT,0) - NVL(TAX_SUNP_IP_AMT,0) + NVL(IWOL_MIJUNGSAN,0) AS MIICHE2 
 FROM
 (
  SELECT   
      C.SIGUMGO_HOIKYE_C AS HOIGYE_CODE    
     ,A.SIGUMGO_ORG_C
     ,SUM(TAX_SUNP_IP_AMT) AS TAX_SUNP_IP_AMT         
     ,SUM(TAX_BAEJUNG_IP_AMT) AS TAX_BAEJUNG_IP_AMT       
     ,SUM(GWAON_PROC_JI_AMT) AS GWAON_PROC_JI_AMT      
     ,SUM(TAX_IP_CRT_IP_AMT) AS TAX_IP_CRT_IP_AMT        
     ,SUM(TAX_IP_CRT_JI_AMT) AS TAX_IP_CRT_JI_AMT        
     ,SUM(BIZPLC_BAEJUNG_JI_AMT) AS BIZPLC_BAEJUNG_JI_AMT     
     ,SUM(BIZPLC_GAM_BAEJUNG_IP_AMT) AS BIZPLC_GAM_BAEJUNG_IP_AMT  
    ,SUM(TAXO_FUND_BAEJUNG_JI_AMT)
     +SUM(TAXO_HNDO_BAEJUNG_JI_AMT)
     +SUM(TAXO_FUND_GETBK_JI_AMT)
     +SUM(TAXO_HNDO_JICHUL_JI_AMT)
     +SUM(TAXO_HNDO_GETBK_JI_AMT)  AS TAXO_JI_AMT      
    ,SUM(TAXO_RTRN_AMT) AS TAXO_RTRN_AMT         
    ,SUM(KWA_CRRC_IP_AMT) AS KWA_CRRC_IP_AMT        
    ,SUM(KWA_CRRC_JI_AMT) AS KWA_CRRC_JI_AMT        
    ,SUM(GA_IWOL_IP_AMT) AS GA_IWOL_IP_AMT         
    ,SUM(GA_IWOL_JI_AMT) AS GA_IWOL_JI_AMT         
    ,SUM(DEP_MK_JI_AMT) AS DEP_MK_JI_AMT          
    ,SUM(DEP_HJI_AMT) AS DEP_HJI_AMT           
    ,0 AS SUNP_AMT                
    ,0 AS IWOL_GONGGEUM              
    ,0 AS IWOL_MIJUNGSAN              
    ,0 AS IWOL_MMDA               
    ,0 AS IWOL_GONGGEUM_DEP             
  FROM RPT_TXIO_DDAC_TAB A,  ACL_SIGUMGO_MAS  B, RPT_AC_BY_HOIKYE_MAPP C
  WHERE  A.SGG_ACNO = B.FIL_100_CTNT2
  AND A.ICH_SIGUMGO_HOIKYE_C = B.ICH_SIGUMGO_HOIKYE_C
  AND A.SIGUMGO_ORG_C = B.SIGUMGO_ORG_C  
  AND B.FIL_100_CTNT2 = C.SIGUMGO_ACNO(+)
  AND B.SIGUMGO_HOIKYE_YR = C.SIGUMGO_HOIKYE_YR(+)
  AND B.SIGUMGO_ORG_C = C.SIGUMGO_C(+)    
  AND A.ICH_SIGUMGO_GUN_GU_C = '0'  
   AND CASE WHEN A.SIGUMGO_HOIKYE_YR = 9999 THEN TO_NUMBER(SUBSTR(A.BAS_DT,1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR) END  = '2024'
  AND A.BAS_DT BETWEEN SUBSTR('20240101',0,4)||'0101' AND '20240522'
  AND A.SIGUMGO_ORG_C = '130'
  AND B.MNG_NO = 1
  GROUP BY C.SIGUMGO_HOIKYE_C, A.SIGUMGO_ORG_C
  UNION ALL
  SELECT  TO_CHAR(ICH_SIGUMGO_HOIKYE_C) HOIGYE_CODE    
    ,A.SIGUMGO_ORG_C
    ,0 TAX_SUNP_IP_AMT         
    ,0 TAX_BAEJUNG_IP_AMT       
    ,0 AS GWAON_PROC_JI_AMT       
    ,0 AS TAX_IP_CRT_IP_AMT        
    ,0 AS TAX_IP_CRT_JI_AMT        
    ,0 AS BIZPLC_BAEJUNG_JI_AMT      
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT     
    ,0 TAXO_JI_AMT          
    ,0 AS TAXO_RTRN_AMT        
    ,0 AS KWA_CRRC_IP_AMT        
    ,0 AS KWA_CRRC_JI_AMT        
    ,0 AS GA_IWOL_IP_AMT        
    ,0 AS GA_IWOL_JI_AMT        
    ,0 AS DEP_MK_JI_AMT        
    ,0 AS DEP_HJI_AMT         
    ,SUM(JIBANGSE_AMT)  AS SUNP_AMT     
    ,0             
    ,0             
    ,0             
    ,0             
   FROM   RPT_TXI_DDAC_TAB A
   WHERE  A.SIGUMGO_HOIKYE_YR = ( '2024' - 1 ) 
     AND A.SIGUMGO_ORG_C = '130'     
     AND A.SUNAP_DT BETWEEN SUBSTR('20240101',0,4)||'0101'AND '20240522'
     AND A.ICH_SIGUMGO_GUN_GU_C = 0    
     GROUP BY ICH_SIGUMGO_HOIKYE_C, A.SIGUMGO_ORG_C
  UNION ALL 
  SELECT  TO_CHAR(HOIGYE_CODE) HOIGYE_CODE    
    ,A.GEUMGO_CODE
    ,0 TAX_SUNP_IP_AMT         
    ,0 TAX_BAEJUNG_IP_AMT       
    ,0 AS GWAON_PROC_JI_AMT       
    ,0 AS TAX_IP_CRT_IP_AMT        
    ,0 AS TAX_IP_CRT_JI_AMT        
    ,0 AS BIZPLC_BAEJUNG_JI_AMT      
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT     
    ,0 TAXO_JI_AMT          
    ,0 AS TAXO_RTRN_AMT        
    ,0 AS KWA_CRRC_IP_AMT        
    ,0 AS KWA_CRRC_JI_AMT        
    ,0 AS GA_IWOL_IP_AMT        
    ,0 AS GA_IWOL_JI_AMT        
    ,0 AS DEP_MK_JI_AMT        
    ,0 AS DEP_HJI_AMT         
    ,0             
    ,SUM(CASE WHEN GUBUN_CODE = 1 THEN AMT1 ELSE 0 END)   
    ,SUM(CASE WHEN GUBUN_CODE = 5 THEN AMT1 ELSE 0 END)   
    ,SUM(CASE WHEN GUBUN_CODE = 4 THEN AMT1 ELSE 0 END)   
    ,SUM(CASE WHEN GUBUN_CODE = 2 THEN AMT1 ELSE 0 END)   
    FROM   RPT_HOIGYE_IWOL A
   WHERE  A.HOIGYE_YEAR = ( '2024' - 1 ) 
     AND A.GEUMGO_CODE = '130'
     AND A.GUBUN_CODE IN (1, 2, 4, 5)
     AND A.KIJUNIL BETWEEN SUBSTR('20240101',0,4)||'0101' AND '20240522'
     AND A.GUNGU_CODE = 0     
     GROUP BY HOIGYE_CODE, A.GEUMGO_CODE
 )
) AA, RPT_HOIKYE_CD BB
WHERE AA.SIGUMGO_ORG_C(+) = BB.SIGUMGO_C
AND AA.HOIGYE_CODE(+) = BB.SIGUMGO_HOIKYE_C
  AND BB.SIGUMGO_HOIKYE_C IN(
      
       '1'
       
         )
   
AND BB.SIGUMGO_C = '130'
AND BB.USE_YN = 'Y'
GROUP BY BB.SIGUMGO_HOIKYE_C, BB.HOIKYE_NM
ORDER BY TO_NUMBER(BB.SIGUMGO_HOIKYE_C), BB.HOIKYE_NM

----------------------------------------------------
-- 원주시 공영개발 특별회계 자금운용내역이 조회되지 않는 이유
-- 세입세출일계표에서는 거래내역을 기준으로 자금운용내역을 표시
-- 거래내역중에서 12-3 예금신규, 62-3 예금해지가 있어야 자금운용내역에 표시가 되지만
-- 원주시는 해당 거래내역이 현재는 없음
-- 공영개발 특별회계의 2024-01-24에 신규된 s드림정기예금의 경우 예금액이 3,000,000,000원인데
-- 정상적인 상황이라면 13000080900000199에서 2024-01-24 에 12-3 예금신규 거래내역이 있어야 함
-- 하지만 해당일에는 12-3 예금신규 거래내역이 없으며, 3,000,000,000원의 지출거래도 없음
-- 자금운용 계좌관리에서 2024-01-23의 활동계좌 내역을 보면
-- 140-007-47739 슈퍼기업자유예금에 31,651,706,978 원이 있으며
-- 2024-01-24에는 슈퍼기업자유예금에 28,650,756,578 원이 있으며
-- s드림정기예금 3,000,000,000이 신규로 생성된 것으로 보아
-- 슈퍼기업자유예금에서 3,000,000,000원을 s드림정기예금으로 공금예금의 유동성계좌를 거치지 않고 이체한 것으로 보임


select SIGUMGO_TRX_G, SIGUMGO_IP_TRX_G, SIGUMGO_JI_TRX_G from ACL_SIGUMGO_SLV
where 1=1
and SIGUMGO_ORG_C = '130'
and FIL_100_CTNT5 = '13000080900000199'
group by SIGUMGO_TRX_G, SIGUMGO_IP_TRX_G, SIGUMGO_JI_TRX_G

select * from ACL_SIGUMGO_SLV
where 1=1
and SIGUMGO_ORG_C = '130'
and FIL_100_CTNT5 = '13000080900000199'
and SIGUMGO_TRX_G = 62

select * from ACL_SIGUMGO_MAS
where 1=1
and FIL_100_CTNT2 = '13000080900000199'
and MNG_NO = 1


select * from rpt_gonggeum_keorae
where GONGGEUM_GYEJWA = '13000080900000199'
and GEORAE_GUBUN = 62

select * from rpt_unyong_gyejwa
where GONGGEUM_GYEJWA = '13000080900000199'

----------------------------------------------------------------------
-- 원주시 회계별 자금운용 명세표에서 900 번대 회계들이 추가로 조회되는 이유

SELECT DECODE(SIGN(A.GONGGEUM_HOIGYE_CODE - 900), 1, A.GONGGEUM_HOIGYE_CODE, B.SIGUMGO_HOIKYE_C) AS GONGGEUM_HOIGYE_CODE
     , DECODE(SIGN(A.GONGGEUM_HOIGYE_CODE - 900), 1, A.GONGGEUM_GYEJWA_NM, B.HOIKYE_NM) AS HOIGYE_NAME
     , A.GUBUN
     , A.GONGGEUM_GYEJWA_NM
     , A.GONGGEUM_GYEJWA
     , A.SANGPUM_NAME
     , A.UNYONG_GYEJWA
     , A.HYUN_JAN
     , A.MKDT
     , A.DUDT
     , A.IYUL
     , TO_CHAR(TO_DATE(A.DUDT,'YYYYMMDD')-TO_DATE(A.MKDT,'YYYYMMDD'))  AS YECHI
  FROM 
(
       WITH WT_GYEJWA_INF_ALL AS
       (
            SELECT T1.SIGUMGO_ORG_C AS GONGGEUM_GEUMGO_CD
                 , T1.SIGUMGO_GUN_GU_C AS GONGGEUM_GUNGU_CODE
                 , TO_NUMBER(T2.SIGUMGO_HOIKYE_C) AS GONGGEUM_HOIGYE_CODE
                 , T1.SIGUMGO_HOIKYE_YR AS GONGGEUM_HOIGYE_YEAR
                 , T1.SIGUMGO_ACNO AS GONGGEUM_GYEJWA
                 , T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
              FROM ACL_SIGUMGO_MAS_SUB T1
              INNER JOIN RPT_AC_BY_HOIKYE_MAPP T2
                      ON T1.SIGUMGO_ACNO = T2.SIGUMGO_ACNO
                     AND T1.SIGUMGO_HOIKYE_YR = T2.SIGUMGO_HOIKYE_YR
              WHERE T1.SIGUMGO_ORG_C = '130'
                AND (   ('1' = 'ALL')
                     OR (LENGTH('1')  = 4 AND T2.SIGUMGO_HOIKYE_C IN (SELECT TO_NUMBER(SIGUMGO_HOIKYE_C) FROM RPT_HOIKYE_GRP_HOIKYE_CD WHERE SIGUMGO_C = '130' AND HOIKYE_GRP_ID = '1'))
                     OR (LENGTH('1') != 4 AND T2.SIGUMGO_HOIKYE_C = '1'))
       ), WT_GYEJWA_INF AS
       (
            SELECT GONGGEUM_GEUMGO_CD
                 , GONGGEUM_GUNGU_CODE
                 , GONGGEUM_HOIGYE_CODE
                 , GONGGEUM_HOIGYE_YEAR
                 , GONGGEUM_GYEJWA
                 , GONGGEUM_GYEJWA_NM
              FROM WT_GYEJWA_INF_ALL 
              WHERE GONGGEUM_GEUMGO_CD = '130'
                AND (   (GONGGEUM_HOIGYE_YEAR = '2024') 
                     OR (GONGGEUM_HOIGYE_YEAR = 9999 AND SUBSTR('20240523' ,1,4) = '2024')) 
        ) 

       SELECT B.GONGGEUM_HOIGYE_CODE, B.GONGGEUM_GYEJWA_NM HOIGYE_NAME
    , 1 GUBUN
    , B.GONGGEUM_GYEJWA, B.GONGGEUM_GYEJWA_NM,
              B.GONGGEUM_GYEJWA UNYONG_GYEJWA, '공금예금' SANGPUM_NAME, '' MKDT, '' DUDT, 0 IYUL,
              SUM(DECODE(A.CRT_CAN_G, 1,-1,2,-1,33,-1,1) * DECODE(A.IPJI_G,1,1,-1) * A.TRAMT) HYUN_JAN
         FROM ACL_SIGUMGO_SLV A, WT_GYEJWA_INF B
        WHERE A.FIL_100_CTNT5 = B.GONGGEUM_GYEJWA
          AND A.GISDT BETWEEN '20070205' AND '20240523'
          AND B.GONGGEUM_GUNGU_CODE = 0
        GROUP BY B.GONGGEUM_HOIGYE_CODE, B.GONGGEUM_GYEJWA_NM, B.GONGGEUM_GYEJWA, B.GONGGEUM_GYEJWA_NM

        UNION ALL

       SELECT A.GONGGEUM_HOIGYE_CODE, A.GONGGEUM_GYEJWA_NM HOIGYE_NAME
    , CASE SUBSTR(B.UNYONG_GYEJWA, 1, 3) 
   WHEN '200' THEN 2
   WHEN '140' THEN 3
   WHEN '100' THEN 4
  ELSE 6 END AS GUBUN
    , A.GONGGEUM_GYEJWA, A.GONGGEUM_GYEJWA_NM
    , B.UNYONG_GYEJWA, B.SANGPUM_NAME, C.MKDT, C.DUDT, C.IYUL, NVL(C.JANAEK, 0) AS JANAEK
         FROM WT_GYEJWA_INF A, RPT_UNYONG_GYEJWA B, RPT_UNYONG_JAN C
        WHERE A.GONGGEUM_GYEJWA >= B.GONGGEUM_GYEJWA
          AND SUBSTR(A.GONGGEUM_GYEJWA,1,15) = SUBSTR(B.GONGGEUM_GYEJWA,1,15)
          AND B.GONGGEUM_GYEJWA = C.GONGGEUM_GYEJWA
          AND (   (A.GONGGEUM_HOIGYE_YEAR <> 9999 AND A.GONGGEUM_GYEJWA >= B.GONGGEUM_GYEJWA) 
               OR (A.GONGGEUM_HOIGYE_YEAR  = 9999 AND A.GONGGEUM_GYEJWA  = B.GONGGEUM_GYEJWA))
          AND B.GONGGEUM_GYEJWA IN ( SELECT Z.GONGGEUM_GYEJWA
                                       FROM WT_GYEJWA_INF X, RPT_HOIGYE_IWOL Y, WT_GYEJWA_INF_ALL Z
                                      WHERE X.GONGGEUM_GEUMGO_CD = Y.GEUMGO_CODE
                                        AND X.GONGGEUM_HOIGYE_CODE = Y.HOIGYE_CODE
                                        AND X.GONGGEUM_GUNGU_CODE = Y.GUNGU_CODE
                                        AND X.GONGGEUM_HOIGYE_YEAR = Y.HOIGYE_YEAR + 1
                                        AND X.GONGGEUM_GEUMGO_CD = '130'
                                        AND X.GONGGEUM_HOIGYE_YEAR = '2024'
                                        AND Y.GUBUN_CODE = 1
                                        AND Y.KIJUNIL <= '20240523'
                                        AND X.GONGGEUM_GEUMGO_CD = Z.GONGGEUM_GEUMGO_CD
                                        AND X.GONGGEUM_HOIGYE_CODE = Z.GONGGEUM_HOIGYE_CODE
                                        AND X.GONGGEUM_GUNGU_CODE = Z.GONGGEUM_GUNGU_CODE
                                        AND X.GONGGEUM_HOIGYE_YEAR > Z.GONGGEUM_HOIGYE_YEAR
                                      UNION
                                     SELECT A.GONGGEUM_GYEJWA
                                       FROM WT_GYEJWA_INF A
                                   )
          AND B.UNYONG_GYEJWA = C.UNYONG_GYEJWA
          AND SUBSTR(NVL(B.MKDT,B.IN_DATE),1,8) <= '20240523'
          AND (B.OUT_DATE IS NULL OR B.OUT_DATE > '20240523' )
          AND (B.HJI_DT IS NULL OR B.HJI_DT > '20240523' )
          AND B.BANK_GUBUN = 0
          AND C.KIJUNIL = '20240523'
          AND A.GONGGEUM_GUNGU_CODE = 0

       UNION ALL  

       SELECT A.HOIGYE_CODE, A.GYEJWA_NAME HOIGYE_NAME
    , CASE SUBSTR(B.UNYONG_GYEJWA, 1, 3) 
   WHEN '200' THEN 2
   WHEN '140' THEN 3
   WHEN '100' THEN 4
  ELSE 6 END AS GUBUN
    , A.GONGGEUM_GYEJWA, A.GYEJWA_NAME,
              B.UNYONG_GYEJWA, B.SANGPUM_NAME, C.MKDT, C.DUDT, C.IYUL, NVL(C.JANAEK, 0) AS JANAEK
         FROM
              (SELECT A.REF_D_NM GONGGEUM_GYEJWA, A.REF_CTNT1 GYEJWA_NAME,
                      A.REF_S_C MNGBR, TO_NUMBER(SUBSTR(A.REF_D_NM,4,3)) GUNGU_CODE,
                      900+REF_D_C HOIGYE_CODE, 99 GYEJWA_BUNRYU
                 FROM RPT_CODE_INFO A
                WHERE A.REF_L_C = 50
                  AND A.REF_M_C = '130'
                  AND A.YUHYO_YN = 0 ) A
             , RPT_UNYONG_GYEJWA B
             , RPT_UNYONG_JAN C
         WHERE A.GONGGEUM_GYEJWA = B.GONGGEUM_GYEJWA
           AND B.GONGGEUM_GYEJWA = C.GONGGEUM_GYEJWA
           AND A.GONGGEUM_GYEJWA = B.GONGGEUM_GYEJWA
           AND B.UNYONG_GYEJWA = C.UNYONG_GYEJWA
           AND SUBSTR(NVL(B.MKDT,B.IN_DATE),1,8) <= '20240523'
           AND (B.OUT_DATE IS NULL OR B.OUT_DATE > '20240523' )
           AND (B.HJI_DT IS NULL OR B.HJI_DT > '20240523' )
           AND B.BANK_GUBUN = 0
           AND C.KIJUNIL = '20240523'
           AND SUBSTR('20240523' ,1,4) = '2024'
           AND A.GUNGU_CODE = 0

         UNION ALL 

        SELECT C.GONGGEUM_HOIGYE_CODE, C.GONGGEUM_GYEJWA_NM HOIGYE_NAME
  , 5 GUBUN, A.GONGGEUM_GYEJWA, C.GONGGEUM_GYEJWA_NM,
               D.UNYONG_GYEJWA, '통합공금' SANGPUM_NAME, D.MKDT, D.DUDT, NVL(D.IYUL,0),  NVL(A.JANAEK, 0) AS JANAEK
          FROM RPT_UNYONG_JAN A, RPT_AC_BY_HOIKYE_MAPP B, WT_GYEJWA_INF C, RPT_UNYONG_JAN D
         WHERE A.GONGGEUM_GYEJWA = C.GONGGEUM_GYEJWA
           AND B.SIGUMGO_ACNO = D.GONGGEUM_GYEJWA
           AND B.SIGUMGO_C = D.GEUMGO_CODE
           AND A.GEUMGO_CODE = '130'
           AND A.UNYONG_GYEJWA = '000000000000'
           AND A.KIJUNIL = '20240523'
           AND B.SIGUMGO_HOIKYE_YR = '9999'
           AND B.SIGUMGO_HOIKYE_C = '99'
           AND D.GEUMGO_CODE = '130'
           AND D.KIJUNIL = '20240523'
           AND C.GONGGEUM_GUNGU_CODE = 0
 ) A
     , RPT_HOIKYE_CD B
 WHERE 1 = 1
   AND DECODE(SIGN(A.GONGGEUM_HOIGYE_CODE - 900), 1, 1, A.GONGGEUM_HOIGYE_CODE) = B.SIGUMGO_HOIKYE_C
   AND A.GONGGEUM_HOIGYE_CODE != 98
   AND B.SIGUMGO_C = '130'
   AND B.SIGUMGO_HOIKYE_C != 98
   AND B.USE_YN = 'Y' 
 ORDER BY TO_NUMBER(DECODE(SIGN(A.GONGGEUM_HOIGYE_CODE - 900), 1, A.GONGGEUM_HOIGYE_CODE, B.SIGUMGO_HOIKYE_C))
        , A.HOIGYE_NAME, A.GUBUN, A.SANGPUM_NAME, A.GONGGEUM_GYEJWA, A.UNYONG_GYEJWA
--------------------------------------------------------------------------------------------------------------------

select * from RPT_SUNAP_JIBGYE
where 1=1
and hoikye_smok_c = 281020



----------------------------------------------------------------------

select * from ACL_SIGUMGO_SLV
where 1=1
and SIGUMGO_ORG_C = 28
and trxdt like '2024%'
and CRT_CAN_G in (2, 33)
and ICH_SIGUMGO_HOIKYE_C in (23, 24, 25, 30)
and SIGUMGO_TRX_G = 11
and SIGUMGO_AC_B = 10
and (
    (ICH_SIGUMGO_HOIKYE_C = 30 and immd_proc_dsyn = 1)
    OR
    (ICH_SIGUMGO_HOIKYE_C <> 30)
)