SELECT
   T.HOIGYE_YEAR
   ,T.HOIGYE_CODE AS HOIGYE_CODE_VAL
   ,LPAD(T.HOIGYE_CODE,2,'0') AS HOIGYE_CODE
   ,U.HOIKYE_NM AS HOIGYE_NAME
     ,TO_CHAR(T.GUNGU_CODE) AS GUNGU_CODE_VAL
     ,LPAD(T.GUNGU_CODE,3,'0') AS GUNGU_CODE
     ,W.CMM_DTL_C_NM AS GUNGU_NAME
   ,T.KIJUNIL
     ,TO_CHAR(NVL(T.AMT1,0)) AS GONGGUEM
     ,TO_CHAR(NVL(T.AMT2,0)) AS JAGUEMUNYONG
     ,TO_CHAR(NVL(T.AMT3,0)) AS ETC 
     ,TO_CHAR(NVL(T.AMT4,0)) AS MMDA_MMF
     ,TO_CHAR(NVL(T.AMT5,0)) AS MIJUNGSAN
     ,TO_CHAR(NVL(T.AMT6,0)) AS JUNBUGUEM
     ,'0' AS KITA
     ,'0' AS BIGO
    FROM
   ( SELECT KIJUNIL, GUNGU_CODE, HOIGYE_YEAR, HOIGYE_CODE, GEUMGO_CODE,
        SUM(CASE WHEN GUBUN_CODE = 1 THEN AMT1 ELSE 0 END) AMT1, 
        SUM(CASE WHEN GUBUN_CODE = 2 THEN AMT1 ELSE 0 END) AMT2, 
        SUM(CASE WHEN GUBUN_CODE = 3 THEN AMT1 ELSE 0 END) AMT3, 
        SUM(CASE WHEN GUBUN_CODE = 4 THEN AMT1 ELSE 0 END) AMT4,
        SUM(CASE WHEN GUBUN_CODE = 5 THEN AMT1 ELSE 0 END) AMT5,
        SUM(CASE WHEN GUBUN_CODE = 6 THEN AMT1 ELSE 0 END) AMT6
         FROM RPT_HOIGYE_IWOL A
      WHERE 1=1
          AND HOIGYE_YEAR = '2023'
          AND GEUMGO_CODE = '130'
          AND GUNGU_CODE = '0'
          AND GUBUN_CODE IN (1, 2, 3, 4, 5, 6)
   AND DECODE(NVL('', 'ALL'), 'ALL', 9999, HOIGYE_CODE) = DECODE(NVL('', 'ALL'), 'ALL', 9999, '')
        GROUP BY KIJUNIL, HOIGYE_YEAR, HOIGYE_CODE, GUNGU_CODE, GEUMGO_CODE
   ) T,
   (SELECT SIGUMGO_HOIKYE_C , HOIKYE_NM
   FROM RPT_HOIKYE_CD
   WHERE SIGUMGO_C = '130'
   ) U,
   (SELECT HRNK_CMM_DTL_C,CMM_DTL_C_NM 
   FROM SFI_CMM_C_DAT
   WHERE CMM_C_NM =  'RPT군구코드'
   AND HRNK_CMM_DTL_C = '130'
   AND TO_NUMBER(CMM_DTL_C) = 0
   ) W
  WHERE T.HOIGYE_CODE = U.SIGUMGO_HOIKYE_C
    AND T.GEUMGO_CODE = W.HRNK_CMM_DTL_C
  ORDER BY T.HOIGYE_CODE