SELECT
    RPAD(NVL(A.LAF_CD, '0'), 7, ' ') ||
    RPAD(NVL(A.GOF_CD, '0'), 4, ' ') ||
    RPAD(NVL(A.GOF_NM, '0'), 300, ' ') ||
    RPAD(NVL(A.FYR, '0'), 4, ' ') ||
    RPAD(NVL(A.ACNT_DV_CD, '0'), 3, ' ') ||
    RPAD(NVL(A.ACNT_DV_NM, '0'), 300, ' ') ||
    RPAD(NVL(A.ACNT_YMD, '0'), 8, ' ') ||
    RPAD(NVL(A.RCVMT_AMT, '0' ), 20, ' ') ||
    RPAD(NVL(A.RFN_AMT, '0' ), 20, ' ') ||
    RPAD(NVL(A.TXRV_SBJ_RVSN_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.TXRV_DD_SUM_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.FDAC_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.FDAC_RTN_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.FDAC_RAMT_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.EP_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.RTN_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.ANE_SBJ_RVSN_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.ANE_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.PMOD_NPYM_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.FD_BDTR_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.FD_OP_DPI_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.FD_OP_CNLT_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.FD_OP_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.STBX_RAMT_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.UNDL_TRSFR_AMT, '0'), 20, ' ') ||
    RPAD(NVL(A.STBX_BANK_CD, '0'), 3, ' ') AS DYMNSUM
FROM
(
    SELECT
        E.CMM_DTL_C AS LAF_CD,
        '0010' AS GOF_CD, 
        '본청' AS GOF_NM,
        2024 AS FYR,
        C.ACNT_DV_CD AS ACNT_DV_CD,
        C.ACNT_DV_NM AS ACNT_DV_NM,
        '20240610' AS ACNT_YMD,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) AS RCVMT_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS RFN_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS TXRV_SBJ_RVSN_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) AS TXRV_DD_SUM_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('61-1', '61-2') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('14-6', '14-7') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS FDAC_AMT,
        0 AS FDAC_RTN_AMT,
        0 AS FDAC_RAMT_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) AS EP_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1)) * -1) AS RTN_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('18-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS ANE_SBJ_RVSN_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) * -1) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('18-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS ANE_AMT,
        0 AS PMOD_NPYM_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS FD_BDTR_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS FD_OP_DPI_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS FD_OP_CNLT_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS FD_OP_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        (
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('61-1', '61-2') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('14-6', '14-7') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) * -1) +
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('18-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS STBX_RAMT_AMT,
        0 AS UNDL_TRSFR_AMT,
        6 AS DAY_MON_FG,
        '088' AS STBX_BANK_CD
FROM ACL_SIGUMGO_SLV A, ACL_SIGUMGO_MAS B, RPT_FISG_INFO_MAP C, SFI_CMM_C_DAT E 
WHERE 1=1
AND A.SIGUMGO_ORG_C = B.SIGUMGO_ORG_C
AND A.FIL_100_CTNT5 = B.FIL_100_CTNT2
AND C.GONGGEUM_GYEJWA = B.FIL_100_CTNT2
AND B.MNG_NO = 1
AND E.CMM_C_NM = 'RPT자치단체코드분류'
AND E.HRNK_CMM_DTL_C = A.SIGUMGO_ORG_C
AND E.UPMU_HMK_1_SLV = A.ICH_SIGUMGO_GUN_GU_C
AND E.CMM_DTL_C = C.LAF_CD(+)
AND NOT (A.SIGUMGO_ORG_C = 28 AND A.ICH_SIGUMGO_GUN_GU_C IN ('260', '710', '720'))
AND GJDT BETWEEN '20240610' AND '20240610'
AND A.SIGUMGO_ORG_C = 28
AND C.FYR = 2024
GROUP BY E.CMM_DTL_C, C.ACNT_DV_CD, C.ACNT_DV_NM, A.SIGUMGO_ORG_C, A.ICH_SIGUMGO_GUN_GU_C
) A

-------------------------------------------------------------------------------------------------


    SELECT
        E.CMM_DTL_C AS LAF_CD,
        '0010' AS GOF_CD, 
        '본청' AS GOF_NM,
        2024 AS FYR,
        C.ACNT_DV_CD AS ACNT_DV_CD,
        C.ACNT_DV_NM AS ACNT_DV_NM,
        '20240610' AS ACNT_YMD,
        C.GONGGEUM_GYEJWA AS GONGGEUM_GYEJWA,
        (A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G) AS TRX_G,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) AS RCVMT_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS RFN_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS TXRV_SBJ_RVSN_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) AS TXRV_DD_SUM_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('61-1', '61-2') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('14-6', '14-7') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS FDAC_AMT,
        0 AS FDAC_RTN_AMT,
        0 AS FDAC_RAMT_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) AS EP_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1)) * -1) AS RTN_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('18-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS ANE_SBJ_RVSN_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) * -1) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('18-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS ANE_AMT,
        0 AS PMOD_NPYM_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS FD_BDTR_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS FD_OP_DPI_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS FD_OP_CNLT_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS FD_OP_AMT,
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        (
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('61-1', '61-2') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('14-6', '14-7') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) * -1) +
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('18-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            SUM((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS STBX_RAMT_AMT,
        0 AS UNDL_TRSFR_AMT,
        6 AS DAY_MON_FG,
        '088' AS STBX_BANK_CD
FROM ACL_SIGUMGO_SLV A, ACL_SIGUMGO_MAS B, RPT_FISG_INFO_MAP C, SFI_CMM_C_DAT E 
WHERE 1=1
AND A.SIGUMGO_ORG_C = B.SIGUMGO_ORG_C
AND A.FIL_100_CTNT5 = B.FIL_100_CTNT2
AND C.GONGGEUM_GYEJWA = B.FIL_100_CTNT2
AND B.MNG_NO = 1
AND E.CMM_C_NM = 'RPT자치단체코드분류'
AND E.HRNK_CMM_DTL_C = A.SIGUMGO_ORG_C
AND E.UPMU_HMK_1_SLV = A.ICH_SIGUMGO_GUN_GU_C
AND E.CMM_DTL_C = C.LAF_CD(+)
AND NOT (A.SIGUMGO_ORG_C = 28 AND A.ICH_SIGUMGO_GUN_GU_C IN ('260', '710', '720'))
AND GJDT BETWEEN '20240610' AND '20240610'
AND A.SIGUMGO_ORG_C = 28
AND C.FYR = 2024
GROUP BY E.CMM_DTL_C, C.ACNT_DV_CD, C.ACNT_DV_NM, A.SIGUMGO_ORG_C, A.ICH_SIGUMGO_GUN_GU_C, (A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G), C.GONGGEUM_GYEJWA


-------------------------------------------------------------------------------------------------

SELECT
        E.CMM_DTL_C AS LAF_CD,
        '0010' AS GOF_CD, 
        '본청' AS GOF_NM,
        2024 AS FYR,
        C.ACNT_DV_CD AS ACNT_DV_CD,
        C.ACNT_DV_NM AS ACNT_DV_NM,
        '20240610' AS ACNT_YMD,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1)))
        ) AS RCVMT_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS RFN_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS TXRV_SBJ_RVSN_AMT,
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1)))
        ) AS TXRV_DD_SUM_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('61-1', '61-2') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('14-6', '14-7') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS FDAC_AMT,
        0 AS FDAC_RTN_AMT,
        0 AS FDAC_RAMT_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) AS EP_AMT,
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1)) * -1) AS RTN_AMT,
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('18-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS ANE_SBJ_RVSN_AMT,
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('20-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('70-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) * -1) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('71-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('21-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) 
        ) AS ANE_AMT,
        0 AS PMOD_NPYM_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS FD_BDTR_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS FD_OP_DPI_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) 
        ) AS FD_OP_CNLT_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS FD_OP_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        (
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('61-1', '61-2') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('14-6', '14-7') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) * -1) +
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('18-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) 
        )AS STBX_RAMT_AMT,
        0 AS UNDL_TRSFR_AMT,
        6 AS DAY_MON_FG,
        '088' AS STBX_BANK_CD
FROM ACL_SIGUMGO_SLV A, ACL_SIGUMGO_MAS B, RPT_FISG_INFO_MAP C, SFI_CMM_C_DAT E 
WHERE 1=1
AND A.SIGUMGO_ORG_C = B.SIGUMGO_ORG_C
AND A.FIL_100_CTNT5 = B.FIL_100_CTNT2
AND C.GONGGEUM_GYEJWA = B.FIL_100_CTNT2
AND B.MNG_NO = 1
AND E.CMM_C_NM = 'RPT자치단체코드분류'
AND E.HRNK_CMM_DTL_C = A.SIGUMGO_ORG_C
AND E.UPMU_HMK_1_SLV = A.ICH_SIGUMGO_GUN_GU_C
AND E.CMM_DTL_C = C.LAF_CD(+)
AND NOT (A.SIGUMGO_ORG_C = 28 AND A.ICH_SIGUMGO_GUN_GU_C IN ('260', '710', '720'))
AND GJDT BETWEEN '20240610' AND '20240610'
AND A.SIGUMGO_ORG_C = 28
AND C.FYR = 2024

---------------------------------------------------------------------------------------------------------

SELECT
        E.CMM_DTL_C AS LAF_CD,
        '0010' AS GOF_CD, 
        '본청' AS GOF_NM,
        2024 AS FYR,
        C.ACNT_DV_CD AS ACNT_DV_CD,
        C.ACNT_DV_NM AS ACNT_DV_NM,
        '20240610' AS ACNT_YMD,
        (A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G) AS TRX_G, 
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1)))
        ) AS RCVMT_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS RFN_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS TXRV_SBJ_RVSN_AMT,
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1)))
        ) AS TXRV_DD_SUM_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('61-1', '61-2') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('14-6', '14-7') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS FDAC_AMT,
        0 AS FDAC_RTN_AMT,
        0 AS FDAC_RAMT_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) AS EP_AMT,
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1)) * -1) AS RTN_AMT,
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('18-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) AS ANE_SBJ_RVSN_AMT,
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('20-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('70-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) * -1) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('71-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('21-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) 
        ) AS ANE_AMT,
        0 AS PMOD_NPYM_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS FD_BDTR_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS FD_OP_DPI_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) 
        ) AS FD_OP_CNLT_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) AS FD_OP_AMT,
        (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('60-0', '66-0', '62-4', '63-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('15-0', '16-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('68-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('64-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) +
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('69-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))) -
        (
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('61-1', '61-2') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('14-6', '14-7') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) * -1) +
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('18-0') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-5') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) +
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))) -
            ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * (DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)))
        ) 
        )AS STBX_RAMT_AMT,
        0 AS UNDL_TRSFR_AMT,
        6 AS DAY_MON_FG,
        '088' AS STBX_BANK_CD
FROM ACL_SIGUMGO_SLV A, ACL_SIGUMGO_MAS B, RPT_FISG_INFO_MAP C, SFI_CMM_C_DAT E 
WHERE 1=1
AND A.SIGUMGO_ORG_C = B.SIGUMGO_ORG_C
AND A.FIL_100_CTNT5 = B.FIL_100_CTNT2
AND C.GONGGEUM_GYEJWA = B.FIL_100_CTNT2
AND B.MNG_NO = 1
AND E.CMM_C_NM = 'RPT자치단체코드분류'
AND E.HRNK_CMM_DTL_C = A.SIGUMGO_ORG_C
AND E.UPMU_HMK_1_SLV = A.ICH_SIGUMGO_GUN_GU_C
AND E.CMM_DTL_C = C.LAF_CD(+)
AND NOT (A.SIGUMGO_ORG_C = 28 AND A.ICH_SIGUMGO_GUN_GU_C IN ('260', '710', '720'))
AND GJDT BETWEEN '20240610' AND '20240610'
AND A.SIGUMGO_ORG_C = 28
AND C.FYR = 2024
GROUP BY E.CMM_DTL_C, C.ACNT_DV_CD, C.ACNT_DV_NM, A.SIGUMGO_ORG_C, A.ICH_SIGUMGO_GUN_GU_C, (A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G)
-------------------------------------------------------------------------------------------------

SELECT
    E.CMM_DTL_C AS LAF_CD,
    '0010' AS GOF_CD, 
    '본청' AS GOF_NM,
    2024 AS FYR,
    C.ACNT_DV_CD AS ACNT_DV_CD,
    C.ACNT_DV_NM AS ACNT_DV_NM,
    '20240610' AS ACNT_YMD,
    C.GONGGEUM_GYEJWA,
    (
      (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)  
    ) AS RCVMT_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) 
    ) AS RCVMT_AMT,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0', '64-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)) 
    ) AS RFN_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0', '64-0') THEN  A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) 
    ) AS RFN_AMT,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9', '69-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) 
    ) AS TXRV_SBJ_RVSN_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9', '69-0') THEN  A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)) 
    ) AS TXRV_SBJ_RVSN_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0', '24-0', '64-0', '19-8', '19-9', '69-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)
    ) AS TXRV_DD_SUM_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0', '24-0', '64-0', '19-8', '19-9', '69-0') THEN  A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))
    ) AS TXRV_DD_SUM_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0', '24-0', '64-0', '19-8', '19-9', '69-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)
    ) AS FDAC_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('61-1', '61-2', '14-6', '14-7') THEN A.TRAMT ELSE 0 END)  * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))
    ) AS FDAC_AMT,
    0 AS FDAC_RTN_AMT,
    0 AS FDAC_RAMT_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('67-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)
    ) AS EP_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1))
    ) AS EP_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)
    ) AS RTN_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1) * -1)
    ) AS RTN_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('65-0', '18-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)
    ) AS ANE_SBJ_RVSN_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0', '18-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))
    ) AS ANE_SBJ_RVSN_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('20-0', '70-0', '71-0', '21-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)
    ) AS ANE_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('20-0', '70-0', '71-0', '21-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))
    ) AS ANE_AMT,
    0 AS PMOD_NPYM_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('62-5', '12-5') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)
    ) AS FD_BDTR_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('62-5', '12-5') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))
    ) AS FD_BDTR_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('62-3') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)
    ) AS FD_OP_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))
    ) AS FD_OP_DPI_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)
    ) AS FD_OP_CNLT_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))
    ) AS FD_OP_CNLT_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('62-3', '12-3') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)
    ) AS FD_OP_AMT,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('62-3', '12-3') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))
    ) AS FD_OP_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0', '24-0', '64-0', '19-8', '19-9', '69-0', '61-1', '61-2', '14-6', '14-7', '67-0', '17-0', '65-0', '18-0', '62-5', '12-5', '62-3', '12-3') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE 0 END)
    ) AS STBX_RAMT_G,
    (
        ((CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0', '24-0', '64-0', '19-8', '19-9', '69-0', '61-1', '61-2', '14-6', '14-7', '67-0', '17-0', '65-0', '18-0', '62-5', '12-5', '62-3', '12-3') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1))
    ) AS STBX_RAMT_AMT,
    0 AS UNDL_TRSFR_AMT,
    6 AS DAY_MON_FG,
    '088' AS STBX_BANK_CD
FROM ACL_SIGUMGO_SLV A
JOIN ACL_SIGUMGO_MAS B ON A.SIGUMGO_ORG_C = B.SIGUMGO_ORG_C AND A.FIL_100_CTNT5 = B.FIL_100_CTNT2
JOIN RPT_FISG_INFO_MAP C ON C.GONGGEUM_GYEJWA = B.FIL_100_CTNT2
LEFT JOIN SFI_CMM_C_DAT E ON E.CMM_DTL_C = C.LAF_CD
WHERE 1=1
AND B.MNG_NO = 1
AND E.CMM_C_NM = 'RPT자치단체코드분류'
AND E.HRNK_CMM_DTL_C = A.SIGUMGO_ORG_C
AND E.UPMU_HMK_1_SLV = A.ICH_SIGUMGO_GUN_GU_C
AND NOT (A.SIGUMGO_ORG_C = 28 AND A.ICH_SIGUMGO_GUN_GU_C IN ('260', '710', '720'))
AND A.GJDT BETWEEN '20240610' AND '20240610'
AND A.SIGUMGO_ORG_C = 28
AND C.FYR = 2024
GROUP BY E.CMM_DTL_C, C.ACNT_DV_CD, C.ACNT_DV_NM, A.SIGUMGO_ORG_C, A.ICH_SIGUMGO_GUN_GU_C, (A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G), A.TRAMT, A.CRT_CAN_G, C.GONGGEUM_GYEJWA

-----------------------------------------------------

SELECT
    E.CMM_DTL_C AS LAF_CD,
    '0010' AS GOF_CD, 
    '본청' AS GOF_NM,
    2024 AS FYR,
    C.ACNT_DV_CD AS ACNT_DV_CD,
    C.ACNT_DV_NM AS ACNT_DV_NM,
    '20240610' AS ACNT_YMD,
    C.GONGGEUM_GYEJWA,
    (
      CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS RCVMT_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS RCVMT_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0', '64-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS RFN_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('24-0', '64-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS RFN_AMT,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9', '69-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS TXRV_SBJ_RVSN_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('19-8', '19-9', '69-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS TXRV_SBJ_RVSN_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0', '24-0', '64-0', '19-8', '19-9', '69-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS TXRV_DD_SUM_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0', '24-0', '64-0', '19-8', '19-9', '69-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1)
    ) AS TXRV_DD_SUM_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0', '24-0', '64-0', '19-8', '19-9', '69-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS FDAC_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('61-1', '61-2', '14-6', '14-7') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS FDAC_AMT,
    0 AS FDAC_RTN_AMT,
    0 AS FDAC_RAMT_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('67-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS EP_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('67-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1)
    ) AS EP_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS RTN_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('17-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, 1, 2, 1, 33, 1, 1) * -1
    ) AS RTN_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('65-0', '18-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS ANE_SBJ_RVSN_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('65-0', '18-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS ANE_SBJ_RVSN_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('20-0', '70-0', '71-0', '21-0') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS ANE_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('20-0', '70-0', '71-0', '21-0') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS ANE_AMT,
    0 AS PMOD_NPYM_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('62-5', '12-5') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS FD_BDTR_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('62-5', '12-5') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS FD_BDTR_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('62-3') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS FD_OP_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G IN ('62-3') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS FD_OP_DPI_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS FD_OP_CNLT_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('12-3') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS FD_OP_CNLT_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('62-3', '12-3') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS FD_OP_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('62-3', '12-3') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS FD_OP_AMT,
    (
        CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0', '24-0', '64-0', '19-8', '19-9', '69-0', '61-1', '61-2', '14-6', '14-7', '67-0', '17-0', '65-0', '18-0', '62-5', '12-5', '62-3', '12-3') THEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G ELSE '0' END
    ) AS STBX_RAMT_G,
    (
        (CASE WHEN A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_IP_TRX_G IN ('10-0', '11-1', '11-2', '12-4', '13-0', '60-0', '66-0', '62-4', '63-0', '15-0', '16-0', '68-0', '24-0', '64-0', '19-8', '19-9', '69-0', '61-1', '61-2', '14-6', '14-7', '67-0', '17-0', '65-0', '18-0', '62-5', '12-5', '62-3', '12-3') THEN A.TRAMT ELSE 0 END) * DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1)
    ) AS STBX_RAMT_AMT,
    0 AS UNDL_TRSFR_AMT,
    6 AS DAY_MON_FG,
    '088' AS STBX_BANK_CD
FROM ACL_SIGUMGO_SLV A
JOIN ACL_SIGUMGO_MAS B ON A.SIGUMGO_ORG_C = B.SIGUMGO_ORG_C AND A.FIL_100_CTNT5 = B.FIL_100_CTNT2
JOIN RPT_FISG_INFO_MAP C ON C.GONGGEUM_GYEJWA = B.FIL_100_CTNT2
LEFT JOIN SFI_CMM_C_DAT E ON E.CMM_DTL_C = C.LAF_CD
WHERE B.MNG_NO = 1
AND E.CMM_C_NM = 'RPT자치단체코드분류'
AND E.HRNK_CMM_DTL_C = A.SIGUMGO_ORG_C
AND E.UPMU_HMK_1_SLV = A.ICH_SIGUMGO_GUN_GU_C
AND NOT (A.SIGUMGO_ORG_C = 28 AND A.ICH_SIGUMGO_GUN_GU_C IN ('260', '710', '720'))
AND A.GJDT BETWEEN '20240610' AND '20240610'
AND A.SIGUMGO_ORG_C = 28
AND C.FYR = 2024
GROUP BY E.CMM_DTL_C, C.ACNT_DV_CD, C.ACNT_DV_NM, A.SIGUMGO_ORG_C, A.ICH_SIGUMGO_GUN_GU_C, C.GONGGEUM_GYEJWA,  (A.SIGUMGO_TRX_G || '-' || A.SIGUMGO_JI_TRX_G)
