       WITH WT_GYEJWA_INFO AS
       (
            SELECT T2.SIGUMGO_C AS GONGGEUM_GEUMGO_CD
                 , T2.SIGUMGO_HOIKYE_YR AS GONGGEUM_HOIGYE_YEAR
                 , T2.SIGUMGO_ACNO AS GONGGEUM_GYEJWA
                 , TO_NUMBER(T2.SIGUMGO_HOIKYE_C) AS GONGGEUM_HOIGYE_CODE
                 , T3.HOIKYE_NM AS HOIGYE_NAME
              FROM  RPT_AC_BY_HOIKYE_MAPP T2
              INNER JOIN RPT_HOIKYE_CD T3
                      ON T2.SIGUMGO_C = T3.SIGUMGO_C
                     AND T2.SIGUMGO_HOIKYE_C = T3.SIGUMGO_HOIKYE_C
                     AND T3.SIGUMGO_HOIKYE_C != 98
                     AND T3.USE_YN = 'Y' 
              WHERE T2.SIGUMGO_C = '150'
       )  
        SELECT 
          B.GONGGEUM_HOIGYE_CODE HOIGYE_CODE,
          B.HOIGYE_NAME,
          B.GONGGEUM_GYEJWA,
          '' AS GYEJWA_NAME,
          A.UNYONG_GYEJWA,
          D.SANGPUM_NAME,
          D.MKDT,
          A.DUDT,
          A.IYUL,
          A.JANAEK,
          TRIM(A.KIJUNIL) KIJUNIL,  
          A.JI_IJA,
          SUBSTR(A.UNYONG_GYEJWA,1,3) AS KWA   
        FROM RPT_UNYONG_JAN A, WT_GYEJWA_INFO B, RPT_HOIGYE_IWOL C, RPT_UNYONG_GYEJWA D
        WHERE A.GONGGEUM_GYEJWA = B.GONGGEUM_GYEJWA
        AND A.GONGGEUM_GYEJWA = D.GONGGEUM_GYEJWA
        AND A.UNYONG_GYEJWA = D.UNYONG_GYEJWA
        AND A.KIJUNIL BETWEEN '20240101' AND '20240630'
        AND A.GEUMGO_CODE = '150'
        AND A.GEUMGO_CODE = B.GONGGEUM_GEUMGO_CD
        AND A.GEUMGO_CODE = D.GEUMGO_CODE
        AND B.GONGGEUM_HOIGYE_CODE = C.HOIGYE_CODE(+)
        AND B.GONGGEUM_HOIGYE_YEAR = C.HOIGYE_YEAR(+)
        AND B.GONGGEUM_GEUMGO_CD = C.GEUMGO_CODE(+)
        AND C.GUBUN_CODE(+) = 1             
        AND ('ALL' = NVL('','ALL') OR B.GONGGEUM_HOIGYE_CODE IN (''))
        AND A.JI_IJA > 0
        AND (
         'ALL' = NVL('2024','ALL')
          OR
          (
            CASE WHEN B.GONGGEUM_HOIGYE_YEAR = 9999 THEN SUBSTR(A.KIJUNIL,1,4)
                   WHEN B.GONGGEUM_HOIGYE_YEAR=SUBSTR(A.KIJUNIL,1,4) THEN B.GONGGEUM_HOIGYE_YEAR
                   WHEN SUBSTR(A.KIJUNIL,1,8) >= C.KIJUNIL THEN TO_CHAR(B.GONGGEUM_HOIGYE_YEAR + 1) 
                   WHEN SUBSTR(A.KIJUNIL,1,8) <  C.KIJUNIL THEN B.GONGGEUM_HOIGYE_YEAR   
                   ELSE B.GONGGEUM_HOIGYE_YEAR END         
          ) = '2024')
        AND ('ALL' = NVL('','ALL') OR B.GONGGEUM_GYEJWA = '')
        AND ('ALL' = NVL('','ALL') OR B.GONGGEUM_HOIGYE_CODE IN (''))