SELECT
    NVL(A.LAF_CD, '0') AS LAF_CD,
    NVL(A.LAF_NM, '0') AS LAF_NM,
    NVL(A.GOF_CD, '0') AS GOF_CD,
    NVL(A.GOF_NM, '0') AS GOF_NM,
    NVL(A.FYR, '0') AS FYR,
    NVL(A.ACNT_DV_CD, '0') AS ACNT_DV_CD,
    NVL(A.ACNT_DV_MSTR_CD, '0') AS ACNT_DV_MSTR_CD,
    NVL(A.ACNT_DV_MSTR_NM, '0') AS ACNT_DV_MSTR_NM,
    NVL(A.ACNT_DV_NM, '0') AS ACNT_DV_NM,
    
    NVL(A.NU_TXRV_DD_SUM_AMT, 0)  세입누계,
    NVL(A.NU_ANE_AMT, 0)  세출누계,
    NVL(A.NU_FD_OP_AMT, 0)  자금운용누계,
    NVL(A.NU_TXRV_DD_SUM_AMT, 0) - NVL(A.NU_ANE_AMT, 0) - NVL(A.NU_FD_OP_AMT, 0)  공금잔액,
    NVL(A.GONGGEUM_JANAEK, '0') AS 수납회계이월액,
    NVL(A.UNYOUNG_JANAEK, '0') AS 운용회계이월액,
    
    NVL(A.ACNT_YMD, '0') AS ACNT_YMD,
    NVL(A.RCVMT_AMT, '0') AS RCVMT_AMT,
    NVL(A.RFN_AMT, '0') AS RFN_AMT,
    NVL(A.TXRV_SBJ_RVSN_AMT, '0') AS TXRV_SBJ_RVSN_AMT,
    NVL(A.TXRV_DD_SUM_AMT, '0') AS TXRV_DD_SUM_AMT,
    NVL(A.FDAC_AMT, '0') AS FDAC_AMT,
    NVL(A.FDAC_RTN_AMT, '0') AS FDAC_RTN_AMT,
    NVL(A.FDAC_RAMT_AMT, '0') AS FDAC_RAMT_AMT,
    NVL(A.EP_AMT, '0') AS EP_AMT,
    NVL(A.RTN_AMT, '0') AS RTN_AMT,
    NVL(A.ANE_SBJ_RVSN_AMT, '0') AS ANE_SBJ_RVSN_AMT,
    NVL(A.ANE_AMT, '0') AS ANE_AMT,
    NVL(A.PMOD_NPYM_AMT, '0') AS PMOD_NPYM_AMT,
    NVL(A.FD_BDTR_AMT, '0') AS FD_BDTR_AMT,
    NVL(A.FD_OP_DPI_AMT, '0') AS FD_OP_DPI_AMT,
    NVL(A.FD_OP_CNLT_AMT, '0') AS FD_OP_CNLT_AMT,
    NVL(A.FD_OP_AMT, '0') AS FD_OP_AMT,
    NVL(A.STBX_RAMT_AMT, '0') AS STBX_RAMT_AMT,
    NVL(A.UNDL_TRSFR_AMT, '0') AS UNDL_TRSFR_AMT,
    NVL(A.NU_ANE_AMT, 0)  AS NU_ANE_AMT,
    NVL(A.NU_FD_OP_AMT, 0) AS NU_FD_OP_AMT,
    NVL(A.NU_RCVMT_AMT, 0) AS NU_RCVMT_AMT,
    NVL(A.NU_RFN_AMT, '0') AS NU_RFN_AMT,
    NVL(A.NU_TXRV_SBJ_RVSN_AMT, '0') AS NU_TXRV_SBJ_RVSN_AMT,
    NVL(A.NU_TXRV_DD_SUM_AMT, 0) AS NU_TXRV_DD_SUM_AMT,
    NVL(A.NU_FDAC_AMT, '0') AS NU_FDAC_AMT,
    NVL(A.NU_FDAC_RTN_AMT, '0') AS NU_FDAC_RTN_AMT,
    NVL(A.NU_FDAC_RAMT_AMT, '0') AS NU_FDAC_RAMT_AMT,
    NVL(A.NU_EP_AMT, '0') AS NU_EP_AMT,
    NVL(A.NU_RTN_AMT, '0') AS NU_RTN_AMT,
    NVL(A.NU_ANE_SBJ_RVSN_AMT, '0') AS NU_ANE_SBJ_RVSN_AMT,
    NVL(A.NU_PMOD_NPYM_AMT, '0') AS NU_PMOD_NPYM_AMT,
    NVL(A.NU_FD_BDTR_AMT, '0') AS NU_FD_BDTR_AMT,
    NVL(A.NU_FD_OP_DPI_AMT, '0') AS NU_FD_OP_DPI_AMT,
    NVL(A.NU_FD_OP_CNLT_AMT, '0') AS NU_FD_OP_CNLT_AMT,

    NVL(A.NU_STBX_RAMT_AMT, '0') AS NU_STBX_RAMT_AMT,
    NVL(A.NU_UNDL_TRSFR_AMT, '0') AS NU_UNDL_TRSFR_AMT,

    NVL(A.STBX_BANK_CD, '0') AS STBX_BANK_CD
FROM
    (
    WITH UNYONG_JAN AS (
    SELECT 
        A.GONGGEUM_GYEJWA,
        SUM(A.JANAEK) AS JANAEK
    FROM 
    (
    SELECT
        CASE
            WHEN B.SIGUMGO_HOIKYE_YR <> 9999 THEN SUBSTR(A.GONGGEUM_GYEJWA, 0, 15) || SUBSTR((SELECT BIZ_DT FROM MAP_JOB_DATE WHERE DW_BAS_DDT = '20240805'), 3, 2)
            ELSE A.GONGGEUM_GYEJWA END AS GONGGEUM_GYEJWA,
        SUM(A.JANAEK) AS JANAEK
    FROM RPT_UNYONG_JAN A
             JOIN ACL_SIGUMGO_MAS B ON B.FIL_100_CTNT2 = A.GONGGEUM_GYEJWA
    WHERE 1=1
      AND B.MNG_NO = 1
      AND A.KIJUNIL = (SELECT CASE WHEN DT_G = 0 THEN BIZ_DT ELSE BF1_BIZ_DT END AS BIZ_DT  FROM MAP_JOB_DATE WHERE DW_BAS_DDT = SUBSTR('20240805',0,4) -1 || 1231)
      AND A.JANAEK > 0
      AND A.GEUMGO_CODE = '42'
     
    GROUP BY A.GONGGEUM_GYEJWA, B.SIGUMGO_HOIKYE_YR
    ) A
    GROUP BY A.GONGGEUM_GYEJWA
    ORDER BY A.GONGGEUM_GYEJWA
),
MI_JAN AS (
    SELECT E.CMM_DTL_C,  C.LAF_NM, C.ACNT_DV_CD, C.ACNT_DV_MSTR_CD, C.ACNT_DV_MSTR_NM, C.ACNT_DV_NM, C.GONGGEUM_GYEJWA,
        SUM(DECODE(A.CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1) * DECODE(A.IPJI_G, 2, -1, 1) * A.TRAMT) AS JANAEK
    FROM ACL_SIGUMGO_SLV A, ACL_SIGUMGO_MAS B, RPT_FISG_INFO_MAP C, SFI_CMM_C_DAT E
    WHERE 1=1
      AND A.SIGUMGO_ORG_C = B.SIGUMGO_ORG_C
      AND A.FIL_100_CTNT5 = B.FIL_100_CTNT2
      AND C.GONGGEUM_GYEJWA = B.FIL_100_CTNT2
      AND C.USE_YN = 'Y'
      AND B.MNG_NO = 1
      AND E.CMM_C_NM = 'RPT자치단체코드분류'
      AND E.USE_YN = 'Y'
      AND E.HRNK_CMM_DTL_C = A.SIGUMGO_ORG_C
      AND E.UPMU_HMK_1_SLV = A.ICH_SIGUMGO_GUN_GU_C
      AND E.CMM_DTL_C = C.LAF_CD(+)
      AND LPAD(A.SIGUMGO_TRX_G,2,'0')||LPAD(A.SIGUMGO_IP_TRX_G,2,'0')||LPAD(A.SIGUMGO_JI_TRX_G,2,'0') NOT IN (SELECT CMM_DTL_C FROM SFI_CMM_C_DAT WHERE CMM_C_NM = '이호조세입세출송신용' AND USE_YN = 'Y')
      AND NOT (A.SIGUMGO_ORG_C = '42' AND A.ICH_SIGUMGO_GUN_GU_C IN('260','710','720'))
      AND NVL(A.GISDT, A.TRXDT) BETWEEN '20240101' AND '20240805'
      AND A.SIGUMGO_ORG_C = '42'
      AND C.FYR = SUBSTR('20240805',0,4)
    GROUP BY E.CMM_DTL_C,  C.LAF_NM, C.ACNT_DV_CD, C.ACNT_DV_MSTR_CD, C.ACNT_DV_MSTR_NM, C.ACNT_DV_NM, C.GONGGEUM_GYEJWA
)
        SELECT
            E.CMM_DTL_C AS LAF_CD,
            C.LAF_NM AS LAF_NM,
            'AAAA' AS GOF_CD,
            'AAAA' AS GOF_NM,
            SUBSTR('20240805',0,4) AS FYR,
            C.ACNT_DV_CD AS ACNT_DV_CD ,
            C.ACNT_DV_MSTR_CD AS ACNT_DV_MSTR_CD ,
            C.ACNT_DV_MSTR_NM AS ACNT_DV_MSTR_NM ,
            C.ACNT_DV_NM AS ACNT_DV_NM ,
            
            G.JANAEK AS GONGGEUM_JANAEK,
            H.JANAEK AS UNYOUNG_JANAEK,
            '20240805' AS ACNT_YMD
             , SUM(CASE WHEN F.HRNK_CMM_C_NM = '세입'   AND  GISDT = '20240805'     THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS TXRV_DD_SUM_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '수납'  AND  GISDT = '20240805'         THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS RCVMT_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '과오납환급'  AND  GISDT = '20240805'         THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS RFN_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '과목경정'   AND  GISDT = '20240805'        THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS TXRV_SBJ_RVSN_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '자금배정'  AND  GISDT = '20240805'         THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS FDAC_AMT
             , 0 AS FDAC_RTN_AMT
             , 0 AS FDAC_RAMT_AMT
             , SUM(CASE WHEN F.HRNK_CMM_C_NM = '세출'     AND  GISDT = '20240805'      THEN -1 * A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS ANE_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '지출'      AND  GISDT = '20240805'     THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS EP_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '반납'      AND  GISDT = '20240805'     THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS RTN_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '세출과목경정'     AND  GISDT = '20240805'      THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS ANE_SBJ_RVSN_AMT
             ,0 AS PMOD_NPYM_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '자금전용'    AND  GISDT = '20240805'       THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS FD_BDTR_AMT
             , SUM(CASE WHEN F.HRNK_CMM_C_NM = '자금운용'     AND  GISDT = '20240805'      THEN -1 * A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS FD_OP_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '자금운용예치'     AND  GISDT = '20240805'      THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS FD_OP_DPI_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '자금운용해지'      AND  GISDT = '20240805'     THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS FD_OP_CNLT_AMT
             , SUM(CASE WHEN F.HRNK_CMM_C_NM = '지급명령미지급액'    AND  GISDT = '20240805'       THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS UNDL_TRSFR_AMT

             , SUM(CASE WHEN F.HRNK_CMM_C_NM = '세입' AND (NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101' OR B.SIGUMGO_HOIKYE_YR <> 9999) THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) + NVL(G.JANAEK,0) + NVL(H.JANAEK,0) AS NU_TXRV_DD_SUM_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '수납'     AND (NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101' OR B.SIGUMGO_HOIKYE_YR <> 9999)  THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) + NVL(G.JANAEK,0) + NVL(H.JANAEK,0) AS NU_RCVMT_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '과오납환급'   AND (NVL(A.GISDT, A.TRXDT) >= SUBSTR(20240805,0,4) || '0101' OR B.SIGUMGO_HOIKYE_YR <> 9999)  THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS NU_RFN_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '과목경정'  AND (NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101' OR B.SIGUMGO_HOIKYE_YR <> 9999)  THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS NU_TXRV_SBJ_RVSN_AMT
             , 0 AS NU_FDAC_RTN_AMT
             , 0 AS NU_FDAC_RAMT_AMT
             , SUM(CASE WHEN F.HRNK_CMM_C_NM = '세출' AND (NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101' OR B.SIGUMGO_HOIKYE_YR <> 9999)  THEN -1 * A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS NU_ANE_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '지출' AND (NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101' OR B.SIGUMGO_HOIKYE_YR <> 9999)  THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS NU_EP_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '반납'  AND (NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101' OR B.SIGUMGO_HOIKYE_YR <> 9999)  THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS NU_RTN_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '세출과목경정' AND (NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101' OR B.SIGUMGO_HOIKYE_YR <> 9999) THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS NU_ANE_SBJ_RVSN_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '자금배정'AND (NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101' OR B.SIGUMGO_HOIKYE_YR <> 9999) THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS NU_FDAC_AMT

             ,0 AS NU_PMOD_NPYM_AMT

             , SUM(CASE WHEN F.HRNK_CMM_C_NM = '자금운용'    AND NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101'  THEN -1 * A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END)  + NVL(H.JANAEK,0) AS NU_FD_OP_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '자금운용예치'   AND NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101'  THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) + NVL(H.JANAEK,0) AS NU_FD_OP_DPI_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '자금운용해지'   AND NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101'  THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END)  + NVL(H.JANAEK,0) AS NU_FD_OP_CNLT_AMT
             , SUM(CASE WHEN F.HRNK_CMM_DTL_C = '자금전용' AND NVL(A.GISDT, A.TRXDT) >= SUBSTR('20240805',0,4) || '0101' THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) + NVL(H.JANAEK,0) AS NU_FD_BDTR_AMT

             , SUM(CASE WHEN F.HRNK_CMM_C_NM = '지급명령미지급액'           THEN A.TRAMT * DECODE(IPJI_G, 2, -1, 1) * DECODE(A.CRT_CAN_G,1,-1,2,-1,33,-1,1) ELSE 0 END) AS NU_UNDL_TRSFR_AMT
             , 0 AS STBX_RAMT_AMT
             , 0 AS NU_STBX_RAMT_AMT
             , '10' AS DAY_MON_FG
             , '088' STBX_BANK_CD
        FROM ACL_SIGUMGO_SLV A, ACL_SIGUMGO_MAS B, RPT_FISG_INFO_MAP C, SFI_CMM_C_DAT E, SFI_CMM_C_DAT F, RPT_GONGGEUM_JAN G, UNYONG_JAN H
        WHERE 1=1
          AND A.SIGUMGO_ORG_C = B.SIGUMGO_ORG_C
          AND A.FIL_100_CTNT5 = B.FIL_100_CTNT2
          AND C.GONGGEUM_GYEJWA = B.FIL_100_CTNT2
          AND C.USE_YN = 'Y'
          AND B.MNG_NO = 1
          AND E.CMM_C_NM = 'RPT자치단체코드분류'
          AND E.USE_YN = 'Y'
          AND E.HRNK_CMM_DTL_C = A.SIGUMGO_ORG_C
          AND E.UPMU_HMK_1_SLV = A.ICH_SIGUMGO_GUN_GU_C
          AND E.CMM_DTL_C = C.LAF_CD(+)
          AND F.CMM_C_NM = '이호조세입세출송신용'
          AND F.USE_YN = 'Y'
          AND F.CMM_DTL_C = LPAD(A.SIGUMGO_TRX_G,2,'0')||LPAD(A.SIGUMGO_IP_TRX_G,2,'0')||LPAD(A.SIGUMGO_JI_TRX_G,2,'0')
          AND NOT (A.SIGUMGO_ORG_C = '42' AND A.ICH_SIGUMGO_GUN_GU_C IN('260','710','720'))
          AND NVL(A.GISDT, A.TRXDT) <= '20240805'
          AND A.SIGUMGO_ORG_C = '42'
          AND C.FYR = SUBSTR('20240805',0,4)
          AND C.GONGGEUM_GYEJWA = G.GONGGEUM_GYEJWA(+)
         
          AND G.KEORAEIL = SUBSTR('20240805',0,4) -1 || 1231
          AND C.GONGGEUM_GYEJWA = H.GONGGEUM_GYEJWA(+)
          AND G.GEUMGO_CODE = '42'
        GROUP BY E.CMM_DTL_C,  C.LAF_NM, C.ACNT_DV_CD, C.ACNT_DV_MSTR_CD, C.ACNT_DV_MSTR_NM, C.ACNT_DV_NM,  G.JANAEK, H.JANAEK
    ) A
     GROUP BY  A.LAF_CD, A.LAF_NM, A.GOF_CD, A.GOF_NM, A.FYR, A.ACNT_DV_CD, A.ACNT_DV_MSTR_CD, A.ACNT_DV_MSTR_NM, A.ACNT_DV_NM, A.ACNT_YMD, A.STBX_BANK_CD
ORDER BY LAF_CD DESC, ACNT_DV_MSTR_CD ASC, ACNT_DV_CD ASC


--------------------------------------------------------------

SELECT B.ACNT_DV_NM , A.FIL_100_CTNT5, A.LINKAC_JAN
FROM ACL_SIGUMGO_SLV A, RPT_FISG_INFO_MAP B
WHERE (A.FIL_100_CTNT5, A.TRXNO) IN (
    SELECT FIL_100_CTNT5, MAX(TRXNO)
    FROM ACL_SIGUMGO_SLV
    WHERE FIL_100_CTNT5 IN (
        SELECT GONGGEUM_GYEJWA
        FROM RPT_FISG_INFO_MAP
        WHERE FYR = 2024
        AND USE_YN = 'Y'
    )
    AND GISDT <= '20240805'
    GROUP BY FIL_100_CTNT5
)
AND A.SIGUMGO_ORG_C = '42'
AND A.FIL_100_CTNT5 = B.GONGGEUM_GYEJWA
AND B.FYR = 2024
AND B.USE_YN = 'Y'
ORDER BY B.ACNT_DV_NM, A.FIL_100_CTNT5

--------------------------------------------------------------
SELECT 
    A.ACNT_DV_NM,
    SUM(A.LINKAC_JAN) AS SUM_JAN
FROM 
(
SELECT B.ACNT_DV_NM , A.FIL_100_CTNT5, A.LINKAC_JAN
FROM ACL_SIGUMGO_SLV A, RPT_FISG_INFO_MAP B
WHERE (A.FIL_100_CTNT5, A.TRXNO) IN (
    SELECT FIL_100_CTNT5, MAX(TRXNO)
    FROM ACL_SIGUMGO_SLV
    WHERE FIL_100_CTNT5 IN (
        SELECT GONGGEUM_GYEJWA
        FROM RPT_FISG_INFO_MAP
        WHERE FYR = 2024
        AND USE_YN = 'Y'
    )
    AND GISDT <= '20240805'
    GROUP BY FIL_100_CTNT5
)
AND A.SIGUMGO_ORG_C = '42'
AND A.FIL_100_CTNT5 = B.GONGGEUM_GYEJWA
AND B.FYR = 2024
AND B.USE_YN = 'Y') A
GROUP BY A.ACNT_DV_NM
ORDER BY A.ACNT_DV_NM
