-- https://rpt.shinhan.com/scs.do?user_id=3540000201900000026&user_name=김윤선&org_id=3540000&dept_id=3540107&key_id=ea0183f905eecb51019e2d75f46d28efb57ef1a9f37e4ec02ddf0acc1b8b4abd

-- 강원 정기예금운용현황 - 계좌 상세 20240930
 SELECT
     T1.GONGGEUM_HOIGYE_CODE
    ,T1.GONGGEUM_GYEJWA_NM
     ,T1.UNYONG_GYEJWA
     ,(SELECT MKDT FROM RPT_UNYONG_GYEJWA WHERE GONGGEUM_GYEJWA LIKE '042%' AND UNYONG_GYEJWA = T1.UNYONG_GYEJWA AND OUT_DATE IS NULL) AS MKDT
     ,(SELECT DUDT FROM RPT_UNYONG_GYEJWA WHERE GONGGEUM_GYEJWA LIKE '042%' AND UNYONG_GYEJWA = T1.UNYONG_GYEJWA AND OUT_DATE IS NULL) AS DUDT
     ,(SELECT HJI_DT FROM RPT_UNYONG_GYEJWA WHERE GONGGEUM_GYEJWA LIKE '042%' AND UNYONG_GYEJWA = T1.UNYONG_GYEJWA AND OUT_DATE IS NULL) AS HJI_DT
    ,T1.GIGAN
    ,T2.PYUNGJAN
    ,T1.IJAAEK
    ,TO_CHAR(T2.SUIKYUL_FROM, '90.99') AS SUIKYUL_FROM
    ,TO_CHAR(T2.SUIKYUL_TO, '90.99') AS SUIKYUL_TO
    ,T1.MANGI_CNT
    ,T1.HYUNJAE_CNT
FROM
    (
     SELECT
          T1.UNYONG_GYEJWA
          ,T1.GONGGEUM_GYEJWA_NM
         ,T1.GONGGEUM_HOIGYE_CODE
         ,T1.GIGAN
         ,SUM(T1.IJAAEK) AS IJAAEK
         ,SUM(T1.MANGI_CNT) AS MANGI_CNT
         ,SUM(T1.HYUNJAE_CNT) AS HYUNJAE_CNT
     FROM
          (
           SELECT
                T1.UNYONG_GYEJWA
                ,T2.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
               ,T3.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
               ,CASE
                    WHEN SUBSTR(T1.DUDT,1,4) <> SUBSTR(T1.MKDT,1,4)
                    THEN
                           (TO_NUMBER(SUBSTR(T1.DUDT,1,4)) - TO_NUMBER(SUBSTR(T1.MKDT,1,4)))*12
                         - (TO_NUMBER(SUBSTR(T1.MKDT,5,2)) - TO_NUMBER(SUBSTR(T1.DUDT,5,2)))
                    WHEN SUBSTR(T1.DUDT,1,4) = SUBSTR(T1.MKDT,1,4)
                    THEN  (TO_NUMBER(SUBSTR(T1.DUDT,5,2)) - TO_NUMBER(SUBSTR(T1.MKDT,5,2)))
                 END AS GIGAN
                ,T1.JI_IJA AS IJAAEK
                ,1 AS MANGI_CNT
                ,0 AS HYUNJAE_CNT
           FROM
                RPT_UNYONG_GYEJWA T1
               ,ACL_SIGUMGO_MAS T2
               ,RPT_AC_BY_HOIKYE_MAPP T3
           WHERE 1=1
                AND T1.GONGGEUM_GYEJWA = T2.FIL_100_CTNT2
                AND T2.FIL_100_CTNT2 = T3.SIGUMGO_ACNO
                AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
                AND T1.GEUMGO_CODE = 42
                AND T1.HJI_DT >= '20240101'
                AND T1.HJI_DT <= '20240930'
                AND T1.GEUMAEK_AMT > 0
                AND T2.MNG_NO = 1
           UNION ALL
           SELECT
                T1.UNYONG_GYEJWA
                ,T2.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
               ,T3.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
               ,CASE
                    WHEN SUBSTR(T1.DUDT,1,4) <> SUBSTR(T1.MKDT,1,4)
                    THEN
                           (TO_NUMBER(SUBSTR(T1.DUDT,1,4)) - TO_NUMBER(SUBSTR(T1.MKDT,1,4)))*12
                         - (TO_NUMBER(SUBSTR(T1.MKDT,5,2)) - TO_NUMBER(SUBSTR(T1.DUDT,5,2)))
                    WHEN SUBSTR(T1.DUDT,1,4) = SUBSTR(T1.MKDT,1,4)
                    THEN  (TO_NUMBER(SUBSTR(T1.DUDT,5,2)) - TO_NUMBER(SUBSTR(T1.MKDT,5,2)))
                 END AS GIGAN
                ,0 AS IJAAEK
                ,0 AS MANGI_CNT
                ,1 AS HYUNJAE_CNT
           FROM
                RPT_UNYONG_GYEJWA T1
               ,ACL_SIGUMGO_MAS T2
               ,RPT_AC_BY_HOIKYE_MAPP T3
           WHERE 1=1
                AND T1.GONGGEUM_GYEJWA = T2.FIL_100_CTNT2
                AND T2.FIL_100_CTNT2 = T3.SIGUMGO_ACNO
                AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
                AND T1.GEUMGO_CODE = 42
                AND T1.MKDT < '20240930'
                AND NVL(T1.HJI_DT,'99999999') > '20240930'
                AND T1.GEUMAEK_AMT > 0
                AND T2.MNG_NO = 1
          ) T1
     GROUP BY
            T1.UNYONG_GYEJWA
         , T1.GONGGEUM_GYEJWA_NM
         ,T1.GONGGEUM_HOIGYE_CODE
         ,T1.GIGAN
    ) T1
    ,(
    SELECT
        T1.UNYONG_GYEJWA
        ,T2.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T1.GIGAN
        ,COUNT(1) AS CNT
        ,TRUNC(SUM(T1.UNYONG) / MIN(T1.DAYS_CNT),0) PYUNGJAN
        ,MIN(T1.IYUL)  AS SUIKYUL_FROM
        ,MAX(T1.IYUL) AS SUIKYUL_TO
    FROM
    (
    SELECT
        T1.UNYONG_GYEJWA 
        , T1.GONGGEUM_GYEJWA
        ,T1.GIGAN
        ,T2.JANAEK AS UNYONG
        ,T1.DAYS_CNT
        ,T2.IYUL
    FROM
    (
    SELECT
         T1.GONGGEUM_HOIGYE_CODE
        ,T1.GONGGEUM_GYEJWA
        ,T1.GONGGEUM_GYEJWA_NM
        ,T2.GONGGEUM_GYEJWA AS UNYONG_GONGGEUM_GYEJWA
        ,T1.BIZ_DT
        ,T2.UNYONG_GYEJWA
        ,CASE
             WHEN SUBSTR(T2.DUDT,1,4) <> SUBSTR(T2.MKDT,1,4)
             THEN
                    (TO_NUMBER(SUBSTR(T2.DUDT,1,4)) - TO_NUMBER(SUBSTR(T2.MKDT,1,4)))*12
                  - (TO_NUMBER(SUBSTR(T2.MKDT,5,2)) - TO_NUMBER(SUBSTR(T2.DUDT,5,2)))
             WHEN SUBSTR(T2.DUDT,1,4) = SUBSTR(T2.MKDT,1,4)
             THEN  (TO_NUMBER(SUBSTR(T2.DUDT,5,2)) - TO_NUMBER(SUBSTR(T2.MKDT,5,2)))
          END AS GIGAN
         ,T1.DAYS_CNT
    FROM
    (
    SELECT
         T1.SIGUMGO_ORG_C
        ,T1.FIL_100_CTNT2 AS GONGGEUM_GYEJWA
        ,T1.SIGUMGO_HOIKYE_YR AS GONGGEUM_HOIGYE_YEAR
        ,T2.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
        ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T3.TRX_DT
        ,T3.BIZ_DT
        ,T3.DAYS_CNT
    FROM
         ACL_SIGUMGO_MAS T1
        ,RPT_AC_BY_HOIKYE_MAPP T2
        ,(
          SELECT
               T1.DW_BAS_DDT AS TRX_DT
              ,DECODE(T1.DT_G, 0, T1.BIZ_DT, T1.BF1_BIZ_DT) AS BIZ_DT
              ,COUNT(1) OVER() AS DAYS_CNT
          FROM
               MAP_JOB_DATE T1
          WHERE 1=1
               AND T1.DW_BAS_DDT >= '20240101'
               AND T1.DW_BAS_DDT <= '20240930'
         ) T3
    WHERE 1=1
         AND T1.FIL_100_CTNT2 = T2.SIGUMGO_ACNO
         AND T1.SIGUMGO_HOIKYE_YR = T2.SIGUMGO_HOIKYE_YR
         AND T1.SIGUMGO_ORG_C = 42
         AND T1.ICH_SIGUMGO_GUN_GU_C = 0
         AND T1.SIGUMGO_HOIKYE_YR = '9999'
         AND T1.FIL_100_CTNT2 <> '04200080900003999'
         AND T1.MNG_NO = 1
    ) T1
    ,RPT_UNYONG_GYEJWA T2
    WHERE 1=1
         AND T1.GONGGEUM_GYEJWA = T2.GONGGEUM_GYEJWA
         AND SUBSTR(T1.TRX_DT, 1, 4) = '2024'
         AND SUBSTR(NVL(T2.MKDT,T2.IN_DATE),1,8) <= T1.TRX_DT
         AND NVL(T2.OUT_DATE, '99991231') > T1.TRX_DT
         AND NVL(T2.HJI_DT, '99991231') > T1.TRX_DT
         AND T2.BANK_GUBUN = 0
         AND T2.DUDT IS NOT NULL
    UNION ALL
    SELECT
         T1.GONGGEUM_HOIGYE_CODE
        ,T1.GONGGEUM_GYEJWA
        ,T1.GONGGEUM_GYEJWA_NM
        ,T2.GONGGEUM_GYEJWA AS UNYONG_GONGGEUM_GYEJWA
        ,T1.BIZ_DT
        ,T2.UNYONG_GYEJWA
        ,CASE
             WHEN SUBSTR(T2.DUDT,1,4) <> SUBSTR(T2.MKDT,1,4)
             THEN
                    (TO_NUMBER(SUBSTR(T2.DUDT,1,4)) - TO_NUMBER(SUBSTR(T2.MKDT,1,4)))*12
                  - (TO_NUMBER(SUBSTR(T2.MKDT,5,2)) - TO_NUMBER(SUBSTR(T2.DUDT,5,2)))
             WHEN SUBSTR(T2.DUDT,1,4) = SUBSTR(T2.MKDT,1,4)
             THEN  (TO_NUMBER(SUBSTR(T2.DUDT,5,2)) - TO_NUMBER(SUBSTR(T2.MKDT,5,2)))
          END AS GIGAN
         ,T1.DAYS_CNT
    FROM
    (
    SELECT
         T1.SIGUMGO_ORG_C
        ,T1.FIL_100_CTNT2 AS GONGGEUM_GYEJWA
        ,T1.SIGUMGO_HOIKYE_YR AS GONGGEUM_HOIGYE_YEAR
        ,T2.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
        ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T3.TRX_DT
        ,T3.BIZ_DT
        ,T3.DAYS_CNT
    FROM
         ACL_SIGUMGO_MAS T1
        ,RPT_AC_BY_HOIKYE_MAPP T2
        ,(
          SELECT
               T1.DW_BAS_DDT AS TRX_DT
              ,DECODE(T1.DT_G, 0, T1.BIZ_DT, T1.BF1_BIZ_DT) AS BIZ_DT
              ,COUNT(1) OVER() AS DAYS_CNT
          FROM
               MAP_JOB_DATE T1
          WHERE 1=1
               AND T1.DW_BAS_DDT >= '20240101'
               AND T1.DW_BAS_DDT <= '20240930'
         ) T3
    WHERE 1=1
         AND T1.FIL_100_CTNT2 = T2.SIGUMGO_ACNO
         AND T1.SIGUMGO_HOIKYE_YR = T2.SIGUMGO_HOIKYE_YR
         AND T1.SIGUMGO_ORG_C = 42
         AND T1.ICH_SIGUMGO_GUN_GU_C = 0
         AND T1.SIGUMGO_HOIKYE_YR = '2024'
         AND T1.FIL_100_CTNT2 <> '04200080900003999'
         AND T1.MNG_NO = 1
    ) T1
    ,RPT_UNYONG_GYEJWA T2
    WHERE 1=1
         AND T1.GONGGEUM_GYEJWA >= T2.GONGGEUM_GYEJWA
         AND T2.GONGGEUM_GYEJWA LIKE SUBSTR(T1.GONGGEUM_GYEJWA, 1, 15)||'%'
         AND SUBSTR(NVL(T2.MKDT,T2.IN_DATE),1,8) <= T1.TRX_DT
         AND NVL(T2.OUT_DATE, '99991231') > T1.TRX_DT
         AND NVL(T2.HJI_DT, '99991231') > T1.TRX_DT
         AND T2.BANK_GUBUN = 0
         AND T2.DUDT IS NOT NULL
    ) T1
    ,RPT_UNYONG_JAN T2
    WHERE 1=1
         AND T1.UNYONG_GONGGEUM_GYEJWA = T2.GONGGEUM_GYEJWA
         AND T1.UNYONG_GYEJWA = T2.UNYONG_GYEJWA
         AND T1.BIZ_DT = T2.KIJUNIL
    ) T1
    ,ACL_SIGUMGO_MAS T2
    WHERE 1=1
          AND T1.GONGGEUM_GYEJWA(+) = T2.FIL_100_CTNT2
          AND T2.SIGUMGO_ORG_C = 42
          AND T2.FIL_100_CTNT2 <> '04200080900003999'
          AND T2.MNG_NO = 1
    GROUP BY
            T1.UNYONG_GYEJWA
         ,T2.SIGUMGO_AC_NM
        ,T1.GIGAN
    ) T2
WHERE 1=1
     AND T1.GONGGEUM_GYEJWA_NM = T2.GONGGEUM_GYEJWA_NM
     AND T1.UNYONG_GYEJWA = T2.UNYONG_GYEJWA
     AND T1.GIGAN = T2.GIGAN
ORDER BY
     T1.GONGGEUM_HOIGYE_CODE
     ,T1.GIGAN
     ,T1.UNYONG_GYEJWA
     
----------------------------------------------------------------------------------------

SELECT
 T2.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T1.UNYONG_GYEJWA
        ,(SELECT MKDT FROM RPT_UNYONG_GYEJWA WHERE GONGGEUM_GYEJWA LIKE '042%' AND UNYONG_GYEJWA = T1.UNYONG_GYEJWA AND OUT_DATE IS NULL) AS MKDT
     ,(SELECT DUDT FROM RPT_UNYONG_GYEJWA WHERE GONGGEUM_GYEJWA LIKE '042%' AND UNYONG_GYEJWA = T1.UNYONG_GYEJWA AND OUT_DATE IS NULL) AS DUDT
     ,(SELECT HJI_DT FROM RPT_UNYONG_GYEJWA WHERE GONGGEUM_GYEJWA LIKE '042%' AND UNYONG_GYEJWA = T1.UNYONG_GYEJWA AND OUT_DATE IS NULL) AS HJI_DT
        ,T1.GIGAN
        ,COUNT(1) AS CNT
        ,TRUNC(SUM(T1.UNYONG) / MIN(T1.DAYS_CNT),0) PYUNGJAN
        ,MIN(T1.IYUL)  AS SUIKYUL_FROM
        ,MAX(T1.IYUL) AS SUIKYUL_TO
    FROM
    (
    SELECT
        T1.UNYONG_GYEJWA 
        , T1.GONGGEUM_GYEJWA
        ,T1.GIGAN
        ,T2.JANAEK AS UNYONG
        ,T1.DAYS_CNT
        ,T2.IYUL
    FROM
    (
    SELECT
         T1.GONGGEUM_HOIGYE_CODE
        ,T1.GONGGEUM_GYEJWA
        ,T1.GONGGEUM_GYEJWA_NM
        ,T2.GONGGEUM_GYEJWA AS UNYONG_GONGGEUM_GYEJWA
        ,T1.BIZ_DT
        ,T2.UNYONG_GYEJWA
        ,CASE
             WHEN SUBSTR(T2.DUDT,1,4) <> SUBSTR(T2.MKDT,1,4)
             THEN
                    (TO_NUMBER(SUBSTR(T2.DUDT,1,4)) - TO_NUMBER(SUBSTR(T2.MKDT,1,4)))*12
                  - (TO_NUMBER(SUBSTR(T2.MKDT,5,2)) - TO_NUMBER(SUBSTR(T2.DUDT,5,2)))
             WHEN SUBSTR(T2.DUDT,1,4) = SUBSTR(T2.MKDT,1,4)
             THEN  (TO_NUMBER(SUBSTR(T2.DUDT,5,2)) - TO_NUMBER(SUBSTR(T2.MKDT,5,2)))
          END AS GIGAN
         ,T1.DAYS_CNT
    FROM
    (
    SELECT
         T1.SIGUMGO_ORG_C
        ,T1.FIL_100_CTNT2 AS GONGGEUM_GYEJWA
        ,T1.SIGUMGO_HOIKYE_YR AS GONGGEUM_HOIGYE_YEAR
        ,T2.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
        ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T3.TRX_DT
        ,T3.BIZ_DT
        ,T3.DAYS_CNT
    FROM
         ACL_SIGUMGO_MAS T1
        ,RPT_AC_BY_HOIKYE_MAPP T2
        ,(
          SELECT
               T1.DW_BAS_DDT AS TRX_DT
              ,DECODE(T1.DT_G, 0, T1.BIZ_DT, T1.BF1_BIZ_DT) AS BIZ_DT
              ,COUNT(1) OVER() AS DAYS_CNT
          FROM
               MAP_JOB_DATE T1
          WHERE 1=1
               AND T1.DW_BAS_DDT >= '20240101'
               AND T1.DW_BAS_DDT <= '20240930'
         ) T3
    WHERE 1=1
         AND T1.FIL_100_CTNT2 = T2.SIGUMGO_ACNO
         AND T1.SIGUMGO_HOIKYE_YR = T2.SIGUMGO_HOIKYE_YR
         AND T1.SIGUMGO_ORG_C = 42
         AND T1.ICH_SIGUMGO_GUN_GU_C = 0
         AND T1.SIGUMGO_HOIKYE_YR = '9999'
         AND T1.FIL_100_CTNT2 <> '04200080900003999'
         AND T1.MNG_NO = 1
    ) T1
    ,RPT_UNYONG_GYEJWA T2
    WHERE 1=1
         AND T1.GONGGEUM_GYEJWA = T2.GONGGEUM_GYEJWA
         AND SUBSTR(T1.TRX_DT, 1, 4) = '2024'
         AND SUBSTR(NVL(T2.MKDT,T2.IN_DATE),1,8) <= T1.TRX_DT
         AND NVL(T2.OUT_DATE, '99991231') > T1.TRX_DT
         AND NVL(T2.HJI_DT, '99991231') > T1.TRX_DT
         AND T2.BANK_GUBUN = 0
         AND T2.DUDT IS NOT NULL
    UNION ALL
    SELECT
         T1.GONGGEUM_HOIGYE_CODE
        ,T1.GONGGEUM_GYEJWA
        ,T1.GONGGEUM_GYEJWA_NM
        ,T2.GONGGEUM_GYEJWA AS UNYONG_GONGGEUM_GYEJWA
        ,T1.BIZ_DT
        ,T2.UNYONG_GYEJWA
        ,CASE
             WHEN SUBSTR(T2.DUDT,1,4) <> SUBSTR(T2.MKDT,1,4)
             THEN
                    (TO_NUMBER(SUBSTR(T2.DUDT,1,4)) - TO_NUMBER(SUBSTR(T2.MKDT,1,4)))*12
                  - (TO_NUMBER(SUBSTR(T2.MKDT,5,2)) - TO_NUMBER(SUBSTR(T2.DUDT,5,2)))
             WHEN SUBSTR(T2.DUDT,1,4) = SUBSTR(T2.MKDT,1,4)
             THEN  (TO_NUMBER(SUBSTR(T2.DUDT,5,2)) - TO_NUMBER(SUBSTR(T2.MKDT,5,2)))
          END AS GIGAN
         ,T1.DAYS_CNT
    FROM
    (
    SELECT
         T1.SIGUMGO_ORG_C
        ,T1.FIL_100_CTNT2 AS GONGGEUM_GYEJWA
        ,T1.SIGUMGO_HOIKYE_YR AS GONGGEUM_HOIGYE_YEAR
        ,T2.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
        ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T3.TRX_DT
        ,T3.BIZ_DT
        ,T3.DAYS_CNT
    FROM
         ACL_SIGUMGO_MAS T1
        ,RPT_AC_BY_HOIKYE_MAPP T2
        ,(
          SELECT
               T1.DW_BAS_DDT AS TRX_DT
              ,DECODE(T1.DT_G, 0, T1.BIZ_DT, T1.BF1_BIZ_DT) AS BIZ_DT
              ,COUNT(1) OVER() AS DAYS_CNT
          FROM
               MAP_JOB_DATE T1
          WHERE 1=1
               AND T1.DW_BAS_DDT >= '20240101'
               AND T1.DW_BAS_DDT <= '20240930'
         ) T3
    WHERE 1=1
         AND T1.FIL_100_CTNT2 = T2.SIGUMGO_ACNO
         AND T1.SIGUMGO_HOIKYE_YR = T2.SIGUMGO_HOIKYE_YR
         AND T1.SIGUMGO_ORG_C = 42
         AND T1.ICH_SIGUMGO_GUN_GU_C = 0
         AND T1.SIGUMGO_HOIKYE_YR = '2024'
         AND T1.FIL_100_CTNT2 <> '04200080900003999'
         AND T1.MNG_NO = 1
    ) T1
    ,RPT_UNYONG_GYEJWA T2
    WHERE 1=1
         AND T1.GONGGEUM_GYEJWA >= T2.GONGGEUM_GYEJWA
         AND T2.GONGGEUM_GYEJWA LIKE SUBSTR(T1.GONGGEUM_GYEJWA, 1, 15)||'%'
         AND SUBSTR(NVL(T2.MKDT,T2.IN_DATE),1,8) <= T1.TRX_DT
         AND NVL(T2.OUT_DATE, '99991231') > T1.TRX_DT
         AND NVL(T2.HJI_DT, '99991231') > T1.TRX_DT
         AND T2.BANK_GUBUN = 0
         AND T2.DUDT IS NOT NULL
    ) T1
    ,RPT_UNYONG_JAN T2
    WHERE 1=1
         AND T1.UNYONG_GONGGEUM_GYEJWA = T2.GONGGEUM_GYEJWA
         AND T1.UNYONG_GYEJWA = T2.UNYONG_GYEJWA
         AND T1.BIZ_DT = T2.KIJUNIL
    ) T1
    ,ACL_SIGUMGO_MAS T2
    WHERE 1=1
          AND T1.GONGGEUM_GYEJWA(+) = T2.FIL_100_CTNT2
          AND T2.SIGUMGO_ORG_C = 42
          AND T2.FIL_100_CTNT2 <> '04200080900003999'
          AND T2.MNG_NO = 1
    GROUP BY
            T1.UNYONG_GYEJWA
         ,T2.SIGUMGO_AC_NM
        ,T1.GIGAN
    ORDER BY T2.SIGUMGO_AC_NM, T1.UNYONG_GYEJWA    

-----------------------------------------------------------------------
-- 200117487615
SELECT * FROM RPT_UNYONG_GYEJWA
WHERE 1=1
AND UNYONG_GYEJWA IN 
(
SELECT
T1.UNYONG_GYEJWA
FROM
    (
     SELECT
          T1.UNYONG_GYEJWA
          ,T1.GONGGEUM_GYEJWA_NM
         ,T1.GONGGEUM_HOIGYE_CODE
         ,T1.GIGAN
         ,SUM(T1.IJAAEK) AS IJAAEK
         ,SUM(T1.MANGI_CNT) AS MANGI_CNT
         ,SUM(T1.HYUNJAE_CNT) AS HYUNJAE_CNT
     FROM
          (
           SELECT
                T1.UNYONG_GYEJWA
                ,T2.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
               ,T3.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
               ,CASE
                    WHEN SUBSTR(T1.DUDT,1,4) <> SUBSTR(T1.MKDT,1,4)
                    THEN
                           (TO_NUMBER(SUBSTR(T1.DUDT,1,4)) - TO_NUMBER(SUBSTR(T1.MKDT,1,4)))*12
                         - (TO_NUMBER(SUBSTR(T1.MKDT,5,2)) - TO_NUMBER(SUBSTR(T1.DUDT,5,2)))
                    WHEN SUBSTR(T1.DUDT,1,4) = SUBSTR(T1.MKDT,1,4)
                    THEN  (TO_NUMBER(SUBSTR(T1.DUDT,5,2)) - TO_NUMBER(SUBSTR(T1.MKDT,5,2)))
                 END AS GIGAN
                ,T1.JI_IJA AS IJAAEK
                ,1 AS MANGI_CNT
                ,0 AS HYUNJAE_CNT
           FROM
                RPT_UNYONG_GYEJWA T1
               ,ACL_SIGUMGO_MAS T2
               ,RPT_AC_BY_HOIKYE_MAPP T3
           WHERE 1=1
                AND T1.GONGGEUM_GYEJWA = T2.FIL_100_CTNT2
                AND T2.FIL_100_CTNT2 = T3.SIGUMGO_ACNO
                AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
                AND T1.GEUMGO_CODE = 42
                AND T1.HJI_DT >= '20240101'
                AND T1.HJI_DT <= '20240930'
                AND T1.GEUMAEK_AMT > 0
                AND T2.MNG_NO = 1
           UNION ALL
           SELECT
                T1.UNYONG_GYEJWA
                ,T2.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
               ,T3.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
               ,CASE
                    WHEN SUBSTR(T1.DUDT,1,4) <> SUBSTR(T1.MKDT,1,4)
                    THEN
                           (TO_NUMBER(SUBSTR(T1.DUDT,1,4)) - TO_NUMBER(SUBSTR(T1.MKDT,1,4)))*12
                         - (TO_NUMBER(SUBSTR(T1.MKDT,5,2)) - TO_NUMBER(SUBSTR(T1.DUDT,5,2)))
                    WHEN SUBSTR(T1.DUDT,1,4) = SUBSTR(T1.MKDT,1,4)
                    THEN  (TO_NUMBER(SUBSTR(T1.DUDT,5,2)) - TO_NUMBER(SUBSTR(T1.MKDT,5,2)))
                 END AS GIGAN
                ,0 AS IJAAEK
                ,0 AS MANGI_CNT
                ,1 AS HYUNJAE_CNT
           FROM
                RPT_UNYONG_GYEJWA T1
               ,ACL_SIGUMGO_MAS T2
               ,RPT_AC_BY_HOIKYE_MAPP T3
           WHERE 1=1
                AND T1.GONGGEUM_GYEJWA = T2.FIL_100_CTNT2
                AND T2.FIL_100_CTNT2 = T3.SIGUMGO_ACNO
                AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
                AND T1.GEUMGO_CODE = 42
                AND T1.MKDT < '20240930'
                AND NVL(T1.HJI_DT,'99999999') > '20240930'
                AND T1.GEUMAEK_AMT > 0
                AND T2.MNG_NO = 1
          ) T1
     GROUP BY
            T1.UNYONG_GYEJWA
         , T1.GONGGEUM_GYEJWA_NM
         ,T1.GONGGEUM_HOIGYE_CODE
         ,T1.GIGAN
    ) T1
    ,(
    SELECT
         T2.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T1.GIGAN
        ,COUNT(1) AS CNT
        ,TRUNC(SUM(T1.UNYONG) / MIN(T1.DAYS_CNT),0) PYUNGJAN
        ,MIN(T1.IYUL)  AS SUIKYUL_FROM
        ,MAX(T1.IYUL) AS SUIKYUL_TO
    FROM
    (
    SELECT
         T1.GONGGEUM_GYEJWA
        ,T1.GIGAN
        ,T2.JANAEK AS UNYONG
        ,T1.DAYS_CNT
        ,T2.IYUL
    FROM
    (
    SELECT
         T1.GONGGEUM_HOIGYE_CODE
        ,T1.GONGGEUM_GYEJWA
        ,T1.GONGGEUM_GYEJWA_NM
        ,T2.GONGGEUM_GYEJWA AS UNYONG_GONGGEUM_GYEJWA
        ,T1.BIZ_DT
        ,T2.UNYONG_GYEJWA
        ,CASE
             WHEN SUBSTR(T2.DUDT,1,4) <> SUBSTR(T2.MKDT,1,4)
             THEN
                    (TO_NUMBER(SUBSTR(T2.DUDT,1,4)) - TO_NUMBER(SUBSTR(T2.MKDT,1,4)))*12
                  - (TO_NUMBER(SUBSTR(T2.MKDT,5,2)) - TO_NUMBER(SUBSTR(T2.DUDT,5,2)))
             WHEN SUBSTR(T2.DUDT,1,4) = SUBSTR(T2.MKDT,1,4)
             THEN  (TO_NUMBER(SUBSTR(T2.DUDT,5,2)) - TO_NUMBER(SUBSTR(T2.MKDT,5,2)))
          END AS GIGAN
         ,T1.DAYS_CNT
    FROM
    (
    SELECT
         T1.SIGUMGO_ORG_C
        ,T1.FIL_100_CTNT2 AS GONGGEUM_GYEJWA
        ,T1.SIGUMGO_HOIKYE_YR AS GONGGEUM_HOIGYE_YEAR
        ,T2.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
        ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T3.TRX_DT
        ,T3.BIZ_DT
        ,T3.DAYS_CNT
    FROM
         ACL_SIGUMGO_MAS T1
        ,RPT_AC_BY_HOIKYE_MAPP T2
        ,(
          SELECT
               T1.DW_BAS_DDT AS TRX_DT
              ,DECODE(T1.DT_G, 0, T1.BIZ_DT, T1.BF1_BIZ_DT) AS BIZ_DT
              ,COUNT(1) OVER() AS DAYS_CNT
          FROM
               MAP_JOB_DATE T1
          WHERE 1=1
               AND T1.DW_BAS_DDT >= '20240101'
               AND T1.DW_BAS_DDT <= '20240930'
         ) T3
    WHERE 1=1
         AND T1.FIL_100_CTNT2 = T2.SIGUMGO_ACNO
         AND T1.SIGUMGO_HOIKYE_YR = T2.SIGUMGO_HOIKYE_YR
         AND T1.SIGUMGO_ORG_C = 42
         AND T1.ICH_SIGUMGO_GUN_GU_C = 0
         AND T1.SIGUMGO_HOIKYE_YR = '9999'
         AND T1.FIL_100_CTNT2 <> '04200080900003999'
         AND T1.MNG_NO = 1
    ) T1
    ,RPT_UNYONG_GYEJWA T2
    WHERE 1=1
         AND T1.GONGGEUM_GYEJWA = T2.GONGGEUM_GYEJWA
         AND SUBSTR(T1.TRX_DT, 1, 4) = '2024'
         AND SUBSTR(NVL(T2.MKDT,T2.IN_DATE),1,8) <= T1.TRX_DT
         AND NVL(T2.OUT_DATE, '99991231') > T1.TRX_DT
         AND NVL(T2.HJI_DT, '99991231') > T1.TRX_DT
         AND T2.BANK_GUBUN = 0
         AND T2.DUDT IS NOT NULL
    UNION ALL
    SELECT
         T1.GONGGEUM_HOIGYE_CODE
        ,T1.GONGGEUM_GYEJWA
        ,T1.GONGGEUM_GYEJWA_NM
        ,T2.GONGGEUM_GYEJWA AS UNYONG_GONGGEUM_GYEJWA
        ,T1.BIZ_DT
        ,T2.UNYONG_GYEJWA
        ,CASE
             WHEN SUBSTR(T2.DUDT,1,4) <> SUBSTR(T2.MKDT,1,4)
             THEN
                    (TO_NUMBER(SUBSTR(T2.DUDT,1,4)) - TO_NUMBER(SUBSTR(T2.MKDT,1,4)))*12
                  - (TO_NUMBER(SUBSTR(T2.MKDT,5,2)) - TO_NUMBER(SUBSTR(T2.DUDT,5,2)))
             WHEN SUBSTR(T2.DUDT,1,4) = SUBSTR(T2.MKDT,1,4)
             THEN  (TO_NUMBER(SUBSTR(T2.DUDT,5,2)) - TO_NUMBER(SUBSTR(T2.MKDT,5,2)))
          END AS GIGAN
         ,T1.DAYS_CNT
    FROM
    (
    SELECT
         T1.SIGUMGO_ORG_C
        ,T1.FIL_100_CTNT2 AS GONGGEUM_GYEJWA
        ,T1.SIGUMGO_HOIKYE_YR AS GONGGEUM_HOIGYE_YEAR
        ,T2.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
        ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T3.TRX_DT
        ,T3.BIZ_DT
        ,T3.DAYS_CNT
    FROM
         ACL_SIGUMGO_MAS T1
        ,RPT_AC_BY_HOIKYE_MAPP T2
        ,(
          SELECT
               T1.DW_BAS_DDT AS TRX_DT
              ,DECODE(T1.DT_G, 0, T1.BIZ_DT, T1.BF1_BIZ_DT) AS BIZ_DT
              ,COUNT(1) OVER() AS DAYS_CNT
          FROM
               MAP_JOB_DATE T1
          WHERE 1=1
               AND T1.DW_BAS_DDT >= '20240101'
               AND T1.DW_BAS_DDT <= '20240930'
         ) T3
    WHERE 1=1
         AND T1.FIL_100_CTNT2 = T2.SIGUMGO_ACNO
         AND T1.SIGUMGO_HOIKYE_YR = T2.SIGUMGO_HOIKYE_YR
         AND T1.SIGUMGO_ORG_C = 42
         AND T1.ICH_SIGUMGO_GUN_GU_C = 0
         AND T1.SIGUMGO_HOIKYE_YR = '2024'
         AND T1.FIL_100_CTNT2 <> '04200080900003999'
         AND T1.MNG_NO = 1
    ) T1
    ,RPT_UNYONG_GYEJWA T2
    WHERE 1=1
         AND T1.GONGGEUM_GYEJWA >= T2.GONGGEUM_GYEJWA
         AND T2.GONGGEUM_GYEJWA LIKE SUBSTR(T1.GONGGEUM_GYEJWA, 1, 15)||'%'
         AND SUBSTR(NVL(T2.MKDT,T2.IN_DATE),1,8) <= T1.TRX_DT
         AND NVL(T2.OUT_DATE, '99991231') > T1.TRX_DT
         AND NVL(T2.HJI_DT, '99991231') > T1.TRX_DT
         AND T2.BANK_GUBUN = 0
         AND T2.DUDT IS NOT NULL
    ) T1
    ,RPT_UNYONG_JAN T2
    WHERE 1=1
         AND T1.UNYONG_GONGGEUM_GYEJWA = T2.GONGGEUM_GYEJWA
         AND T1.UNYONG_GYEJWA = T2.UNYONG_GYEJWA
         AND T1.BIZ_DT = T2.KIJUNIL
    ) T1
    ,ACL_SIGUMGO_MAS T2
    WHERE 1=1
          AND T1.GONGGEUM_GYEJWA(+) = T2.FIL_100_CTNT2
          AND T2.SIGUMGO_ORG_C = 42
          AND T2.FIL_100_CTNT2 <> '04200080900003999'
          AND T2.MNG_NO = 1
    GROUP BY
         T2.SIGUMGO_AC_NM
        ,T1.GIGAN
    ) T2
WHERE 1=1
     AND T1.GONGGEUM_GYEJWA_NM = T2.GONGGEUM_GYEJWA_NM
     AND T1.GIGAN = T2.GIGAN
)  
ORDER BY GONGGEUM_GYEJWA, UNYONG_GYEJWA   
-----------------------------------------------------------------------

SELECT UNYONG_GYEJWA, COUNT(*) AS CNT FROM RPT_UNYONG_GYEJWA
WHERE 1=1
AND UNYONG_GYEJWA IN 
(
SELECT
T1.UNYONG_GYEJWA
FROM
    (
     SELECT
          T1.UNYONG_GYEJWA
          ,T1.GONGGEUM_GYEJWA_NM
         ,T1.GONGGEUM_HOIGYE_CODE
         ,T1.GIGAN
         ,SUM(T1.IJAAEK) AS IJAAEK
         ,SUM(T1.MANGI_CNT) AS MANGI_CNT
         ,SUM(T1.HYUNJAE_CNT) AS HYUNJAE_CNT
     FROM
          (
           SELECT
                T1.UNYONG_GYEJWA
                ,T2.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
               ,T3.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
               ,CASE
                    WHEN SUBSTR(T1.DUDT,1,4) <> SUBSTR(T1.MKDT,1,4)
                    THEN
                           (TO_NUMBER(SUBSTR(T1.DUDT,1,4)) - TO_NUMBER(SUBSTR(T1.MKDT,1,4)))*12
                         - (TO_NUMBER(SUBSTR(T1.MKDT,5,2)) - TO_NUMBER(SUBSTR(T1.DUDT,5,2)))
                    WHEN SUBSTR(T1.DUDT,1,4) = SUBSTR(T1.MKDT,1,4)
                    THEN  (TO_NUMBER(SUBSTR(T1.DUDT,5,2)) - TO_NUMBER(SUBSTR(T1.MKDT,5,2)))
                 END AS GIGAN
                ,T1.JI_IJA AS IJAAEK
                ,1 AS MANGI_CNT
                ,0 AS HYUNJAE_CNT
           FROM
                RPT_UNYONG_GYEJWA T1
               ,ACL_SIGUMGO_MAS T2
               ,RPT_AC_BY_HOIKYE_MAPP T3
           WHERE 1=1
                AND T1.GONGGEUM_GYEJWA = T2.FIL_100_CTNT2
                AND T2.FIL_100_CTNT2 = T3.SIGUMGO_ACNO
                AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
                AND T1.GEUMGO_CODE = 42
                AND T1.HJI_DT >= '20240101'
                AND T1.HJI_DT <= '20240930'
                AND T1.GEUMAEK_AMT > 0
                AND T2.MNG_NO = 1
           UNION ALL
           SELECT
                T1.UNYONG_GYEJWA
                ,T2.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
               ,T3.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
               ,CASE
                    WHEN SUBSTR(T1.DUDT,1,4) <> SUBSTR(T1.MKDT,1,4)
                    THEN
                           (TO_NUMBER(SUBSTR(T1.DUDT,1,4)) - TO_NUMBER(SUBSTR(T1.MKDT,1,4)))*12
                         - (TO_NUMBER(SUBSTR(T1.MKDT,5,2)) - TO_NUMBER(SUBSTR(T1.DUDT,5,2)))
                    WHEN SUBSTR(T1.DUDT,1,4) = SUBSTR(T1.MKDT,1,4)
                    THEN  (TO_NUMBER(SUBSTR(T1.DUDT,5,2)) - TO_NUMBER(SUBSTR(T1.MKDT,5,2)))
                 END AS GIGAN
                ,0 AS IJAAEK
                ,0 AS MANGI_CNT
                ,1 AS HYUNJAE_CNT
           FROM
                RPT_UNYONG_GYEJWA T1
               ,ACL_SIGUMGO_MAS T2
               ,RPT_AC_BY_HOIKYE_MAPP T3
           WHERE 1=1
                AND T1.GONGGEUM_GYEJWA = T2.FIL_100_CTNT2
                AND T2.FIL_100_CTNT2 = T3.SIGUMGO_ACNO
                AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
                AND T1.GEUMGO_CODE = 42
                AND T1.MKDT < '20240930'
                AND NVL(T1.HJI_DT,'99999999') > '20240930'
                AND T1.GEUMAEK_AMT > 0
                AND T2.MNG_NO = 1
          ) T1
     GROUP BY
            T1.UNYONG_GYEJWA
         , T1.GONGGEUM_GYEJWA_NM
         ,T1.GONGGEUM_HOIGYE_CODE
         ,T1.GIGAN
    ) T1
    ,(
    SELECT
         T2.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T1.GIGAN
        ,COUNT(1) AS CNT
        ,TRUNC(SUM(T1.UNYONG) / MIN(T1.DAYS_CNT),0) PYUNGJAN
        ,MIN(T1.IYUL)  AS SUIKYUL_FROM
        ,MAX(T1.IYUL) AS SUIKYUL_TO
    FROM
    (
    SELECT
         T1.GONGGEUM_GYEJWA
        ,T1.GIGAN
        ,T2.JANAEK AS UNYONG
        ,T1.DAYS_CNT
        ,T2.IYUL
    FROM
    (
    SELECT
         T1.GONGGEUM_HOIGYE_CODE
        ,T1.GONGGEUM_GYEJWA
        ,T1.GONGGEUM_GYEJWA_NM
        ,T2.GONGGEUM_GYEJWA AS UNYONG_GONGGEUM_GYEJWA
        ,T1.BIZ_DT
        ,T2.UNYONG_GYEJWA
        ,CASE
             WHEN SUBSTR(T2.DUDT,1,4) <> SUBSTR(T2.MKDT,1,4)
             THEN
                    (TO_NUMBER(SUBSTR(T2.DUDT,1,4)) - TO_NUMBER(SUBSTR(T2.MKDT,1,4)))*12
                  - (TO_NUMBER(SUBSTR(T2.MKDT,5,2)) - TO_NUMBER(SUBSTR(T2.DUDT,5,2)))
             WHEN SUBSTR(T2.DUDT,1,4) = SUBSTR(T2.MKDT,1,4)
             THEN  (TO_NUMBER(SUBSTR(T2.DUDT,5,2)) - TO_NUMBER(SUBSTR(T2.MKDT,5,2)))
          END AS GIGAN
         ,T1.DAYS_CNT
    FROM
    (
    SELECT
         T1.SIGUMGO_ORG_C
        ,T1.FIL_100_CTNT2 AS GONGGEUM_GYEJWA
        ,T1.SIGUMGO_HOIKYE_YR AS GONGGEUM_HOIGYE_YEAR
        ,T2.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
        ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T3.TRX_DT
        ,T3.BIZ_DT
        ,T3.DAYS_CNT
    FROM
         ACL_SIGUMGO_MAS T1
        ,RPT_AC_BY_HOIKYE_MAPP T2
        ,(
          SELECT
               T1.DW_BAS_DDT AS TRX_DT
              ,DECODE(T1.DT_G, 0, T1.BIZ_DT, T1.BF1_BIZ_DT) AS BIZ_DT
              ,COUNT(1) OVER() AS DAYS_CNT
          FROM
               MAP_JOB_DATE T1
          WHERE 1=1
               AND T1.DW_BAS_DDT >= '20240101'
               AND T1.DW_BAS_DDT <= '20240930'
         ) T3
    WHERE 1=1
         AND T1.FIL_100_CTNT2 = T2.SIGUMGO_ACNO
         AND T1.SIGUMGO_HOIKYE_YR = T2.SIGUMGO_HOIKYE_YR
         AND T1.SIGUMGO_ORG_C = 42
         AND T1.ICH_SIGUMGO_GUN_GU_C = 0
         AND T1.SIGUMGO_HOIKYE_YR = '9999'
         AND T1.FIL_100_CTNT2 <> '04200080900003999'
         AND T1.MNG_NO = 1
    ) T1
    ,RPT_UNYONG_GYEJWA T2
    WHERE 1=1
         AND T1.GONGGEUM_GYEJWA = T2.GONGGEUM_GYEJWA
         AND SUBSTR(T1.TRX_DT, 1, 4) = '2024'
         AND SUBSTR(NVL(T2.MKDT,T2.IN_DATE),1,8) <= T1.TRX_DT
         AND NVL(T2.OUT_DATE, '99991231') > T1.TRX_DT
         AND NVL(T2.HJI_DT, '99991231') > T1.TRX_DT
         AND T2.BANK_GUBUN = 0
         AND T2.DUDT IS NOT NULL
    UNION ALL
    SELECT
         T1.GONGGEUM_HOIGYE_CODE
        ,T1.GONGGEUM_GYEJWA
        ,T1.GONGGEUM_GYEJWA_NM
        ,T2.GONGGEUM_GYEJWA AS UNYONG_GONGGEUM_GYEJWA
        ,T1.BIZ_DT
        ,T2.UNYONG_GYEJWA
        ,CASE
             WHEN SUBSTR(T2.DUDT,1,4) <> SUBSTR(T2.MKDT,1,4)
             THEN
                    (TO_NUMBER(SUBSTR(T2.DUDT,1,4)) - TO_NUMBER(SUBSTR(T2.MKDT,1,4)))*12
                  - (TO_NUMBER(SUBSTR(T2.MKDT,5,2)) - TO_NUMBER(SUBSTR(T2.DUDT,5,2)))
             WHEN SUBSTR(T2.DUDT,1,4) = SUBSTR(T2.MKDT,1,4)
             THEN  (TO_NUMBER(SUBSTR(T2.DUDT,5,2)) - TO_NUMBER(SUBSTR(T2.MKDT,5,2)))
          END AS GIGAN
         ,T1.DAYS_CNT
    FROM
    (
    SELECT
         T1.SIGUMGO_ORG_C
        ,T1.FIL_100_CTNT2 AS GONGGEUM_GYEJWA
        ,T1.SIGUMGO_HOIKYE_YR AS GONGGEUM_HOIGYE_YEAR
        ,T2.SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
        ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
        ,T3.TRX_DT
        ,T3.BIZ_DT
        ,T3.DAYS_CNT
    FROM
         ACL_SIGUMGO_MAS T1
        ,RPT_AC_BY_HOIKYE_MAPP T2
        ,(
          SELECT
               T1.DW_BAS_DDT AS TRX_DT
              ,DECODE(T1.DT_G, 0, T1.BIZ_DT, T1.BF1_BIZ_DT) AS BIZ_DT
              ,COUNT(1) OVER() AS DAYS_CNT
          FROM
               MAP_JOB_DATE T1
          WHERE 1=1
               AND T1.DW_BAS_DDT >= '20240101'
               AND T1.DW_BAS_DDT <= '20240930'
         ) T3
    WHERE 1=1
         AND T1.FIL_100_CTNT2 = T2.SIGUMGO_ACNO
         AND T1.SIGUMGO_HOIKYE_YR = T2.SIGUMGO_HOIKYE_YR
         AND T1.SIGUMGO_ORG_C = 42
         AND T1.ICH_SIGUMGO_GUN_GU_C = 0
         AND T1.SIGUMGO_HOIKYE_YR = '2024'
         AND T1.FIL_100_CTNT2 <> '04200080900003999'
         AND T1.MNG_NO = 1
    ) T1
    ,RPT_UNYONG_GYEJWA T2
    WHERE 1=1
         AND T1.GONGGEUM_GYEJWA >= T2.GONGGEUM_GYEJWA
         AND T2.GONGGEUM_GYEJWA LIKE SUBSTR(T1.GONGGEUM_GYEJWA, 1, 15)||'%'
         AND SUBSTR(NVL(T2.MKDT,T2.IN_DATE),1,8) <= T1.TRX_DT
         AND NVL(T2.OUT_DATE, '99991231') > T1.TRX_DT
         AND NVL(T2.HJI_DT, '99991231') > T1.TRX_DT
         AND T2.BANK_GUBUN = 0
         AND T2.DUDT IS NOT NULL
    ) T1
    ,RPT_UNYONG_JAN T2
    WHERE 1=1
         AND T1.UNYONG_GONGGEUM_GYEJWA = T2.GONGGEUM_GYEJWA
         AND T1.UNYONG_GYEJWA = T2.UNYONG_GYEJWA
         AND T1.BIZ_DT = T2.KIJUNIL
    ) T1
    ,ACL_SIGUMGO_MAS T2
    WHERE 1=1
          AND T1.GONGGEUM_GYEJWA(+) = T2.FIL_100_CTNT2
          AND T2.SIGUMGO_ORG_C = 42
          AND T2.FIL_100_CTNT2 <> '04200080900003999'
          AND T2.MNG_NO = 1
    GROUP BY
         T2.SIGUMGO_AC_NM
        ,T1.GIGAN
    ) T2
WHERE 1=1
     AND T1.GONGGEUM_GYEJWA_NM = T2.GONGGEUM_GYEJWA_NM
     AND T1.GIGAN = T2.GIGAN
)  
GROUP BY UNYONG_GYEJWA
ORDER BY UNYONG_GYEJWA