WITH BIZDT AS (
    SELECT
        DW_BAS_DDT AS TDT,
        NEXT_BIZ_DT AS NDT
    FROM MAP_JOB_DATE
    WHERE DW_BAS_DDT = (SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') FROM DUAL)
),
     MERGED_BIZDT AS (
         SELECT TDT AS DT FROM BIZDT
         UNION ALL
         SELECT NDT AS DT FROM BIZDT
     )
SELECT GJDT AS DT, '1.서구청' AS GUBUN, SUM(SUNP_AMT) AS AMT
FROM ACL_SUNAPMSG_SLV
WHERE GJDT IN (SELECT DT FROM MERGED_BIZDT)
  AND UPMU_G IN (1, 2, 4)
  AND RPT_TOT_C != '104901'
GROUP BY GJDT
UNION ALL
SELECT SIGUMGO_ICHE_KJ_DT AS DT, '2.7331' AS GUBUN, SUM(SIGUMGO_IP_AMT) AS AMT
FROM ACL_INCHICHE_CC
WHERE SIGUMGO_ICHE_KJ_DT IN (SELECT DT FROM MERGED_BIZDT)
  AND SIGUMGO_IP_REF_NO = '55291000670205'
  AND IPJI_G = 1
GROUP BY SIGUMGO_ICHE_KJ_DT
ORDER BY DT, GUBUN, AMT

;

SELECT
    SIGUMGO_TRX_G,
    SIGUMGO_IP_TRX_G,
    SIGUMGO_JI_TRX_G,
    SUM(DECODE(IPJI_G, 2, -1, 1) * DECODE(CRT_CAN_G,1,-1,2,-1,33,-1,1) * TRAMT) AS AMT
FROM ACL_SIGUMGO_SLV
WHERE SIGUMGO_ORG_C = 150
AND FIL_100_CTNT5 = '15000080900000124'
GROUP BY SIGUMGO_TRX_G, SIGUMGO_IP_TRX_G, SIGUMGO_JI_TRX_G
ORDER BY SIGUMGO_TRX_G, SIGUMGO_IP_TRX_G, SIGUMGO_JI_TRX_G