select * from rpt_txi_ddac_tab
where 1=1
and sigumgo_org_c = 440
and upd_dttm like '20240906%'

select count(*) as cnt from acl_sigumgo_slv
where trxdt < gisdt


select * from rpt_dangseipjojeong
where 1=1
and jibgye_code = 750009


SELECT REF_D_C GUNGU_CODE, REF_D_NM GUNGU_NM, NVL(AA.DATA_ROW,1) AS DATA_ROW,
                SUM(NVL(AMT1 , 0)) AMT1 , SUM(NVL(AMT2 , 0)) AMT2 , SUM(NVL(AMT3 , 0)) AMT3 ,
                SUM(NVL(AMT4 , 0)) AMT4 , SUM(NVL(AMT5 , 0)) AMT5 , SUM(NVL(AMT6 , 0)) AMT6 ,
                SUM(NVL(AMT7 , 0)) AMT7 , SUM(NVL(AMT8 , 0)) AMT8 , SUM(NVL(AMT9 , 0)) AMT9 ,
                SUM(NVL(AMT10, 0)) AMT10, SUM(NVL(AMT11, 0)) AMT11, SUM(NVL(AMT12, 0)) AMT12,
                SUM(NVL(AMT13, 0)) AMT13, SUM(NVL(AMT14, 0)) AMT14, SUM(NVL(AMT15, 0)) AMT15,
                SUM(NVL(AMT16, 0)) AMT16, SUM(NVL(AMT17, 0)) AMT17, SUM(NVL(AMT18, 0)) AMT18,
                SUM(NVL(AMT19, 0)) AMT19, SUM(NVL(AMT20, 0)) AMT20, SUM(NVL(AMT21, 0)) AMT21,
                SUM(NVL(AMT22, 0)) AMT22, SUM(NVL(AMT23, 0)) AMT23, SUM(NVL(AMT24, 0)) AMT24,
                SUM(NVL(AMT25, 0)) AMT25, SUM(NVL(AMT26, 0)) AMT26, SUM(NVL(AMT27, 0)) AMT27,
                SUM(NVL(AMT28, 0)) AMT28
FROM  
(
      SELECT  GUNGU_CODE, 1 DATA_ROW,
                       0 AMT1,
                       SUM(CASE WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN  = 1 AND SUNAPIL = '20231229' THEN NVL(JIBANGSE_AMT,0) * -1
                                            WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN  = 2 AND SUNAPIL = '20231229' THEN NVL(JIBANGSE_AMT,0)  ELSE 0 END) AMT2,
                       SUM(CASE WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 1 AND SUNAPIL = '20231229' THEN NVL(JIBANGSE_AMT,0)
                                            WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 2 AND SUNAPIL = '20231229' THEN NVL(JIBANGSE_AMT,0) * -1  ELSE 0 END) AMT3,
                       0 AMT4,
                       SUM(CASE WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN  = 1 AND SUNAPIL = '20231229' THEN NVL(SEWOI_AMT,0) * -1
                                            WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN  = 2 AND SUNAPIL = '20231229' THEN NVL(SEWOI_AMT,0)  ELSE 0 END) AMT5,
                       SUM(CASE WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 1 AND SUNAPIL = '20231229' THEN NVL(SEWOI_AMT,0)
                                            WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 2 AND SUNAPIL = '20231229' THEN NVL(SEWOI_AMT,0) * -1 ELSE 0 END) AMT6,
                       0 AMT7,
                       SUM(CASE WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN  = 1 AND SUNAPIL = '20231229' THEN NVL(GYOYUKSE_AMT,0) * -1
                                            WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN  = 2 AND SUNAPIL = '20231229' THEN NVL(GYOYUKSE_AMT,0) ELSE 0 END) AMT8,
                       SUM(CASE WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 1 AND SUNAPIL = '20231229' THEN NVL(GYOYUKSE_AMT,0)
                                            WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 2 AND SUNAPIL = '20231229' THEN NVL(GYOYUKSE_AMT,0) * -1 ELSE 0 END) AMT9,
                       0 AMT10,
                       SUM(CASE WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN  = 1 AND SUNAPIL = '20231229' THEN NVL(NONGTEUKSE_AMT,0) * -1
                                            WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN  = 2 AND SUNAPIL = '20231229' THEN NVL(NONGTEUKSE_AMT,0) ELSE 0 END) AMT11,
                       SUM(CASE WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 1 AND SUNAPIL = '20231229' THEN NVL(NONGTEUKSE_AMT,0)
                                            WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 2 AND SUNAPIL = '20231229' THEN NVL(NONGTEUKSE_AMT,0) * -1 ELSE 0 END) AMT12,
                       0 AMT13,
                       SUM(CASE WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN = 1 THEN NVL(JIBANGSE_AMT,0) * -1
                                            WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN = 2 THEN NVL(JIBANGSE_AMT,0) ELSE 0 END) AMT14,
                       SUM(CASE WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 1 THEN NVL(JIBANGSE_AMT,0)
                                            WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 2 THEN NVL(JIBANGSE_AMT,0) * -1 ELSE 0 END) AMT15,
                       0 AMT16,
                       SUM(CASE WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN = 1 THEN NVL(SEWOI_AMT,0) * -1
                                            WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN = 2 THEN NVL(SEWOI_AMT,0) ELSE 0 END) AMT17,
                       SUM(CASE WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 1 THEN NVL(SEWOI_AMT,0)
                                            WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 2 THEN NVL(SEWOI_AMT,0) * -1 ELSE 0 END) AMT18,
                       0 AMT19,
                       SUM(CASE WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN = 1 THEN NVL(GYOYUKSE_AMT,0) * -1
                                            WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN = 2 THEN NVL(GYOYUKSE_AMT,0) ELSE 0 END) AMT20,
                       SUM(CASE WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 1 THEN NVL(GYOYUKSE_AMT,0)
                                            WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 2 THEN NVL(GYOYUKSE_AMT,0) * -1 ELSE 0 END) AMT21,
                       0 AMT22,
                       SUM(CASE WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN = 1 THEN NVL(NONGTEUKSE_AMT,0) * -1
                                            WHEN JOJEONG_GUBUN = 2 AND IPJI_GUBUN = 2 THEN NVL(NONGTEUKSE_AMT,0) ELSE 0 END) AMT23,
                       SUM(CASE WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 1 THEN NVL(NONGTEUKSE_AMT,0)
                                            WHEN JOJEONG_GUBUN <> 2 AND IPJI_GUBUN = 2 THEN NVL(NONGTEUKSE_AMT,0) * -1 ELSE 0 END) AMT24,
                       SUM(CASE WHEN (SUNAPIL BETWEEN '20231229' AND '20231229') AND IPJI_GUBUN = 1 THEN NVL(JIBANGSE_AMT,0)
                                            WHEN (SUNAPIL BETWEEN SUBSTR('20231229',0,6)||'01' AND '20231229') AND IPJI_GUBUN <> 1 THEN NVL(JIBANGSE_AMT,0) * -1 ELSE 0 END) AMT25,
                       SUM(CASE WHEN (SUNAPIL BETWEEN SUBSTR('20231229',0,6)||'01' AND '20231229') AND IPJI_GUBUN =  1 THEN NVL(SEWOI_AMT,0)
                                            WHEN (SUNAPIL BETWEEN SUBSTR('20231229',0,6)||'01' AND '20231229') AND IPJI_GUBUN <> 1 THEN NVL(SEWOI_AMT,0) * -1 ELSE 0 END) AMT26,
                       SUM(CASE WHEN (SUNAPIL BETWEEN SUBSTR('20231229',0,6)||'01' AND '20231229') AND IPJI_GUBUN =  1 THEN NVL(GYOYUKSE_AMT,0)
                                            WHEN (SUNAPIL BETWEEN SUBSTR('20231229',0,6)||'01' AND '20231229') AND IPJI_GUBUN <> 1 THEN NVL(GYOYUKSE_AMT,0) * -1 ELSE 0 END) AMT27,
                       SUM(CASE WHEN (SUNAPIL BETWEEN SUBSTR('20231229',0,6)||'00' AND '20231229') AND IPJI_GUBUN =  1 THEN NVL(NONGTEUKSE_AMT,0)
                                            WHEN (SUNAPIL BETWEEN SUBSTR('20231229',0,6)||'00' AND '20231229') AND IPJI_GUBUN <> 1 THEN NVL(NONGTEUKSE_AMT,0) * -1 ELSE 0 END) AMT28
      FROM  RPT_DANGSEIPJOJEONG A
       WHERE  A.GEUMGO_CODE = '28' 
       AND A.SUNAPIL <= '20231229'
      AND A.GUNGU_CODE LIKE '0' || '%'
      AND A.JIBGYE_CODE = (SELECT REF_D_C FROM RPT_CODE_INFO WHERE REF_L_C = 879 AND REF_M_C = 28 AND REF_CTNT1 = '02800075690000123')
       GROUP BY A.GUNGU_CODE
 ) AA,
 (SELECT CASE WHEN '0' = '' THEN '9999' ELSE '0' END REF_D_C, (SELECT REF_D_NM FROM RPT_CODE_INFO WHERE REF_L_C = 500 AND REF_M_C = '28' AND REF_S_C = 1 AND REF_D_C = '0') REF_D_NM, 1 DATA_ROW FROM DUAL
   UNION ALL
   SELECT '9999' REF_D_C, '합계' REF_D_NM, 2 DATA_ROW FROM DUAL
 ) M
 WHERE
   AA.GUNGU_CODE(+) = M.REF_D_C
 GROUP BY  REF_D_C, REF_D_NM, AA.DATA_ROW