SELECT   BB.SIGUMGO_HOIKYE_C 
  ,BB.HOIKYE_NM NUGYE_HOIGYE_NAME
                ,TO_CHAR((SUM(NVL(SUNP_AMT,0)) + SUM(NVL(TAX_BAEJUNG_IP_AMT,0)) + SUM(NVL(IWOL_GONGGEUM,0)))) AS NUGYE_SEIB_SUIP
                ,TO_CHAR(SUM(NVL(SEIB_BANNAB,0))) AS NUGYE_SEIB_BANNAB 
                ,TO_CHAR(SUM(NVL(SEIB_GYEONGJEONG_IB,0))) AS NUGYE_SEIB_GYEONGJEONG_IB
                ,TO_CHAR(SUM(NVL(SEIB_GYEONGJEONG_JI,0))*-1) AS NUGYE_SEIB_GYEONGJEONG_JI
                ,TO_CHAR(SUM(NVL(SECHUL_BAEJEONG,0))) AS NUGYE_SECHUL_BAEJEONG
                ,TO_CHAR(SUM(NVL(SECHUL_HWANSU,0))*-1) AS NUGYE_SECHUL_HWANSU
                ,TO_CHAR(SUM(NVL(SECHUL_JI,0))) AS NUGYE_SECHUL_JI
                ,TO_CHAR(SUM(NVL(SECHUL_BANNAB,0))*-1) AS NUGYE_SECHUL_BANNAB
                ,TO_CHAR(SUM(NVL(SECHUL_GYEONGJEONG_IB,0))) AS NUGYE_SECHUL_GYEONGJEONG_IB
                ,TO_CHAR(SUM(NVL(SECHUL_GYEONGJEONG_JI,0))) AS NUGYE_SECHUL_GYEONGJEONG_JI 
                ,TO_CHAR(SUM(NVL(SEIB_GYULSANBF_IIB,0))) AS NUGYE_SEIB_GYULSANBF_IIB
                ,TO_CHAR(SUM(NVL(SECHUL_GYULSANBF_IWOL,0))) AS NUGYE_SECHUL_GYULSANBF_IWOL
                ,TO_CHAR(SUM(NVL(DEP,0)) + SUM(NVL(IWOL_GONGGEUM_DEP,0))) AS NUGYE_DEP
               ,TO_CHAR(SUM(NVL(MMDA,0)) + SUM(NVL(IWOL_MMDA,0))) AS NUGYE_MMDA
               ,TO_CHAR(SUM(NVL(SUNP_AMT,0)) - SUM(NVL(SEIB_SUIP,0)) + SUM(NVL(IWOL_MIJUNGSAN,0))) AS NUGYE_MIICHE
                ,TO_CHAR((SUM(NVL(SUNP_AMT2,0)) + SUM(NVL(TAX_BAEJUNG_IP_AMT2,0)) + SUM(NVL(IWOL_GONGGEUM2,0)))) AS ILGYE_SEIB_SUIP
                ,TO_CHAR(SUM(NVL(SEIB_BANNAB2,0))) AS ILGYE_SEIB_BANNAB
                ,TO_CHAR(SUM(NVL(SEIB_GYEONGJEONG_IB2,0))) AS ILGYE_SEIB_GYEONGJEONG_IB
                ,TO_CHAR(SUM(NVL(SEIB_GYEONGJEONG_JI2,0))*-1) AS ILGYE_SEIB_GYEONGJEONG_JI
                ,TO_CHAR(SUM(NVL(SECHUL_BAEJEONG2,0))) AS ILGYE_SECHUL_BAEJEONG
                ,TO_CHAR(SUM(NVL(SECHUL_HWANSU2,0))*-1) AS ILGYE_SECHUL_HWANSU
                ,TO_CHAR(SUM(NVL(SECHUL_JI2,0))) AS ILGYE_SECHUL_JI
                ,TO_CHAR(SUM(NVL(SECHUL_BANNAB2,0))*-1) AS ILGYE_SECHUL_BANNAB
                ,TO_CHAR(SUM(NVL(SECHUL_GYEONGJEONG_IB2,0))) AS ILGYE_SECHUL_GYEONGJEONG_IB  
                ,TO_CHAR(SUM(NVL(SECHUL_GYEONGJEONG_JI2,0))) AS ILGYE_SECHUL_GYEONGJEONG_JI  
                ,TO_CHAR(SUM(NVL(SEIB_GYULSANBF_IIB2,0))) AS ILGYE_SEIB_GYULSANBF_IIB
                ,TO_CHAR(SUM(NVL(SECHUL_GYULSANBF_IWOL2,0))) AS ILGYE_SECHUL_GYULSANBF_IWOL
                ,TO_CHAR(SUM(NVL(DEP2,0)) + SUM(NVL(IWOL_GONGGEUM_DEP2,0))) AS ILGYE_DEP
               ,TO_CHAR(SUM(NVL(MMDA2,0)) + SUM(NVL(IWOL_MMDA2,0))) AS ILGYE_MMDA
               ,TO_CHAR(SUM(NVL(SUNP_AMT2,0)) - SUM(NVL(SEIB_SUIP2,0)) + SUM(NVL(IWOL_MIJUNGSAN2,0))) AS ILGYE_MIICHE
FROM
(

 WITH AC_LIST AS (
  SELECT     
    T2.SIGUMGO_ORG_C
    ,T3.SIGUMGO_HOIKYE_C AS RPT_HOIKYE_C
    ,T2.GONGGEUM_GYEJWA
    ,T2.GONGGEUM_GYEJWA_NM
    ,T2.SIGUMGO_HOIKYE_YR
  FROM
    (
  SELECT
    T1.SIGUMGO_ORG_C
    ,T1.ICH_SIGUMGO_GUN_GU_C
    ,T1.ICH_SIGUMGO_HOIKYE_C
    ,T1.SIGUMGO_AC_B
    ,T1.SIGUMGO_AC_SER
    ,T1.SIGUMGO_HOIKYE_YR
    ,LPAD(T1.SIGUMGO_ORG_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_GUN_GU_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_HOIKYE_C, 2, 0)||RPAD(T1.SIGUMGO_AC_B, 2, 0)||LPAD(T1.SIGUMGO_AC_SER, 5, '0')||SUBSTR(T1.SIGUMGO_HOIKYE_YR, 3, 2) AS  GONGGEUM_GYEJWA    
    ,T1.LINKAC_KWA_C ||'000'|| T1.LINK_ACSER AS GONGGEUM_YUDONG_ACNO
    ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
  FROM
    ACL_SIGUMGO_MAS T1
  WHERE 1=1
    AND T1.SIGUMGO_ORG_C = '110'
    AND T1.SIGUMGO_HOIKYE_YR IN ('2025', '9999')
    AND T1.MNG_NO = 1
    ) T2
    ,RPT_AC_BY_HOIKYE_MAPP T3
  WHERE 1=1
    AND T2.GONGGEUM_GYEJWA = T3.SIGUMGO_ACNO
    AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
    AND T2.SIGUMGO_ORG_C = T3.SIGUMGO_C
 )
 SELECT
    HOIGYE_CODE,
    SIGUMGO_ORG_C,
           NVL(TAX_SUNP_IP_AMT,0) AS SEIB_SUIP,           
    NVL(TAX_BAEJUNG_IP_AMT,0) AS TAX_BAEJUNG_IP_AMT,    
    NVL(GWAON_PROC_JI_AMT,0) AS SEIB_BANNAB,                  
    NVL(TAX_IP_CRT_IP_AMT,0) AS SEIB_GYEONGJEONG_IB,       
    NVL(TAX_IP_CRT_JI_AMT,0) AS SEIB_GYEONGJEONG_JI,                  
    NVL(BIZPLC_BAEJUNG_JI_AMT,0)+NVL(GAM_BAEJUNG_JI_AMT,0) AS SECHUL_BAEJEONG,                 
    NVL(BIZPLC_GAM_BAEJUNG_IP_AMT,0) AS SECHUL_HWANSU,                
    NVL(TAXO_JI_AMT,0) AS SECHUL_JI,                       
    NVL(TAXO_RTRN_AMT,0) AS SECHUL_BANNAB,                    
    NVL(KWA_CRRC_IP_AMT,0) AS SECHUL_GYEONGJEONG_IB,                 
    NVL(KWA_CRRC_JI_AMT,0) AS SECHUL_GYEONGJEONG_JI,                 
    NVL(GA_IWOL_IP_AMT,0) AS SEIB_GYULSANBF_IIB,                   
    NVL(GA_IWOL_JI_AMT,0) AS SECHUL_GYULSANBF_IWOL,                  
    NVL(DEP_MK_JI_AMT,0) - NVL(DEP_HJI_AMT,0) AS DEP,                       
    NVL(MMDA,0) AS MMDA,                       
    NVL(SUNP_AMT,0) AS SUNP_AMT,           
    NVL(IWOL_GONGGEUM,0) AS IWOL_GONGGEUM,      
    NVL(IWOL_MIJUNGSAN,0) AS IWOL_MIJUNGSAN ,      
    NVL(IWOL_MMDA,0) AS IWOL_MMDA,         
     NVL(IWOL_GONGGEUM_DEP,0) AS IWOL_GONGGEUM_DEP,    
    0 AS SEIB_SUIP2,                
    0 AS TAX_BAEJUNG_IP_AMT2,           
    0 AS SEIB_BANNAB2,                        
    0 AS SEIB_GYEONGJEONG_IB2,             
    0 AS SEIB_GYEONGJEONG_JI2,                        
    0 AS SECHUL_BAEJEONG2,                        
    0 AS SECHUL_HWANSU2,                        
    0 AS SECHUL_JI2,                           
    0 AS SECHUL_BANNAB2,                         
    0 AS SECHUL_GYEONGJEONG_IB2,                       
    0 AS SECHUL_GYEONGJEONG_JI2,                       
    0 AS SEIB_GYULSANBF_IIB2,                        
    0 AS SECHUL_GYULSANBF_IWOL2,                       
    0 AS DEP2,                            
    0 AS MMDA2,                          
    0 AS SUNP_AMT2,              
    0 AS IWOL_GONGGEUM2,           
    0 AS IWOL_MIJUNGSAN2 ,            
    0 AS IWOL_MMDA2,             
     0 AS IWOL_GONGGEUM_DEP2          
 FROM
 (
  SELECT   
      RPT_HOIKYE_C AS HOIGYE_CODE
     ,A.SIGUMGO_ORG_C
     ,SUM(TAX_SUNP_IP_AMT) AS TAX_SUNP_IP_AMT
     ,SUM(SUIP_CHULNAP_BAEJUNG_AMT)
        +SUM(FUND_UNYONG_INT_AMT)
        +SUM(PMNY_DEP_INT_AMT)
        +SUM(BTDEP_INT_AMT)
        +SUM(JICULWO_BAEJUNG_IP_AMT) AS TAX_BAEJUNG_IP_AMT
     ,SUM(GWAON_PROC_JI_AMT) AS GWAON_PROC_JI_AMT
     ,SUM(TAX_IP_CRT_IP_AMT) AS TAX_IP_CRT_IP_AMT
     ,SUM(TAX_IP_CRT_JI_AMT) AS TAX_IP_CRT_JI_AMT
     ,SUM(BIZPLC_BAEJUNG_JI_AMT) AS BIZPLC_BAEJUNG_JI_AMT
     ,SUM(BIZPLC_GAM_BAEJUNG_IP_AMT) AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,SUM(TAXO_FUND_BAEJUNG_JI_AMT)
     +SUM(TAXO_HNDO_BAEJUNG_JI_AMT)
     +SUM(TAXO_FUND_GETBK_JI_AMT)
     +SUM(TAXO_HNDO_JICHUL_JI_AMT)
     +SUM(TAXO_HNDO_GETBK_JI_AMT)  AS TAXO_JI_AMT
    ,SUM(TAXO_RTRN_AMT) AS TAXO_RTRN_AMT
    ,SUM(KWA_CRRC_IP_AMT) AS KWA_CRRC_IP_AMT
    ,SUM(KWA_CRRC_JI_AMT) AS KWA_CRRC_JI_AMT
    ,SUM(GA_IWOL_IP_AMT) AS GA_IWOL_IP_AMT
    ,SUM(GA_IWOL_JI_AMT) AS GA_IWOL_JI_AMT
    ,SUM(DEP_MK_JI_AMT) AS DEP_MK_JI_AMT
    ,SUM(MR_FUND_AMT) AS MMDA
    ,SUM(DEP_HJI_AMT) AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
    ,SUM(GAM_BAEJUNG_JI_AMT) GAM_BAEJUNG_JI_AMT
  FROM RPT_TXIO_DDAC_TAB A, AC_LIST B
  WHERE  A.SGG_ACNO(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.BAS_DT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.BAS_DT(+) BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  -- 25.08.11 11-11, 11-12, 11-13 금액을 수입액에 잡아줌

  SELECT   
    RPT_HOIKYE_C AS HOIGYE_CODE
    , A.SIGUMGO_ORG_C
    , 0 AS TAX_SUNP_IP_AMT
    , 0 AS TAX_BAEJUNG_IP_AMT
    , 0 AS GWAON_PROC_JI_AMT
    , 0 AS TAX_IP_CRT_IP_AMT
    , 0 AS TAX_IP_CRT_JI_AMT
    , 0 AS BIZPLC_BAEJUNG_JI_AMT
    , 0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    , 0 AS TAXO_JI_AMT
    , 0 AS TAXO_RTRN_AMT
    , 0 AS KWA_CRRC_IP_AMT
    , 0 AS KWA_CRRC_JI_AMT
    , 0 AS GA_IWOL_IP_AMT
    , 0 AS GA_IWOL_JI_AMT
    , 0 AS DEP_MK_JI_AMT
    , 0 AS MMDA
    , 0 AS DEP_HJI_AMT
    , SUM(DECODE(CRT_CAN_G, 1 ,-1, 2, -1, 33, -1, 1) * DECODE(IPJI_G, 2, -1, 1) * TRAMT) AS SUNP_AMT
    , 0 AS IWOL_GONGGEUM
    , 0 AS IWOL_MIJUNGSAN
    , 0 AS IWOL_MMDA
    , 0 AS IWOL_GONGGEUM_DEP
    , 0 AS GAM_BAEJUNG_JI_AMT
  FROM ACL_SIGUMGO_SLV A, AC_LIST B
  WHERE  A.FIL_100_CTNT5(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.GJDT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.GJDT(+) BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  AND A.SIGUMGO_TRX_G = 11
  AND A.SIGUMGO_IP_TRX_G IN (11, 12, 13)
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  SELECT  TO_CHAR(ICH_SIGUMGO_HOIKYE_C) HOIGYE_CODE
    ,A.SIGUMGO_ORG_C
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,SUM(JIBANGSE_AMT)  AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
    ,0 GAM_BAEJUNG_JI_AMT
   FROM   RPT_TXI_DDAC_TAB A
   WHERE  A.SIGUMGO_HOIKYE_YR = ( '2025' ) 
     AND A.SIGUMGO_ORG_C = '110'
     AND A.SUNAP_DT BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
     AND A.ICH_SIGUMGO_GUN_GU_C = 0    
     GROUP BY ICH_SIGUMGO_HOIKYE_C, A.SIGUMGO_ORG_C
  UNION ALL
  SELECT  TO_CHAR(HOIGYE_CODE) HOIGYE_CODE
    ,GEUMGO_CODE
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,SUM(CASE WHEN GUBUN_CODE = 1 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM
    ,SUM(CASE WHEN GUBUN_CODE = 5 THEN AMT1 ELSE 0 END) AS IWOL_MIJUNGSAN
    ,SUM(CASE WHEN GUBUN_CODE = 4 THEN AMT1 ELSE 0 END) AS IWOL_MMDA
    ,SUM(CASE WHEN GUBUN_CODE = 2 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM_DEP
    ,0 GAM_BAEJUNG_JI_AMT
   FROM   RPT_HOIGYE_IWOL A
   WHERE  A.HOIGYE_YEAR = ( '2025' - 1 )
     AND A.GEUMGO_CODE = '110'
     AND A.GUBUN_CODE IN (1, 2, 4, 5)
     AND A.KIJUNIL BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
     AND A.GUNGU_CODE = 0
     GROUP BY HOIGYE_CODE, GEUMGO_CODE
 ) 
 UNION ALL
 SELECT   
    HOIGYE_CODE,
    SIGUMGO_ORG_C,
           0 AS SEIB_SUIP,                
    0 AS TAX_BAEJUNG_IP_AMT,           
    0 AS SEIB_BANNAB,                        
    0 AS SEIB_GYEONGJEONG_IB,             
    0 AS SEIB_GYEONGJEONG_JI,                        
    0 AS SECHUL_BAEJEONG,                        
    0 AS SECHUL_HWANSU,                        
    0 AS SECHUL_JI,                           
    0 AS SECHUL_BANNAB,                         
    0 AS SECHUL_GYEONGJEONG_IB,                       
    0 AS SECHUL_GYEONGJEONG_JI,                       
    0 AS SEIB_GYULSANBF_IIB,                         
    0 AS SECHUL_GYULSANBF_IWOL,                       
    0 AS DEP,                            
    0 AS MMDA,                          
    0 AS SUNP_AMT,               
    0 AS IWOL_GONGGEUM,            
    0 AS IWOL_MIJUNGSAN ,            
    0 AS IWOL_MMDA,             
     0 AS IWOL_GONGGEUM_DEP,           
           NVL(TAX_SUNP_IP_AMT,0) AS SEIB_SUIP2,          
    NVL(TAX_BAEJUNG_IP_AMT,0) AS TAX_BAEJUNG_IP_AMT2,    
    NVL(GWAON_PROC_JI_AMT,0) AS SEIB_BANNAB2,                 
    NVL(TAX_IP_CRT_IP_AMT,0) AS SEIB_GYEONGJEONG_IB2,       
    NVL(TAX_IP_CRT_JI_AMT,0) AS SEIB_GYEONGJEONG_JI2,                  
    NVL(BIZPLC_BAEJUNG_JI_AMT,0) AS SECHUL_BAEJEONG2,                
    NVL(BIZPLC_GAM_BAEJUNG_IP_AMT,0) AS SECHUL_HWANSU2,                
    NVL(TAXO_JI_AMT,0) AS SECHUL_JI2,                      
    NVL(TAXO_RTRN_AMT,0) AS SECHUL_BANNAB2,                    
    NVL(KWA_CRRC_IP_AMT,0) AS SECHUL_GYEONGJEONG_IB2,                 
    NVL(KWA_CRRC_JI_AMT,0) AS SECHUL_GYEONGJEONG_JI2,                 
    NVL(GA_IWOL_IP_AMT,0) AS SEIB_GYULSANBF_IIB2,                   
    NVL(GA_IWOL_JI_AMT,0) AS SECHUL_GYULSANBF_IWOL2,                  
    NVL(DEP_MK_JI_AMT,0) - NVL(DEP_HJI_AMT,0) AS DEP2,                       
    NVL(MMDA,0) AS MMDA2,                       
    NVL(SUNP_AMT,0) AS SUNP_AMT2,          
    NVL(IWOL_GONGGEUM,0) AS IWOL_GONGGEUM2,      
    NVL(IWOL_MIJUNGSAN,0) AS IWOL_MIJUNGSAN2,      
    NVL(IWOL_MMDA,0) AS IWOL_MMDA2,         
    NVL(IWOL_GONGGEUM_DEP,0) AS IWOL_GONGGEUM_DEP2
     
 FROM
 (
  SELECT   
      RPT_HOIKYE_C AS HOIGYE_CODE
     ,A.SIGUMGO_ORG_C
     ,SUM(TAX_SUNP_IP_AMT) AS TAX_SUNP_IP_AMT
     ,SUM(SUIP_CHULNAP_BAEJUNG_AMT)
        +SUM(FUND_UNYONG_INT_AMT)
        +SUM(PMNY_DEP_INT_AMT)
        +SUM(BTDEP_INT_AMT)
        +SUM(JICULWO_BAEJUNG_IP_AMT) AS TAX_BAEJUNG_IP_AMT
     ,SUM(GWAON_PROC_JI_AMT) AS GWAON_PROC_JI_AMT
     ,SUM(TAX_IP_CRT_IP_AMT) AS TAX_IP_CRT_IP_AMT
     ,SUM(TAX_IP_CRT_JI_AMT) AS TAX_IP_CRT_JI_AMT
     ,SUM(BIZPLC_BAEJUNG_JI_AMT) AS BIZPLC_BAEJUNG_JI_AMT
     ,SUM(BIZPLC_GAM_BAEJUNG_IP_AMT) AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,SUM(TAXO_FUND_BAEJUNG_JI_AMT)
     +SUM(TAXO_HNDO_BAEJUNG_JI_AMT)
     +SUM(TAXO_FUND_GETBK_JI_AMT)
     +SUM(TAXO_HNDO_JICHUL_JI_AMT)
     +SUM(TAXO_HNDO_GETBK_JI_AMT)  AS TAXO_JI_AMT
    ,SUM(TAXO_RTRN_AMT) AS TAXO_RTRN_AMT
    ,SUM(KWA_CRRC_IP_AMT) AS KWA_CRRC_IP_AMT
    ,SUM(KWA_CRRC_JI_AMT) AS KWA_CRRC_JI_AMT
    ,SUM(GA_IWOL_IP_AMT) AS GA_IWOL_IP_AMT
    ,SUM(GA_IWOL_JI_AMT) AS GA_IWOL_JI_AMT
    ,SUM(DEP_MK_JI_AMT) AS DEP_MK_JI_AMT
    ,SUM(MR_FUND_AMT) AS MMDA
    ,SUM(DEP_HJI_AMT) AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
    ,SUM(GAM_BAEJUNG_JI_AMT) GAM_BAEJUNG_JI_AMT
  FROM RPT_TXIO_DDAC_TAB A, AC_LIST B
  WHERE  A.SGG_ACNO(+) = B.GONGGEUM_GYEJWA
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.BAS_DT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.BAS_DT(+) BETWEEN '20251031' AND '20251031'
  AND A.SIGUMGO_ORG_C(+) = '110'
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  -- 25.08.11 11-11, 11-12, 11-13 금액을 수입액에 잡아줌

  SELECT   
    RPT_HOIKYE_C AS HOIGYE_CODE
    , A.SIGUMGO_ORG_C
    , 0 AS TAX_SUNP_IP_AMT
    , 0 AS TAX_BAEJUNG_IP_AMT
    , 0 AS GWAON_PROC_JI_AMT
    , 0 AS TAX_IP_CRT_IP_AMT
    , 0 AS TAX_IP_CRT_JI_AMT
    , 0 AS BIZPLC_BAEJUNG_JI_AMT
    , 0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    , 0 AS TAXO_JI_AMT
    , 0 AS TAXO_RTRN_AMT
    , 0 AS KWA_CRRC_IP_AMT
    , 0 AS KWA_CRRC_JI_AMT
    , 0 AS GA_IWOL_IP_AMT
    , 0 AS GA_IWOL_JI_AMT
    , 0 AS DEP_MK_JI_AMT
    , 0 AS MMDA
    , 0 AS DEP_HJI_AMT
    , SUM(DECODE(CRT_CAN_G, 1 ,-1, 2, -1, 33, -1, 1) * DECODE(IPJI_G, 2, -1, 1) * TRAMT) AS SUNP_AMT
    , 0 AS IWOL_GONGGEUM
    , 0 AS IWOL_MIJUNGSAN
    , 0 AS IWOL_MMDA
    , 0 AS IWOL_GONGGEUM_DEP
    , 0 AS GAM_BAEJUNG_JI_AMT
  FROM ACL_SIGUMGO_SLV A, AC_LIST B
  WHERE  A.FIL_100_CTNT5(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.GJDT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.GJDT(+) BETWEEN '20251031' AND '20251031'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  AND A.SIGUMGO_TRX_G = 11
  AND A.SIGUMGO_IP_TRX_G IN (11, 12, 13)
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  SELECT  TO_CHAR(ICH_SIGUMGO_HOIKYE_C) HOIGYE_CODE
    ,A.SIGUMGO_ORG_C
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,SUM(JIBANGSE_AMT)  AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
   , 0 GAM_BAEJUNG_JI_AMT
   FROM   RPT_TXI_DDAC_TAB A
   WHERE  A.SIGUMGO_HOIKYE_YR = ( '2025' ) 
     AND A.SIGUMGO_ORG_C = '110'
     AND A.SUNAP_DT BETWEEN '20251031' AND '20251031'
     AND A.ICH_SIGUMGO_GUN_GU_C = 0
     GROUP BY ICH_SIGUMGO_HOIKYE_C, A.SIGUMGO_ORG_C
  UNION ALL 
  SELECT  TO_CHAR(HOIGYE_CODE) HOIGYE_CODE
    ,A.GEUMGO_CODE
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,SUM(CASE WHEN GUBUN_CODE = 1 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM
    ,SUM(CASE WHEN GUBUN_CODE = 5 THEN AMT1 ELSE 0 END) AS IWOL_MIJUNGSAN
    ,SUM(CASE WHEN GUBUN_CODE = 4 THEN AMT1 ELSE 0 END) AS IWOL_MMDA
    ,SUM(CASE WHEN GUBUN_CODE = 2 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM_DEP
   ,0 GAM_BAEJUNG_JI_AMT
    FROM   RPT_HOIGYE_IWOL A
   WHERE  A.HOIGYE_YEAR = ( '2025' - 1 ) 
     AND A.GEUMGO_CODE = '110'
     AND A.GUBUN_CODE IN (1, 2, 4, 5)
     AND A.KIJUNIL BETWEEN '20251031' AND '20251031'
     AND A.GUNGU_CODE = 0
     GROUP BY HOIGYE_CODE, A.GEUMGO_CODE
 )
) AA, RPT_HOIKYE_CD BB
WHERE AA.SIGUMGO_ORG_C(+) = BB.SIGUMGO_C
AND AA.HOIGYE_CODE(+) = BB.SIGUMGO_HOIKYE_C
  AND BB.SIGUMGO_HOIKYE_C IN ( 
    
     '1'
     
         )
   
AND BB.SIGUMGO_C = '110'
AND BB.USE_YN = 'Y'
GROUP BY BB.SIGUMGO_HOIKYE_C, BB.HOIKYE_NM
ORDER BY TO_NUMBER(BB.SIGUMGO_HOIKYE_C), BB.HOIKYE_NM


----------------------------------------------------------------




select 
 A.*
from (
 WITH AC_LIST AS (
  SELECT     
    T2.SIGUMGO_ORG_C
    ,T3.SIGUMGO_HOIKYE_C AS RPT_HOIKYE_C
    ,T2.GONGGEUM_GYEJWA
    ,T2.GONGGEUM_GYEJWA_NM
    ,T2.SIGUMGO_HOIKYE_YR
  FROM
    (
  SELECT
    T1.SIGUMGO_ORG_C
    ,T1.ICH_SIGUMGO_GUN_GU_C
    ,T1.ICH_SIGUMGO_HOIKYE_C
    ,T1.SIGUMGO_AC_B
    ,T1.SIGUMGO_AC_SER
    ,T1.SIGUMGO_HOIKYE_YR
    ,LPAD(T1.SIGUMGO_ORG_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_GUN_GU_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_HOIKYE_C, 2, 0)||RPAD(T1.SIGUMGO_AC_B, 2, 0)||LPAD(T1.SIGUMGO_AC_SER, 5, '0')||SUBSTR(T1.SIGUMGO_HOIKYE_YR, 3, 2) AS  GONGGEUM_GYEJWA    
    ,T1.LINKAC_KWA_C ||'000'|| T1.LINK_ACSER AS GONGGEUM_YUDONG_ACNO
    ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
  FROM
    ACL_SIGUMGO_MAS T1
  WHERE 1=1
    AND T1.SIGUMGO_ORG_C = '110'
    AND T1.SIGUMGO_HOIKYE_YR IN ('2025', '9999')
    AND T1.MNG_NO = 1
    ) T2
    ,RPT_AC_BY_HOIKYE_MAPP T3
  WHERE 1=1
    AND T2.GONGGEUM_GYEJWA = T3.SIGUMGO_ACNO
    AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
    AND T2.SIGUMGO_ORG_C = T3.SIGUMGO_C
 )
 SELECT
    HOIGYE_CODE,
    SIGUMGO_ORG_C,
           NVL(TAX_SUNP_IP_AMT,0) AS SEIB_SUIP,           
    NVL(TAX_BAEJUNG_IP_AMT,0) AS TAX_BAEJUNG_IP_AMT,    
    NVL(GWAON_PROC_JI_AMT,0) AS SEIB_BANNAB,                  
    NVL(TAX_IP_CRT_IP_AMT,0) AS SEIB_GYEONGJEONG_IB,       
    NVL(TAX_IP_CRT_JI_AMT,0) AS SEIB_GYEONGJEONG_JI,                  
    NVL(BIZPLC_BAEJUNG_JI_AMT,0)+NVL(GAM_BAEJUNG_JI_AMT,0) AS SECHUL_BAEJEONG,                 
    NVL(BIZPLC_GAM_BAEJUNG_IP_AMT,0) AS SECHUL_HWANSU,                
    NVL(TAXO_JI_AMT,0) AS SECHUL_JI,                       
    NVL(TAXO_RTRN_AMT,0) AS SECHUL_BANNAB,                    
    NVL(KWA_CRRC_IP_AMT,0) AS SECHUL_GYEONGJEONG_IB,                 
    NVL(KWA_CRRC_JI_AMT,0) AS SECHUL_GYEONGJEONG_JI,                 
    NVL(GA_IWOL_IP_AMT,0) AS SEIB_GYULSANBF_IIB,                   
    NVL(GA_IWOL_JI_AMT,0) AS SECHUL_GYULSANBF_IWOL,                  
    NVL(DEP_MK_JI_AMT,0) - NVL(DEP_HJI_AMT,0) AS DEP,                       
    NVL(MMDA,0) AS MMDA,                       
    NVL(SUNP_AMT,0) AS SUNP_AMT,           
    NVL(IWOL_GONGGEUM,0) AS IWOL_GONGGEUM,      
    NVL(IWOL_MIJUNGSAN,0) AS IWOL_MIJUNGSAN ,      
    NVL(IWOL_MMDA,0) AS IWOL_MMDA,         
     NVL(IWOL_GONGGEUM_DEP,0) AS IWOL_GONGGEUM_DEP,    
    0 AS SEIB_SUIP2,                
    0 AS TAX_BAEJUNG_IP_AMT2,           
    0 AS SEIB_BANNAB2,                        
    0 AS SEIB_GYEONGJEONG_IB2,             
    0 AS SEIB_GYEONGJEONG_JI2,                        
    0 AS SECHUL_BAEJEONG2,                        
    0 AS SECHUL_HWANSU2,                        
    0 AS SECHUL_JI2,                           
    0 AS SECHUL_BANNAB2,                         
    0 AS SECHUL_GYEONGJEONG_IB2,                       
    0 AS SECHUL_GYEONGJEONG_JI2,                       
    0 AS SEIB_GYULSANBF_IIB2,                        
    0 AS SECHUL_GYULSANBF_IWOL2,                       
    0 AS DEP2,                            
    0 AS MMDA2,                          
    0 AS SUNP_AMT2,              
    0 AS IWOL_GONGGEUM2,           
    0 AS IWOL_MIJUNGSAN2 ,            
    0 AS IWOL_MMDA2,             
     0 AS IWOL_GONGGEUM_DEP2          
 FROM
 (
  SELECT   
      RPT_HOIKYE_C AS HOIGYE_CODE
     ,A.SIGUMGO_ORG_C
     ,SUM(TAX_SUNP_IP_AMT) AS TAX_SUNP_IP_AMT
     ,SUM(SUIP_CHULNAP_BAEJUNG_AMT)
        +SUM(FUND_UNYONG_INT_AMT)
        +SUM(PMNY_DEP_INT_AMT)
        +SUM(BTDEP_INT_AMT)
        +SUM(JICULWO_BAEJUNG_IP_AMT) AS TAX_BAEJUNG_IP_AMT
     ,SUM(GWAON_PROC_JI_AMT) AS GWAON_PROC_JI_AMT
     ,SUM(TAX_IP_CRT_IP_AMT) AS TAX_IP_CRT_IP_AMT
     ,SUM(TAX_IP_CRT_JI_AMT) AS TAX_IP_CRT_JI_AMT
     ,SUM(BIZPLC_BAEJUNG_JI_AMT) AS BIZPLC_BAEJUNG_JI_AMT
     ,SUM(BIZPLC_GAM_BAEJUNG_IP_AMT) AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,SUM(TAXO_FUND_BAEJUNG_JI_AMT)
     +SUM(TAXO_HNDO_BAEJUNG_JI_AMT)
     +SUM(TAXO_FUND_GETBK_JI_AMT)
     +SUM(TAXO_HNDO_JICHUL_JI_AMT)
     +SUM(TAXO_HNDO_GETBK_JI_AMT)  AS TAXO_JI_AMT
    ,SUM(TAXO_RTRN_AMT) AS TAXO_RTRN_AMT
    ,SUM(KWA_CRRC_IP_AMT) AS KWA_CRRC_IP_AMT
    ,SUM(KWA_CRRC_JI_AMT) AS KWA_CRRC_JI_AMT
    ,SUM(GA_IWOL_IP_AMT) AS GA_IWOL_IP_AMT
    ,SUM(GA_IWOL_JI_AMT) AS GA_IWOL_JI_AMT
    ,SUM(DEP_MK_JI_AMT) AS DEP_MK_JI_AMT
    ,SUM(MR_FUND_AMT) AS MMDA
    ,SUM(DEP_HJI_AMT) AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
    ,SUM(GAM_BAEJUNG_JI_AMT) GAM_BAEJUNG_JI_AMT
  FROM RPT_TXIO_DDAC_TAB A, AC_LIST B
  WHERE  A.SGG_ACNO(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.BAS_DT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.BAS_DT(+) BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  -- 25.08.11 11-11, 11-12, 11-13 금액을 수입액에 잡아줌

  SELECT   
    RPT_HOIKYE_C AS HOIGYE_CODE
    , A.SIGUMGO_ORG_C
    , 0 AS TAX_SUNP_IP_AMT
    , 0 AS TAX_BAEJUNG_IP_AMT
    , 0 AS GWAON_PROC_JI_AMT
    , 0 AS TAX_IP_CRT_IP_AMT
    , 0 AS TAX_IP_CRT_JI_AMT
    , 0 AS BIZPLC_BAEJUNG_JI_AMT
    , 0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    , 0 AS TAXO_JI_AMT
    , 0 AS TAXO_RTRN_AMT
    , 0 AS KWA_CRRC_IP_AMT
    , 0 AS KWA_CRRC_JI_AMT
    , 0 AS GA_IWOL_IP_AMT
    , 0 AS GA_IWOL_JI_AMT
    , 0 AS DEP_MK_JI_AMT
    , 0 AS MMDA
    , 0 AS DEP_HJI_AMT
    , SUM(DECODE(CRT_CAN_G, 1 ,-1, 2, -1, 33, -1, 1) * DECODE(IPJI_G, 2, -1, 1) * TRAMT) AS SUNP_AMT
    , 0 AS IWOL_GONGGEUM
    , 0 AS IWOL_MIJUNGSAN
    , 0 AS IWOL_MMDA
    , 0 AS IWOL_GONGGEUM_DEP
    , 0 AS GAM_BAEJUNG_JI_AMT
  FROM ACL_SIGUMGO_SLV A, AC_LIST B
  WHERE  A.FIL_100_CTNT5(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.GJDT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.GJDT(+) BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  AND A.SIGUMGO_TRX_G = 11
  AND A.SIGUMGO_IP_TRX_G IN (11, 12, 13)
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  SELECT  TO_CHAR(ICH_SIGUMGO_HOIKYE_C) HOIGYE_CODE
    ,A.SIGUMGO_ORG_C
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,SUM(JIBANGSE_AMT)  AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
    ,0 GAM_BAEJUNG_JI_AMT
   FROM   RPT_TXI_DDAC_TAB A
   WHERE  A.SIGUMGO_HOIKYE_YR = ( '2025' ) 
     AND A.SIGUMGO_ORG_C = '110'
     AND A.SUNAP_DT BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
     AND A.ICH_SIGUMGO_GUN_GU_C = 0    
     GROUP BY ICH_SIGUMGO_HOIKYE_C, A.SIGUMGO_ORG_C
  UNION ALL
  SELECT  TO_CHAR(HOIGYE_CODE) HOIGYE_CODE
    ,GEUMGO_CODE
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,SUM(CASE WHEN GUBUN_CODE = 1 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM
    ,SUM(CASE WHEN GUBUN_CODE = 5 THEN AMT1 ELSE 0 END) AS IWOL_MIJUNGSAN
    ,SUM(CASE WHEN GUBUN_CODE = 4 THEN AMT1 ELSE 0 END) AS IWOL_MMDA
    ,SUM(CASE WHEN GUBUN_CODE = 2 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM_DEP
    ,0 GAM_BAEJUNG_JI_AMT
   FROM   RPT_HOIGYE_IWOL A
   WHERE  A.HOIGYE_YEAR = ( '2025' - 1 )
     AND A.GEUMGO_CODE = '110'
     AND A.GUBUN_CODE IN (1, 2, 4, 5)
     AND A.KIJUNIL BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
     AND A.GUNGU_CODE = 0
     GROUP BY HOIGYE_CODE, GEUMGO_CODE
 ) 
 UNION ALL
 SELECT   
    HOIGYE_CODE,
    SIGUMGO_ORG_C,
           0 AS SEIB_SUIP,                
    0 AS TAX_BAEJUNG_IP_AMT,           
    0 AS SEIB_BANNAB,                        
    0 AS SEIB_GYEONGJEONG_IB,             
    0 AS SEIB_GYEONGJEONG_JI,                        
    0 AS SECHUL_BAEJEONG,                        
    0 AS SECHUL_HWANSU,                        
    0 AS SECHUL_JI,                           
    0 AS SECHUL_BANNAB,                         
    0 AS SECHUL_GYEONGJEONG_IB,                       
    0 AS SECHUL_GYEONGJEONG_JI,                       
    0 AS SEIB_GYULSANBF_IIB,                         
    0 AS SECHUL_GYULSANBF_IWOL,                       
    0 AS DEP,                            
    0 AS MMDA,                          
    0 AS SUNP_AMT,               
    0 AS IWOL_GONGGEUM,            
    0 AS IWOL_MIJUNGSAN ,            
    0 AS IWOL_MMDA,             
     0 AS IWOL_GONGGEUM_DEP,           
           NVL(TAX_SUNP_IP_AMT,0) AS SEIB_SUIP2,          
    NVL(TAX_BAEJUNG_IP_AMT,0) AS TAX_BAEJUNG_IP_AMT2,    
    NVL(GWAON_PROC_JI_AMT,0) AS SEIB_BANNAB2,                 
    NVL(TAX_IP_CRT_IP_AMT,0) AS SEIB_GYEONGJEONG_IB2,       
    NVL(TAX_IP_CRT_JI_AMT,0) AS SEIB_GYEONGJEONG_JI2,                  
    NVL(BIZPLC_BAEJUNG_JI_AMT,0) AS SECHUL_BAEJEONG2,                
    NVL(BIZPLC_GAM_BAEJUNG_IP_AMT,0) AS SECHUL_HWANSU2,                
    NVL(TAXO_JI_AMT,0) AS SECHUL_JI2,                      
    NVL(TAXO_RTRN_AMT,0) AS SECHUL_BANNAB2,                    
    NVL(KWA_CRRC_IP_AMT,0) AS SECHUL_GYEONGJEONG_IB2,                 
    NVL(KWA_CRRC_JI_AMT,0) AS SECHUL_GYEONGJEONG_JI2,                 
    NVL(GA_IWOL_IP_AMT,0) AS SEIB_GYULSANBF_IIB2,                   
    NVL(GA_IWOL_JI_AMT,0) AS SECHUL_GYULSANBF_IWOL2,                  
    NVL(DEP_MK_JI_AMT,0) - NVL(DEP_HJI_AMT,0) AS DEP2,                       
    NVL(MMDA,0) AS MMDA2,                       
    NVL(SUNP_AMT,0) AS SUNP_AMT2,          
    NVL(IWOL_GONGGEUM,0) AS IWOL_GONGGEUM2,      
    NVL(IWOL_MIJUNGSAN,0) AS IWOL_MIJUNGSAN2,      
    NVL(IWOL_MMDA,0) AS IWOL_MMDA2,         
    NVL(IWOL_GONGGEUM_DEP,0) AS IWOL_GONGGEUM_DEP2
     
 FROM
 (
  SELECT   
      RPT_HOIKYE_C AS HOIGYE_CODE
     ,A.SIGUMGO_ORG_C
     ,SUM(TAX_SUNP_IP_AMT) AS TAX_SUNP_IP_AMT
     ,SUM(SUIP_CHULNAP_BAEJUNG_AMT)
        +SUM(FUND_UNYONG_INT_AMT)
        +SUM(PMNY_DEP_INT_AMT)
        +SUM(BTDEP_INT_AMT)
        +SUM(JICULWO_BAEJUNG_IP_AMT) AS TAX_BAEJUNG_IP_AMT
     ,SUM(GWAON_PROC_JI_AMT) AS GWAON_PROC_JI_AMT
     ,SUM(TAX_IP_CRT_IP_AMT) AS TAX_IP_CRT_IP_AMT
     ,SUM(TAX_IP_CRT_JI_AMT) AS TAX_IP_CRT_JI_AMT
     ,SUM(BIZPLC_BAEJUNG_JI_AMT) AS BIZPLC_BAEJUNG_JI_AMT
     ,SUM(BIZPLC_GAM_BAEJUNG_IP_AMT) AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,SUM(TAXO_FUND_BAEJUNG_JI_AMT)
     +SUM(TAXO_HNDO_BAEJUNG_JI_AMT)
     +SUM(TAXO_FUND_GETBK_JI_AMT)
     +SUM(TAXO_HNDO_JICHUL_JI_AMT)
     +SUM(TAXO_HNDO_GETBK_JI_AMT)  AS TAXO_JI_AMT
    ,SUM(TAXO_RTRN_AMT) AS TAXO_RTRN_AMT
    ,SUM(KWA_CRRC_IP_AMT) AS KWA_CRRC_IP_AMT
    ,SUM(KWA_CRRC_JI_AMT) AS KWA_CRRC_JI_AMT
    ,SUM(GA_IWOL_IP_AMT) AS GA_IWOL_IP_AMT
    ,SUM(GA_IWOL_JI_AMT) AS GA_IWOL_JI_AMT
    ,SUM(DEP_MK_JI_AMT) AS DEP_MK_JI_AMT
    ,SUM(MR_FUND_AMT) AS MMDA
    ,SUM(DEP_HJI_AMT) AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
    ,SUM(GAM_BAEJUNG_JI_AMT) GAM_BAEJUNG_JI_AMT
  FROM RPT_TXIO_DDAC_TAB A, AC_LIST B
  WHERE  A.SGG_ACNO(+) = B.GONGGEUM_GYEJWA
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.BAS_DT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.BAS_DT(+) BETWEEN '20251031' AND '20251031'
  AND A.SIGUMGO_ORG_C(+) = '110'
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  -- 25.08.11 11-11, 11-12, 11-13 금액을 수입액에 잡아줌

  SELECT   
    RPT_HOIKYE_C AS HOIGYE_CODE
    , A.SIGUMGO_ORG_C
    , 0 AS TAX_SUNP_IP_AMT
    , 0 AS TAX_BAEJUNG_IP_AMT
    , 0 AS GWAON_PROC_JI_AMT
    , 0 AS TAX_IP_CRT_IP_AMT
    , 0 AS TAX_IP_CRT_JI_AMT
    , 0 AS BIZPLC_BAEJUNG_JI_AMT
    , 0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    , 0 AS TAXO_JI_AMT
    , 0 AS TAXO_RTRN_AMT
    , 0 AS KWA_CRRC_IP_AMT
    , 0 AS KWA_CRRC_JI_AMT
    , 0 AS GA_IWOL_IP_AMT
    , 0 AS GA_IWOL_JI_AMT
    , 0 AS DEP_MK_JI_AMT
    , 0 AS MMDA
    , 0 AS DEP_HJI_AMT
    , SUM(DECODE(CRT_CAN_G, 1 ,-1, 2, -1, 33, -1, 1) * DECODE(IPJI_G, 2, -1, 1) * TRAMT) AS SUNP_AMT
    , 0 AS IWOL_GONGGEUM
    , 0 AS IWOL_MIJUNGSAN
    , 0 AS IWOL_MMDA
    , 0 AS IWOL_GONGGEUM_DEP
    , 0 AS GAM_BAEJUNG_JI_AMT
  FROM ACL_SIGUMGO_SLV A, AC_LIST B
  WHERE  A.FIL_100_CTNT5(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.GJDT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.GJDT(+) BETWEEN '20251031' AND '20251031'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  AND A.SIGUMGO_TRX_G = 11
  AND A.SIGUMGO_IP_TRX_G IN (11, 12, 13)
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  SELECT  TO_CHAR(ICH_SIGUMGO_HOIKYE_C) HOIGYE_CODE
    ,A.SIGUMGO_ORG_C
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,SUM(JIBANGSE_AMT)  AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
   , 0 GAM_BAEJUNG_JI_AMT
   FROM   RPT_TXI_DDAC_TAB A
   WHERE  A.SIGUMGO_HOIKYE_YR = ( '2025' ) 
     AND A.SIGUMGO_ORG_C = '110'
     AND A.SUNAP_DT BETWEEN '20251031' AND '20251031'
     AND A.ICH_SIGUMGO_GUN_GU_C = 0
     GROUP BY ICH_SIGUMGO_HOIKYE_C, A.SIGUMGO_ORG_C
  UNION ALL 
  SELECT  TO_CHAR(HOIGYE_CODE) HOIGYE_CODE
    ,A.GEUMGO_CODE
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,SUM(CASE WHEN GUBUN_CODE = 1 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM
    ,SUM(CASE WHEN GUBUN_CODE = 5 THEN AMT1 ELSE 0 END) AS IWOL_MIJUNGSAN
    ,SUM(CASE WHEN GUBUN_CODE = 4 THEN AMT1 ELSE 0 END) AS IWOL_MMDA
    ,SUM(CASE WHEN GUBUN_CODE = 2 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM_DEP
   ,0 GAM_BAEJUNG_JI_AMT
    FROM   RPT_HOIGYE_IWOL A
   WHERE  A.HOIGYE_YEAR = ( '2025' - 1 ) 
     AND A.GEUMGO_CODE = '110'
     AND A.GUBUN_CODE IN (1, 2, 4, 5)
     AND A.KIJUNIL BETWEEN '20251031' AND '20251031'
     AND A.GUNGU_CODE = 0
     GROUP BY HOIGYE_CODE, A.GEUMGO_CODE
 ) 
 ) A 
 where A.HOIGYE_CODE = '1'



 -----------------------------------------------------------------------


WITH AC_LIST AS (
  SELECT     
    T2.SIGUMGO_ORG_C
    ,T3.SIGUMGO_HOIKYE_C AS RPT_HOIKYE_C
    ,T2.GONGGEUM_GYEJWA
    ,T2.GONGGEUM_GYEJWA_NM
    ,T2.SIGUMGO_HOIKYE_YR
  FROM
    (
  SELECT
    T1.SIGUMGO_ORG_C
    ,T1.ICH_SIGUMGO_GUN_GU_C
    ,T1.ICH_SIGUMGO_HOIKYE_C
    ,T1.SIGUMGO_AC_B
    ,T1.SIGUMGO_AC_SER
    ,T1.SIGUMGO_HOIKYE_YR
    ,LPAD(T1.SIGUMGO_ORG_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_GUN_GU_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_HOIKYE_C, 2, 0)||RPAD(T1.SIGUMGO_AC_B, 2, 0)||LPAD(T1.SIGUMGO_AC_SER, 5, '0')||SUBSTR(T1.SIGUMGO_HOIKYE_YR, 3, 2) AS  GONGGEUM_GYEJWA    
    ,T1.LINKAC_KWA_C ||'000'|| T1.LINK_ACSER AS GONGGEUM_YUDONG_ACNO
    ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
  FROM
    ACL_SIGUMGO_MAS T1
  WHERE 1=1
    AND T1.SIGUMGO_ORG_C = '110'
    AND T1.SIGUMGO_HOIKYE_YR IN ('2025', '9999')
    AND T1.MNG_NO = 1
    ) T2
    ,RPT_AC_BY_HOIKYE_MAPP T3
  WHERE 1=1
    AND T2.GONGGEUM_GYEJWA = T3.SIGUMGO_ACNO
    AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
    AND T2.SIGUMGO_ORG_C = T3.SIGUMGO_C
 )
 SELECT   
    RPT_HOIKYE_C AS HOIGYE_CODE
    , A.SIGUMGO_ORG_C
    , 0 AS TAX_SUNP_IP_AMT
    , 0 AS TAX_BAEJUNG_IP_AMT
    , 0 AS GWAON_PROC_JI_AMT
    , 0 AS TAX_IP_CRT_IP_AMT
    , 0 AS TAX_IP_CRT_JI_AMT
    , 0 AS BIZPLC_BAEJUNG_JI_AMT
    , 0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    , 0 AS TAXO_JI_AMT
    , 0 AS TAXO_RTRN_AMT
    , 0 AS KWA_CRRC_IP_AMT
    , 0 AS KWA_CRRC_JI_AMT
    , 0 AS GA_IWOL_IP_AMT
    , 0 AS GA_IWOL_JI_AMT
    , 0 AS DEP_MK_JI_AMT
    , 0 AS MMDA
    , 0 AS DEP_HJI_AMT
    , SUM(DECODE(CRT_CAN_G, 1 ,-1, 2, -1, 33, -1, 1) * DECODE(IPJI_G, 2, -1, 1) * TRAMT) AS SUNP_AMT
    , 0 AS IWOL_GONGGEUM
    , 0 AS IWOL_MIJUNGSAN
    , 0 AS IWOL_MMDA
    , 0 AS IWOL_GONGGEUM_DEP
    , 0 AS GAM_BAEJUNG_JI_AMT
  FROM ACL_SIGUMGO_SLV A, AC_LIST B
  WHERE  A.FIL_100_CTNT5(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.GJDT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.GJDT(+) BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  AND A.SIGUMGO_TRX_G = 11
  AND A.SIGUMGO_IP_TRX_G IN (11, 12, 13)
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  SELECT  TO_CHAR(ICH_SIGUMGO_HOIKYE_C) HOIGYE_CODE
    ,A.SIGUMGO_ORG_C
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,SUM(JIBANGSE_AMT)  AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
    ,0 GAM_BAEJUNG_JI_AMT
   FROM   RPT_TXI_DDAC_TAB A
   WHERE  A.SIGUMGO_HOIKYE_YR = ( '2025' ) 
     AND A.SIGUMGO_ORG_C = '110'
     AND A.SUNAP_DT BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
     AND A.ICH_SIGUMGO_GUN_GU_C = 0    
     GROUP BY ICH_SIGUMGO_HOIKYE_C, A.SIGUMGO_ORG_C

     -----------------------------------------------------


-- 거래내역
WITH AC_LIST AS (
  SELECT     
    T2.SIGUMGO_ORG_C
    ,T3.SIGUMGO_HOIKYE_C AS RPT_HOIKYE_C
    ,T2.GONGGEUM_GYEJWA
    ,T2.GONGGEUM_GYEJWA_NM
    ,T2.SIGUMGO_HOIKYE_YR
  FROM
    (
  SELECT
    T1.SIGUMGO_ORG_C
    ,T1.ICH_SIGUMGO_GUN_GU_C
    ,T1.ICH_SIGUMGO_HOIKYE_C
    ,T1.SIGUMGO_AC_B
    ,T1.SIGUMGO_AC_SER
    ,T1.SIGUMGO_HOIKYE_YR
    ,LPAD(T1.SIGUMGO_ORG_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_GUN_GU_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_HOIKYE_C, 2, 0)||RPAD(T1.SIGUMGO_AC_B, 2, 0)||LPAD(T1.SIGUMGO_AC_SER, 5, '0')||SUBSTR(T1.SIGUMGO_HOIKYE_YR, 3, 2) AS  GONGGEUM_GYEJWA    
    ,T1.LINKAC_KWA_C ||'000'|| T1.LINK_ACSER AS GONGGEUM_YUDONG_ACNO
    ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
  FROM
    ACL_SIGUMGO_MAS T1
  WHERE 1=1
    AND T1.SIGUMGO_ORG_C = '110'
    AND T1.SIGUMGO_HOIKYE_YR IN ('2025', '9999')
    AND T1.MNG_NO = 1
    ) T2
    ,RPT_AC_BY_HOIKYE_MAPP T3
  WHERE 1=1
    AND T2.GONGGEUM_GYEJWA = T3.SIGUMGO_ACNO
    AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
    AND T2.SIGUMGO_ORG_C = T3.SIGUMGO_C
 )
 SELECT A.*
  FROM ACL_SIGUMGO_SLV A, AC_LIST B
  WHERE  A.FIL_100_CTNT5(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.GJDT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.GJDT(+) BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  AND A.SIGUMGO_TRX_G = 11
  AND A.SIGUMGO_IP_TRX_G IN (11, 12, 13)

-----------------------------------------------------------------------
-- 수납금액

WITH AC_LIST AS (
  SELECT     
    T2.SIGUMGO_ORG_C
    ,T3.SIGUMGO_HOIKYE_C AS RPT_HOIKYE_C
    ,T2.GONGGEUM_GYEJWA
    ,T2.GONGGEUM_GYEJWA_NM
    ,T2.SIGUMGO_HOIKYE_YR
  FROM
    (
  SELECT
    T1.SIGUMGO_ORG_C
    ,T1.ICH_SIGUMGO_GUN_GU_C
    ,T1.ICH_SIGUMGO_HOIKYE_C
    ,T1.SIGUMGO_AC_B
    ,T1.SIGUMGO_AC_SER
    ,T1.SIGUMGO_HOIKYE_YR
    ,LPAD(T1.SIGUMGO_ORG_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_GUN_GU_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_HOIKYE_C, 2, 0)||RPAD(T1.SIGUMGO_AC_B, 2, 0)||LPAD(T1.SIGUMGO_AC_SER, 5, '0')||SUBSTR(T1.SIGUMGO_HOIKYE_YR, 3, 2) AS  GONGGEUM_GYEJWA    
    ,T1.LINKAC_KWA_C ||'000'|| T1.LINK_ACSER AS GONGGEUM_YUDONG_ACNO
    ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
  FROM
    ACL_SIGUMGO_MAS T1
  WHERE 1=1
    AND T1.SIGUMGO_ORG_C = '110'
    AND T1.SIGUMGO_HOIKYE_YR IN ('2025', '9999')
    AND T1.MNG_NO = 1
    ) T2
    ,RPT_AC_BY_HOIKYE_MAPP T3
  WHERE 1=1
    AND T2.GONGGEUM_GYEJWA = T3.SIGUMGO_ACNO
    AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
    AND T2.SIGUMGO_ORG_C = T3.SIGUMGO_C
 )
SELECT  A.SUNAP_DT,
        A.JIBANGSE_AMT
   FROM   RPT_TXI_DDAC_TAB A
   WHERE  A.SIGUMGO_HOIKYE_YR = ( '2025' ) 
     AND A.SIGUMGO_ORG_C = '110'
     AND TO_CHAR(ICH_SIGUMGO_HOIKYE_C) = '1'
     AND A.SUNAP_DT BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
     AND A.ICH_SIGUMGO_GUN_GU_C = 0    
  ORDER BY A.SUNAP_DT   
     
-----------------------------------------------------------------------------


SELECT
   T1.GBN
    ,T1.SUNAPIL
    ,T1.REF_S_C
    ,T1.REF_D_C
    ,T1.DANGHAENG_GUBUN
    ,T1.SUNAP_ORG_NM
    ,T1.SANGSUDO
    ,T1.HASUDO
,T1.GIBAN_GUKSE
,T1.GIBAN_SISE
,T1.GICHO
,T1.HEALTH
,T1.GYOTONG
,T1.DOSI
,T1.JIHASU
,T1.HAPGYE
FROM
     (
      SELECT
           1 AS GBN
          ,'20251031' AS SUNAPIL
          ,TO_NUMBER(T1.CMM_DTL_C) AS REF_S_C
          ,TO_NUMBER(T1.UPMU_HMK_1_SLV) AS REF_D_C
          ,T2.CMM_DTL_C_NM AS DANGHAENG_GUBUN
          ,T1.CMM_DTL_C_NM AS SUNAP_ORG_NM
          ,SUM(DECODE(T3.JIBGYE_CODE, 1, T3.BONSE_AMT, 0)) AS SANGSUDO
          ,SUM(DECODE(T3.JIBGYE_CODE, 4, T3.BONSE_AMT, 0)) AS HASUDO
          ,SUM(DECODE(T3.JIBGYE_CODE, 10, T3.BONSE_AMT, 0)) AS GIBAN_GUKSE
 ,SUM(DECODE(T3.JIBGYE_CODE, 11, T3.BONSE_AMT, 0)) AS GIBAN_SISE
 ,SUM(DECODE(T3.JIBGYE_CODE, 14, T3.BONSE_AMT, 0)) AS GICHO
 ,SUM(DECODE(T3.JIBGYE_CODE, 15, T3.BONSE_AMT, 0)) AS HEALTH
 ,SUM(DECODE(T3.JIBGYE_CODE, 16, T3.BONSE_AMT, 0)) AS GYOTONG
 ,SUM(DECODE(T3.JIBGYE_CODE, 25, T3.BONSE_AMT, 0)) AS DOSI
 ,SUM(DECODE(T3.JIBGYE_CODE, 38, T3.BONSE_AMT, 0)) AS JIHASU
          ,NVL(SUM(T3.BONSE_AMT), 0) AS HAPGYE
      FROM
           SFI_CMM_C_DAT T1
          ,SFI_CMM_C_DAT T2
          ,RPT_SUNAP_JIBGYE T3
      WHERE 1=1
           AND NVL('', ' ') <> 'true'
           AND T1.UPMU_HMK_1_SLV = T2.CMM_DTL_C
           AND T1.CMM_DTL_C = T3.ORG_MNGBR(+)
           AND T1.CMM_C_NM = 'RPT춘천 수납기관'
           AND T1.USE_YN = 'Y'
           AND T2.CMM_C_NM = 'RPT수납기관유형'
           AND T2.USE_YN = 'Y'
           AND T3.SUNAPIL(+) = '20251031'
           AND T3.GEUMGO_CODE(+) = '110'
           AND T3.HOIGYE_YEAR(+) = '2025'
      GROUP BY
           T1.CMM_DTL_C
          ,T1.UPMU_HMK_1_SLV
          ,T2.CMM_DTL_C_NM
          ,T1.CMM_DTL_C_NM
      UNION ALL
      SELECT
           1 AS GBN
          ,T3.SUNAPIL
          ,TO_NUMBER(T1.CMM_DTL_C) AS REF_S_C
          ,TO_NUMBER(T1.UPMU_HMK_1_SLV) AS REF_D_C
          ,T2.CMM_DTL_C_NM AS DANGHAENG_GUBUN
          ,T1.CMM_DTL_C_NM AS SUNAP_ORG_NM
          ,SUM(DECODE(T3.JIBGYE_CODE, 1, T3.BONSE_AMT, 0)) AS SANGSUDO
          ,SUM(DECODE(T3.JIBGYE_CODE, 4, T3.BONSE_AMT, 0)) AS HASUDO
          ,SUM(DECODE(T3.JIBGYE_CODE, 10, T3.BONSE_AMT, 0)) AS GIBAN_GUKSE
 ,SUM(DECODE(T3.JIBGYE_CODE, 11, T3.BONSE_AMT, 0)) AS GIBAN_SISE
 ,SUM(DECODE(T3.JIBGYE_CODE, 14, T3.BONSE_AMT, 0)) AS GICHO
 ,SUM(DECODE(T3.JIBGYE_CODE, 15, T3.BONSE_AMT, 0)) AS HEALTH
 ,SUM(DECODE(T3.JIBGYE_CODE, 16, T3.BONSE_AMT, 0)) AS GYOTONG
 ,SUM(DECODE(T3.JIBGYE_CODE, 25, T3.BONSE_AMT, 0)) AS DOSI
 ,SUM(DECODE(T3.JIBGYE_CODE, 38, T3.BONSE_AMT, 0)) AS JIHASU
          ,NVL(SUM(T3.BONSE_AMT), 0) AS HAPGYE
      FROM
           SFI_CMM_C_DAT T1
          ,SFI_CMM_C_DAT T2
          ,RPT_SUNAP_JIBGYE T3
      WHERE 1=1
           AND NVL('', ' ') = 'true'
           AND T1.UPMU_HMK_1_SLV = T2.CMM_DTL_C
           AND T1.CMM_DTL_C = T3.ORG_MNGBR
           AND T1.CMM_C_NM = 'RPT춘천 수납기관'
           AND T1.USE_YN = 'Y'
           AND T2.CMM_C_NM = 'RPT수납기관유형'
           AND T2.USE_YN = 'Y'
           AND T3.SUNAPIL >= '20251031'
           AND T3.SUNAPIL <= '20251031'
           AND T3.GEUMGO_CODE = '110'
           AND T3.HOIGYE_YEAR = '2025'
           AND DECODE(NVL('', ' '), ' ', '99991231', NVL(T3.ICHEIL, '99991231')) > '20251031'
      GROUP BY
           T3.SUNAPIL
          ,T1.CMM_DTL_C
          ,T1.UPMU_HMK_1_SLV
          ,T2.CMM_DTL_C_NM
          ,T1.CMM_DTL_C_NM
      UNION ALL
      SELECT
           2 AS GBN
          ,T1.SUNAPIL
          ,0 AS REF_S_C
          ,0 AS REF_D_C
          ,'' AS DANGHAENG_GUBUN
          ,T1.SUNAPIL AS SUNAP_ORG_NM
          ,SUM(DECODE(T1.JIBGYE_CODE, 1, T1.BONSE_AMT, 0)) AS SANGSUDO
          ,SUM(DECODE(T1.JIBGYE_CODE, 4, T1.BONSE_AMT, 0)) AS HASUDO
          ,SUM(DECODE(T1.JIBGYE_CODE, 10, T1.BONSE_AMT, 0)) AS GIBAN_GUKSE
 ,SUM(DECODE(T1.JIBGYE_CODE, 11, T1.BONSE_AMT, 0)) AS GIBAN_SISE
 ,SUM(DECODE(T1.JIBGYE_CODE, 14, T1.BONSE_AMT, 0)) AS GICHO
 ,SUM(DECODE(T1.JIBGYE_CODE, 15, T1.BONSE_AMT, 0)) AS HEALTH
 ,SUM(DECODE(T1.JIBGYE_CODE, 16, T1.BONSE_AMT, 0)) AS GYOTONG
 ,SUM(DECODE(T1.JIBGYE_CODE, 25, T1.BONSE_AMT, 0)) AS DOSI
 ,SUM(DECODE(T1.JIBGYE_CODE, 38, T1.BONSE_AMT, 0)) AS JIHASU
          ,NVL(SUM(T1.BONSE_AMT), 0) AS HAPGYE
      FROM
           (
            SELECT
                 T1.SUNAPIL
                ,T1.JIBGYE_CODE
                ,T1.BONSE_AMT
            FROM
                 RPT_SUNAP_JIBGYE T1
            WHERE 1=1
                  AND T1.SUNAPIL >= DECODE(NVL('', ' '), 'true', '20251031', '2025' || '0101')
                 AND T1.SUNAPIL <= '20251031'
                 AND T1.GUNGU_CODE = 0
                 AND T1.GEUMGO_CODE = '110'
                 AND T1.HOIGYE_YEAR = '2025'
                 AND NVL(T1.ICHEIL, '99991231') > '20251031'
            UNION ALL
            SELECT
                 T1.SUNAPIL
                ,T1.JIBGYE_CODE
                ,T1.BONSE_AMT
            FROM
                 RPT_SUNAP_JIBGYE T1
                ,RPT_HOIKYE_CD T2
            WHERE 1=1
                 AND T1.JIBGYE_CODE = T2.SIGUMGO_HOIKYE_C
                 AND T1.GEUMGO_CODE = T2.SIGUMGO_C
                 AND T1.SUNAPIL >= '2024' || '0101'
                 AND T1.SUNAPIL <= '2024' || '1231'
                 AND T1.GUNGU_CODE = 0
                 AND T1.GEUMGO_CODE = '110'
                 AND T1.HOIGYE_YEAR = '2024'
                 AND NVL(T1.ICHEIL, '99991231') > '20251031'
                 AND T2.HOIKYE_ATRB_C = 1
                 AND DECODE(NVL('', ' '), 'true', '20251031', '2025' || '0101') = '2025' || '0101'
            UNION ALL
            SELECT
                 T1.SUNAPIL
                ,T1.JIBGYE_CODE
                ,T1.BONSE_AMT
            FROM
                 RPT_SUNAP_JIBGYE T1
                ,RPT_HOIKYE_CD T2
            WHERE 1=1
                 AND T1.JIBGYE_CODE = T2.SIGUMGO_HOIKYE_C
                 AND T1.GEUMGO_CODE = T2.SIGUMGO_C
                 AND T1.SUNAPIL >= '2024' || '0101'
                 AND T1.SUNAPIL <= '2025' || '0110'
                 AND T1.GUNGU_CODE = 0
                 AND T1.GEUMGO_CODE = '110'
                 AND T1.HOIGYE_YEAR = '2024'
                 AND NVL(T1.ICHEIL, '99991231') > '20251031'
                 AND T2.HOIKYE_ATRB_C = 9
                 AND DECODE(NVL('', ' '), 'true', '20251031', '2025' || '0101')  = '2025' || '0101'
                 AND '20251031' >= '2025' || '0101'
           ) T1
      GROUP BY
           T1.SUNAPIL
     ) T1
    ORDER BY GBN,SUNAPIL,REF_S_C,REF_D_C


    --------------------------------

    SELECT * FROM RPT_HOIKYE_CD
    WHERE SIGUMGO_C = 110


    SELECT
           2 AS GBN
          ,T1.SUNAPIL
          ,0 AS REF_S_C
          ,0 AS REF_D_C
          ,'' AS DANGHAENG_GUBUN
          ,T1.SUNAPIL AS SUNAP_ORG_NM
          ,SUM(DECODE(T1.JIBGYE_CODE, 1, T1.BONSE_AMT, 0)) AS SANGSUDO
          ,SUM(DECODE(T1.JIBGYE_CODE, 4, T1.BONSE_AMT, 0)) AS HASUDO
          ,SUM(DECODE(T1.JIBGYE_CODE, 10, T1.BONSE_AMT, 0)) AS GIBAN_GUKSE
 ,SUM(DECODE(T1.JIBGYE_CODE, 11, T1.BONSE_AMT, 0)) AS GIBAN_SISE
 ,SUM(DECODE(T1.JIBGYE_CODE, 14, T1.BONSE_AMT, 0)) AS GICHO
 ,SUM(DECODE(T1.JIBGYE_CODE, 15, T1.BONSE_AMT, 0)) AS HEALTH
 ,SUM(DECODE(T1.JIBGYE_CODE, 16, T1.BONSE_AMT, 0)) AS GYOTONG
 ,SUM(DECODE(T1.JIBGYE_CODE, 25, T1.BONSE_AMT, 0)) AS DOSI
 ,SUM(DECODE(T1.JIBGYE_CODE, 38, T1.BONSE_AMT, 0)) AS JIHASU
          ,NVL(SUM(T1.BONSE_AMT), 0) AS HAPGYE
      FROM
           (
            SELECT
                 T1.SUNAPIL
                ,T1.JIBGYE_CODE
                ,T1.BONSE_AMT
            FROM
                 RPT_SUNAP_JIBGYE T1
            WHERE 1=1
                  AND T1.SUNAPIL >= DECODE(NVL('', ' '), 'true', '20251031', '2025' || '0101')
                 AND T1.SUNAPIL <= '20251031'
                 AND T1.GUNGU_CODE = 0
                 AND T1.GEUMGO_CODE = '110'
                 AND T1.HOIGYE_YEAR = '2025'
                 AND NVL(T1.ICHEIL, '99991231') > '20251031'
            UNION ALL
            SELECT
                 T1.SUNAPIL
                ,T1.JIBGYE_CODE
                ,T1.BONSE_AMT
            FROM
                 RPT_SUNAP_JIBGYE T1
                ,RPT_HOIKYE_CD T2
            WHERE 1=1
                 AND T1.JIBGYE_CODE = T2.SIGUMGO_HOIKYE_C
                 AND T1.GEUMGO_CODE = T2.SIGUMGO_C
                 AND T1.SUNAPIL >= '2024' || '0101'
                 AND T1.SUNAPIL <= '2024' || '1231'
                 AND T1.GUNGU_CODE = 0
                 AND T1.GEUMGO_CODE = '110'
                 AND T1.HOIGYE_YEAR = '2024'
                 AND NVL(T1.ICHEIL, '99991231') > '20251031'
                 AND T2.HOIKYE_ATRB_C = 1
                 AND DECODE(NVL('', ' '), 'true', '20251031', '2025' || '0101') = '2025' || '0101'
            UNION ALL
            SELECT
                 T1.SUNAPIL
                ,T1.JIBGYE_CODE
                ,T1.BONSE_AMT
            FROM
                 RPT_SUNAP_JIBGYE T1
                ,RPT_HOIKYE_CD T2
            WHERE 1=1
                 AND T1.JIBGYE_CODE = T2.SIGUMGO_HOIKYE_C
                 AND T1.GEUMGO_CODE = T2.SIGUMGO_C
                 AND T1.SUNAPIL >= '2024' || '0101'
                 AND T1.SUNAPIL <= '2025' || '0110'
                 AND T1.GUNGU_CODE = 0
                 AND T1.GEUMGO_CODE = '110'
                 AND T1.HOIGYE_YEAR = '2024'
                 AND NVL(T1.ICHEIL, '99991231') > '20251031'
                 AND T2.HOIKYE_ATRB_C = 9
                 AND DECODE(NVL('', ' '), 'true', '20251031', '2025' || '0101')  = '2025' || '0101'
                 AND '20251031' >= '2025' || '0101'
           ) T1
      GROUP BY
           T1.SUNAPIL

 --------------------------------------------------------------------------------



 SELECT
                 T1.SUNAPIL
                 , T1.ICHEIL
                ,T1.JIBGYE_CODE
                ,T1.BONSE_AMT
            FROM
                 RPT_SUNAP_JIBGYE T1
            WHERE 1=1
                  AND T1.SUNAPIL >= DECODE(NVL('', ' '), 'true', '20251031', '2025' || '0101')
                 AND T1.SUNAPIL <= '20251031'
                 AND T1.GUNGU_CODE = 0
                 AND T1.GEUMGO_CODE = '110'
                 AND T1.HOIGYE_YEAR = '2025'
                 AND T1.JIBGYE_CODE = 1
                 AND NVL(T1.ICHEIL, '99991231') > '20251031'        
             ORDER BY   T1.SUNAPIL 



    SELECT
                 T1.SUNAPIL
                ,SUM(T1.BONSE_AMT) AS BONSE_AMT
            FROM
                 RPT_SUNAP_JIBGYE T1
            WHERE 1=1
                  AND T1.SUNAPIL >= DECODE(NVL('', ' '), 'true', '20251031', '2025' || '0101')
                 AND T1.SUNAPIL <= '20251031'
                 AND T1.GUNGU_CODE = 0
                 AND T1.GEUMGO_CODE = '110'
                 AND T1.HOIGYE_YEAR = '2025'
                 AND T1.JIBGYE_CODE = 1
                GROUP BY T1.SUNAPIL    
                ORDER BY T1.SUNAPIL
-----------------------------------------------------------
   SELECT 
   A.GJDT,
    SUM(DECODE(A.CRT_CAN_G, 1 ,-1, 2, -1, 33, -1, 1) * DECODE(A.IPJI_G, 2, -1, 1) * A.TRAMT) AS SUNP_AMT
   FROM ACL_SIGUMGO_SLV A
   WHERE 
   A.FIL_100_CTNT5 = '11000080900000199'
  AND A.GJDT BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
  AND A.SIGUMGO_ORG_C  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0   
  AND A.SIGUMGO_TRX_G = 11 
  AND A.SIGUMGO_IP_TRX_G = 1    
  GROUP BY A.GJDT   
  ORDER BY A.GJDT  

------------------------------------------------------------------

WITH AC_LIST AS (
  SELECT     
    T2.SIGUMGO_ORG_C
    ,T3.SIGUMGO_HOIKYE_C AS RPT_HOIKYE_C
    ,T2.GONGGEUM_GYEJWA
    ,T2.GONGGEUM_GYEJWA_NM
    ,T2.SIGUMGO_HOIKYE_YR
  FROM
    (
  SELECT
    T1.SIGUMGO_ORG_C
    ,T1.ICH_SIGUMGO_GUN_GU_C
    ,T1.ICH_SIGUMGO_HOIKYE_C
    ,T1.SIGUMGO_AC_B
    ,T1.SIGUMGO_AC_SER
    ,T1.SIGUMGO_HOIKYE_YR
    ,LPAD(T1.SIGUMGO_ORG_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_GUN_GU_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_HOIKYE_C, 2, 0)||RPAD(T1.SIGUMGO_AC_B, 2, 0)||LPAD(T1.SIGUMGO_AC_SER, 5, '0')||SUBSTR(T1.SIGUMGO_HOIKYE_YR, 3, 2) AS  GONGGEUM_GYEJWA    
    ,T1.LINKAC_KWA_C ||'000'|| T1.LINK_ACSER AS GONGGEUM_YUDONG_ACNO
    ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
  FROM
    ACL_SIGUMGO_MAS T1
  WHERE 1=1
    AND T1.SIGUMGO_ORG_C = '110'
    AND T1.SIGUMGO_HOIKYE_YR IN ('2025', '9999')
    AND T1.MNG_NO = 1
    ) T2
    ,RPT_AC_BY_HOIKYE_MAPP T3
  WHERE 1=1
    AND T2.GONGGEUM_GYEJWA = T3.SIGUMGO_ACNO
    AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
    AND T2.SIGUMGO_ORG_C = T3.SIGUMGO_C
 )
 SELECT
    HOIGYE_CODE,
    SIGUMGO_ORG_C,
           NVL(TAX_SUNP_IP_AMT,0) AS SEIB_SUIP,           
    NVL(TAX_BAEJUNG_IP_AMT,0) AS TAX_BAEJUNG_IP_AMT,    
    NVL(GWAON_PROC_JI_AMT,0) AS SEIB_BANNAB,                  
    NVL(TAX_IP_CRT_IP_AMT,0) AS SEIB_GYEONGJEONG_IB,       
    NVL(TAX_IP_CRT_JI_AMT,0) AS SEIB_GYEONGJEONG_JI,                  
    NVL(BIZPLC_BAEJUNG_JI_AMT,0)+NVL(GAM_BAEJUNG_JI_AMT,0) AS SECHUL_BAEJEONG,                 
    NVL(BIZPLC_GAM_BAEJUNG_IP_AMT,0) AS SECHUL_HWANSU,                
    NVL(TAXO_JI_AMT,0) AS SECHUL_JI,                       
    NVL(TAXO_RTRN_AMT,0) AS SECHUL_BANNAB,                    
    NVL(KWA_CRRC_IP_AMT,0) AS SECHUL_GYEONGJEONG_IB,                 
    NVL(KWA_CRRC_JI_AMT,0) AS SECHUL_GYEONGJEONG_JI,                 
    NVL(GA_IWOL_IP_AMT,0) AS SEIB_GYULSANBF_IIB,                   
    NVL(GA_IWOL_JI_AMT,0) AS SECHUL_GYULSANBF_IWOL,                  
    NVL(DEP_MK_JI_AMT,0) - NVL(DEP_HJI_AMT,0) AS DEP,                       
    NVL(MMDA,0) AS MMDA,                       
    NVL(SUNP_AMT,0) AS SUNP_AMT,           
    NVL(IWOL_GONGGEUM,0) AS IWOL_GONGGEUM,      
    NVL(IWOL_MIJUNGSAN,0) AS IWOL_MIJUNGSAN ,      
    NVL(IWOL_MMDA,0) AS IWOL_MMDA,         
     NVL(IWOL_GONGGEUM_DEP,0) AS IWOL_GONGGEUM_DEP,    
    0 AS SEIB_SUIP2,                
    0 AS TAX_BAEJUNG_IP_AMT2,           
    0 AS SEIB_BANNAB2,                        
    0 AS SEIB_GYEONGJEONG_IB2,             
    0 AS SEIB_GYEONGJEONG_JI2,                        
    0 AS SECHUL_BAEJEONG2,                        
    0 AS SECHUL_HWANSU2,                        
    0 AS SECHUL_JI2,                           
    0 AS SECHUL_BANNAB2,                         
    0 AS SECHUL_GYEONGJEONG_IB2,                       
    0 AS SECHUL_GYEONGJEONG_JI2,                       
    0 AS SEIB_GYULSANBF_IIB2,                        
    0 AS SECHUL_GYULSANBF_IWOL2,                       
    0 AS DEP2,                            
    0 AS MMDA2,                          
    0 AS SUNP_AMT2,              
    0 AS IWOL_GONGGEUM2,           
    0 AS IWOL_MIJUNGSAN2 ,            
    0 AS IWOL_MMDA2,             
     0 AS IWOL_GONGGEUM_DEP2          
 FROM
 (
  SELECT   
      RPT_HOIKYE_C AS HOIGYE_CODE
     ,A.SIGUMGO_ORG_C
     ,SUM(TAX_SUNP_IP_AMT) AS TAX_SUNP_IP_AMT
     ,SUM(SUIP_CHULNAP_BAEJUNG_AMT)
        +SUM(FUND_UNYONG_INT_AMT)
        +SUM(PMNY_DEP_INT_AMT)
        +SUM(BTDEP_INT_AMT)
        +SUM(JICULWO_BAEJUNG_IP_AMT) AS TAX_BAEJUNG_IP_AMT
     ,SUM(GWAON_PROC_JI_AMT) AS GWAON_PROC_JI_AMT
     ,SUM(TAX_IP_CRT_IP_AMT) AS TAX_IP_CRT_IP_AMT
     ,SUM(TAX_IP_CRT_JI_AMT) AS TAX_IP_CRT_JI_AMT
     ,SUM(BIZPLC_BAEJUNG_JI_AMT) AS BIZPLC_BAEJUNG_JI_AMT
     ,SUM(BIZPLC_GAM_BAEJUNG_IP_AMT) AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,SUM(TAXO_FUND_BAEJUNG_JI_AMT)
     +SUM(TAXO_HNDO_BAEJUNG_JI_AMT)
     +SUM(TAXO_FUND_GETBK_JI_AMT)
     +SUM(TAXO_HNDO_JICHUL_JI_AMT)
     +SUM(TAXO_HNDO_GETBK_JI_AMT)  AS TAXO_JI_AMT
    ,SUM(TAXO_RTRN_AMT) AS TAXO_RTRN_AMT
    ,SUM(KWA_CRRC_IP_AMT) AS KWA_CRRC_IP_AMT
    ,SUM(KWA_CRRC_JI_AMT) AS KWA_CRRC_JI_AMT
    ,SUM(GA_IWOL_IP_AMT) AS GA_IWOL_IP_AMT
    ,SUM(GA_IWOL_JI_AMT) AS GA_IWOL_JI_AMT
    ,SUM(DEP_MK_JI_AMT) AS DEP_MK_JI_AMT
    ,SUM(MR_FUND_AMT) AS MMDA
    ,SUM(DEP_HJI_AMT) AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
    ,SUM(GAM_BAEJUNG_JI_AMT) GAM_BAEJUNG_JI_AMT
  FROM RPT_TXIO_DDAC_TAB A, AC_LIST B
  WHERE  A.SGG_ACNO(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.BAS_DT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.BAS_DT(+) BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20251031'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  and A.FIL_100_CTNT5 = '11000080900000199'
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C
 )