-- 세입월계표의 이월금액을 분석하기 항목별(공금예금, 정기예금), 회계별(99, YY)
SELECT
    *
FROM RPT_DANGSEIPJOJEONG 
WHERE JOJEONG_GUBUN = 1
AND GEUMGO_CODE = 28
AND GUNGU_CODE = 0
AND JIBGYE_CODE = 103000
AND SUNAPIL BETWEEN '20250101' AND '20251231'

-----------------------------------------------------


SELECT
    *
FROM RPT_DANGSEIPJOJEONG 
WHERE JOJEONG_GUBUN = 1
AND GEUMGO_CODE = 28
AND JUSEOK LIKE '%이월%'
AND SUNAPIL BETWEEN '20250101' AND '20251231'
ORDER BY GEUMGO_CODE, GUNGU_CODE, JIBGYE_CODE