SELECT
 A.GYEJWA_NM AS GYEJWA_NM
 , A.ACNO
 , A.GUBUN_NM
 , SUM(NVL(TO_NUMBER(A.JEONHANDO_BAEJEONG), 0)) AS JEONHANDO_BAEJEONG
 , SUM(NVL(TO_NUMBER(A.JEONHANDO_HWANSU), 0)) AS JEONHANDO_HWANSU
 , SUM(NVL(TO_NUMBER(A.DANGHANDO_BAEJEONG), 0)) AS DANGHANDO_BAEJEONG
 , SUM(NVL(TO_NUMBER(A.DANGHANDO_HWANSU), 0)) AS DANGHANDO_HWANSU
 , SUM(NVL(TO_NUMBER(A.JEONSECHUL_JICHUL), 0)) AS JEONSECHUL_JICHUL
 , SUM(NVL(TO_NUMBER(A.JEONSECHUL_BANNAB), 0)) AS JEONSECHUL_BANNAB
 , SUM(NVL(TO_NUMBER(A.DANGSECHUL_JICHUL), 0)) AS DANGSECHUL_JICHUL
 , SUM(NVL(TO_NUMBER(A.DANGSECHUL_BANNAB), 0)) AS DANGSECHUL_BANNAB
FROM (

  WITH DEPT_GYEJWA AS (
 SELECT SGG_ACNO
   FROM
 (
   SELECT ROWNUM AS R_NUM
     , A.*
     FROM 
   (
       SELECT SGM.SIGUMGO_ACNO AS SGG_ACNO
      FROM (
   
       SELECT ADM.SGG_ACNO
      FROM SFI_ORG_DEPT_C_MNG ODC
     INNER JOIN SFI_ORG_BY_DEPT_MNG OBD
       ON OBD.PADM_STD_ORG_C = ODC.PADM_STD_ORG_C
     INNER JOIN RPT_JEONJA_AC_BY_DEPT_MNG ADM
       ON ADM.GEUMGO_CODE = '28'
         AND ADM.SL_GMGO_DEPT_C = OBD.G_CC_DEPT_C
         AND (ADM.HOIKYE_YEAR = '2024' OR ADM.HOIKYE_YEAR = '9999')
         AND (ADM.USE_G = '1' OR ADM.USE_G = '2')
         AND ADM.DEL_YN = 'N'
      WHERE ('all'  = 'all'            OR ODC.REP_ORG_C = 'all') 
        AND ('all'  = 'all'            OR OBD.PADM_STD_ORG_C = 'all')
        AND ('all'  = 'all'           OR ADM.SL_GMGO_DEPT_C = 'all')
        AND ODC.DEL_YN = 'N'
      GROUP BY ADM.SGG_ACNO
        
    ) ADM
     INNER JOIN ACL_SIGUMGO_MAS_SUB SGM
       ON SIGUMGO_ORG_C = '28'
         AND SGM.SIGUMGO_ACNO = ADM.SGG_ACNO
     WHERE 1=1
       AND TO_CHAR(SGM.SIGUMGO_HOIKYE_C) = '1'
     GROUP BY SGM.SIGUMGO_ACNO
     ORDER BY SGM.SIGUMGO_ACNO
   ) A
   WHERE ROWNUM <= '2000'
 ) X
 WHERE X.R_NUM >= '0'
   AND (('02800001100000024' = 'all' AND SUBSTR(SGG_ACNO, 7, 4) <> '0110' ) OR  SGG_ACNO = '02800001100000024')
  )
  , GYEJWA AS (
  
  
    SELECT
      FIL_100_CTNT2 AS ACNO
      , SIGUMGO_AC_B AS ACB
      , SIGUMGO_AGE_AC_G AS AGE
      , SIGUMGO_AC_G AS ACG
      , SIGUMGO_AC_NM AS GYEJWA_NM
    FROM ACL_SIGUMGO_MAS
    WHERE ICH_SIGUMGO_HOIKYE_C = 1
      AND SIGUMGO_HOIKYE_YR = TO_NUMBER('2024')
      AND ( 
  FIL_100_CTNT2 IN (SELECT SGG_ACNO FROM DEPT_GYEJWA)
    OR
  (
   SIGUMGO_AGE_AC_G = 3
  AND 
   FUND_BAEJUNG_SIGUMGO_MNG_NO IN (SELECT SGG_ACNO FROM DEPT_GYEJWA)
  )
    )
      AND MNG_NO = 1      
  )
  , SLV AS (
    SELECT
        TRXDT
        , GISDT
        , FIL_100_CTNT5 AS ACNO
        , (SELECT GYEJWA_NM FROM GYEJWA WHERE ACNO = FIL_100_CTNT5) AS GYEJWA_NM
        , (SELECT ACB FROM GYEJWA WHERE ACNO = FIL_100_CTNT5) AS ACB
        , (SELECT ACG FROM GYEJWA WHERE ACNO = FIL_100_CTNT5) AS ACG
        , (SELECT AGE FROM GYEJWA WHERE ACNO = FIL_100_CTNT5) AS AGE
        , 'JG' AS G
        , LPAD(SIGUMGO_TRX_G, 2, '0') || LPAD(SIGUMGO_IP_TRX_G, 2, '0') || LPAD(SIGUMGO_JI_TRX_G, 2, '0') AS GG
        , SUM( DECODE(CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1) * DECODE(IPJI_G, 2, -1, 1) * TRAMT ) AS AMT
      FROM ACL_SIGUMGO_SLV
      WHERE FIL_100_CTNT5 IN (SELECT ACNO FROM GYEJWA)
      AND TRXDT >= '2024' || '0101'
      GROUP BY TRXDT, GISDT, FIL_100_CTNT5, LPAD(SIGUMGO_TRX_G, 2, '0') || LPAD(SIGUMGO_IP_TRX_G, 2, '0') || LPAD(SIGUMGO_JI_TRX_G, 2, '0')

      UNION ALL

      SELECT
        TRXDT
        , GISDT
        , SIGUMGO_ACNO AS ACNO
        , (SELECT GYEJWA_NM FROM GYEJWA WHERE ACNO = SIGUMGO_ACNO) AS GYEJWA_NM
        , (SELECT ACB FROM GYEJWA WHERE ACNO = SIGUMGO_ACNO) AS ACB
        , (SELECT ACG FROM GYEJWA WHERE ACNO = SIGUMGO_ACNO) AS ACG
        , (SELECT AGE FROM GYEJWA WHERE ACNO = SIGUMGO_ACNO) AS AGE
        , 'HD' AS G
        , TO_CHAR(SIGUMGO_TRX_G) AS GG
        , SUM( DECODE(CRT_CAN_G, 1, -1, 2, -1, 33, -1, 1) * DECODE(IPJI_G, 2, -1, 1) * TRAMT ) AS AMT
      FROM ACL_SGGHANDO_SLV
      WHERE SIGUMGO_ACNO IN (SELECT ACNO FROM GYEJWA)
      AND TRXDT >= '2024' || '0101'
      GROUP BY TRXDT, GISDT, SIGUMGO_ACNO, SIGUMGO_TRX_G
  )

  -- 본청 => 본청지출, 일상경비
  SELECT 
    GYEJWA_NM
    , ACNO
    , '1' AS GUBUN_NM
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('670090', '91') THEN AMT * -1 ELSE 0 END ) AS JEONHANDO_BAEJEONG
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('179000', '45') THEN AMT * 1 ELSE 0 END ) AS JEONHANDO_HWANSU
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('670090', '91') THEN AMT * -1 ELSE 0 END ) AS DANGHANDO_BAEJEONG
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('179000', '45') THEN AMT * 1 ELSE 0 END ) AS DANGHANDO_HWANSU
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('670090', '670092') THEN AMT * -1 ELSE 0 END ) AS JEONSECHUL_JICHUL
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('179000', '179200') THEN AMT * 1 ELSE 0 END ) AS JEONSECHUL_BANNAB
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('670090', '670092') THEN AMT * -1 ELSE 0 END ) AS DANGSECHUL_JICHUL
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('179000', '179200') THEN AMT * 1 ELSE 0 END ) AS DANGSECHUL_BANNAB
  FROM SLV
  WHERE AGE = 1
  GROUP BY GYEJWA_NM, ACNO

  UNION ALL

  -- 본청외 => 사업소, 일상경비 손
  SELECT 
    GYEJWA_NM
    , ACNO
    , '2' AS GUBUN_NM
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('90') THEN AMT * -1 ELSE 0 END ) AS JEONHANDO_BAEJEONG
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('42') THEN AMT * 1 ELSE 0 END ) AS JEONHANDO_HWANSU
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('90') THEN AMT * -1 ELSE 0 END ) AS DANGHANDO_BAEJEONG
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('42') THEN AMT * 1 ELSE 0 END ) AS DANGHANDO_HWANSU
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('670091', '670093') THEN AMT * -1 ELSE 0 END ) AS JEONSECHUL_JICHUL
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('179100', '179300') THEN AMT * 1 ELSE 0 END ) AS JEONSECHUL_BANNAB
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('670091', '670093') THEN AMT * -1 ELSE 0 END ) AS DANGSECHUL_JICHUL
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('179100', '179300') THEN AMT * 1 ELSE 0 END ) AS DANGSECHUL_BANNAB
  FROM SLV
  WHERE AGE = 1
  GROUP BY GYEJWA_NM, ACNO

  UNION ALL

  -- 자계좌 
  SELECT 
    GYEJWA_NM
    , ACNO
    , '0' AS GUBUN_NM
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('40', '41', '91') THEN AMT
        ELSE 0 END ) AS JEONHANDO_BAEJEONG
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('45', '92', '95') THEN AMT * -1 ELSE 0 END ) AS JEONHANDO_HWANSU
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('40', '41', '91') THEN AMT
        ELSE 0 END ) AS DANGHANDO_BAEJEONG
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('45', '92', '95') THEN AMT * -1 ELSE 0 END ) AS DANGHANDO_HWANSU
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('670091', '670092', '670093') THEN AMT * -1 ELSE 0 END ) AS JEONSECHUL_JICHUL
    , SUM ( CASE WHEN GISDT < '20241231' AND GG IN ('179100', '179200', '179300') THEN AMT * 1 ELSE 0 END ) AS JEONSECHUL_BANNAB
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('670091', '670092', '670093') THEN AMT * -1 ELSE 0 END ) AS DANGSECHUL_JICHUL
    , SUM ( CASE WHEN GISDT = '20241231' AND GG IN ('179100', '179200', '179300') THEN AMT * 1 ELSE 0 END ) AS DANGSECHUL_BANNAB
  FROM SLV
  WHERE AGE IN (2, 3)
  GROUP BY GYEJWA_NM, ACNO
-- 거래내역이 없어도 목록이 보이도록 처리 
  UNION ALL
  SELECT 
    GYEJWA_NM
    ,ACNO
    ,'1' AS GUBUN_NM
    , 0 AS JEONHANDO_BAEJEONG
    , 0 AS JEONHANDO_HWANSU
    , 0 AS DANGHANDO_BAEJEONG
    , 0 AS DANGHANDO_HWANSU
    , 0 AS JEONSECHUL_JICHUL
    , 0 AS JEONSECHUL_BANNAB
    , 0 AS DANGSECHUL_JICHUL
    , 0 AS DANGSECHUL_BANNAB 
  FROM GYEJWA
  WHERE AGE = 1
  GROUP BY GYEJWA_NM, ACNO
  UNION ALL
  SELECT 
    GYEJWA_NM
    ,ACNO
    ,'2' AS GUBUN_NM
    , 0 AS JEONHANDO_BAEJEONG
    , 0 AS JEONHANDO_HWANSU
    , 0 AS DANGHANDO_BAEJEONG
    , 0 AS DANGHANDO_HWANSU
    , 0 AS JEONSECHUL_JICHUL
    , 0 AS JEONSECHUL_BANNAB
    , 0 AS DANGSECHUL_JICHUL
    , 0 AS DANGSECHUL_BANNAB 
  FROM GYEJWA
  WHERE AGE = 1
  GROUP BY GYEJWA_NM, ACNO
UNION ALL
  SELECT 
    GYEJWA_NM
    ,ACNO
    ,'0' AS GUBUN_NM
    , 0 AS JEONHANDO_BAEJEONG
    , 0 AS JEONHANDO_HWANSU
    , 0 AS DANGHANDO_BAEJEONG
    , 0 AS DANGHANDO_HWANSU
    , 0 AS JEONSECHUL_JICHUL
    , 0 AS JEONSECHUL_BANNAB
    , 0 AS DANGSECHUL_JICHUL
    , 0 AS DANGSECHUL_BANNAB 
  FROM GYEJWA
  WHERE AGE IN (2,3)
  GROUP BY GYEJWA_NM, ACNO
  UNION ALL
  SELECT 
    GYEJWA_NM
    ,ACNO
    ,'3' AS GUBUN_NM
    , 0 AS JEONHANDO_BAEJEONG
    , 0 AS JEONHANDO_HWANSU
    , 0 AS DANGHANDO_BAEJEONG
    , 0 AS DANGHANDO_HWANSU
    , 0 AS JEONSECHUL_JICHUL
    , 0 AS JEONSECHUL_BANNAB
    , 0 AS DANGSECHUL_JICHUL
    , 0 AS DANGSECHUL_BANNAB 
  FROM GYEJWA
  WHERE ACG = 0
  GROUP BY GYEJWA_NM, ACNO
) A
GROUP BY GYEJWA_NM, ACNO, GUBUN_NM
ORDER BY ACNO, GUBUN_NM