SELECT
     TRXDT,
     GJDT,
     CASE WHEN SUNP_SIGUMGO_HOIKYE_SMOK_C = 4000 AND SUNP_ICH_SIGUMGO_GUN_GU_C = 260
          THEN 0
          WHEN SUNP_ICH_SIGUMGO_GUN_GU_C IN (40,50,55,70,80,90,810,830,840,850,210,220,230)
          THEN TO_NUMBER(CONCAT('7',SUNP_ICH_SIGUMGO_GUN_GU_C))
          WHEN SUNP_ICH_SIGUMGO_GUN_GU_C = 100 AND SUNP_SIGUMGO_HOIKYE_SMOK_C = 9330
          THEN TO_NUMBER(CONCAT('7',SUNP_ICH_SIGUMGO_GUN_GU_C))
          ELSE SUNP_ICH_SIGUMGO_GUN_GU_C
     END AS GUNGU_CODE,
     CASE WHEN SIGUMGO_HOIKYE_YR = 9999 THEN SUBSTR(GJDT, 1, 4) ELSE SIGUMGO_HOIKYE_YR END AS HOIGYE_YEAR,
     DECODE(NEW_GU_YR_G, 0, 1, NEW_GU_YR_G) AS YEAR_GUBUN,
     26 AS BANK_GUBUN,
     1 AS JOJEONG_GUBUN,
     IPJI_G AS IPJI_GUBUN,
     TO_NUMBER(
          CASE WHEN SUNP_SIGUMGO_HOIKYE_SMOK_C = 4000 AND SUNP_ICH_SIGUMGO_GUN_GU_C = 260
               THEN '103000'
               
               WHEN 22 < ICH_SIGUMGO_HOIKYE_C AND ICH_SIGUMGO_HOIKYE_C < 44
               THEN CONCAT('21', CONCAT(ICH_SIGUMGO_HOIKYE_C, '00') )
               WHEN ICH_SIGUMGO_HOIKYE_C = 75
               THEN CONCAT('22', CONCAT(ICH_SIGUMGO_HOIKYE_C, '00') )
               WHEN SUNP_SIGUMGO_HOIKYE_SMOK_C IN (3000,4000)
               THEN CONCAT('10', SUNP_SIGUMGO_HOIKYE_SMOK_C)
               
               WHEN SUNP_SIGUMGO_HOIKYE_SMOK_C IN (10,20)
               THEN CONCAT('2000', SUNP_SIGUMGO_HOIKYE_SMOK_C)
               WHEN SUNP_SIGUMGO_HOIKYE_SMOK_C NOT IN (10,20,3000,4000)
               THEN CONCAT('20', SUNP_SIGUMGO_HOIKYE_SMOK_C)
          END
     ) AS JIBGYE_CODE,
     DECODE(CRT_CAN_G,1,-1,2,-1,33,-1,1) * EDTAX_AMT AS GYOYUKSE_AMT,
     DECODE(CRT_CAN_G,1,-1,2,-1,33,-1,1) * NTTAX_AMT AS NONGTEUKSE_AMT,
     0 AS JIBANGSE_CNT,
     DECODE(CRT_CAN_G,1,-1,2,-1,33,-1,1) * MTAX_AMT AS JIBANGSE_AMT,
     0 AS SEWOI_CNT,
     DECODE(CRT_CAN_G,1,-1,2,-1,33,-1,1) * TAX_OI_SUIP_AMT AS SEWOI_AMT,
     0 AS SUNAP_CNT,
     0 AS SUNAP_AMT,
     CMMT_CTNT AS JUSEOK,
     '' AS SEIP_GYEJWANO,
     SUBSTR(TRXDT, 4, 5) AS SEQ_NO, -- 추후 SEQ관련 바이트작업 필요
     28 AS GEUMGO_CODE
FROM ACL_SIGUMGO_SLV
WHERE 1=1
  AND TRXDT BETWEEN :1  AND :2 
  AND SIGUMGO_ORG_C = 28 
  AND SIGUMGO_TRX_G IN (13) -- 추후 63번 코드 추가 필요, OriginalSql = INSERT INTO RPT_DANGSEIPJOJEONG
(
     KEORAEIL,
     SUNAPIL,
     GUNGU_CODE,
     HOIGYE_YEAR,
     YEAR_GUBUN,
     BANK_GUBUN,
     JOJEONG_GUBUN,
     IPJI_GUBUN,
     JIBGYE_CODE,
     GYOYUKSE_AMT,
     NONGTEUKSE_AMT,
     JIBANGSE_CNT,
     JIBANGSE_AMT,
     SEWOI_CNT,
     SEWOI_AMT,
     SUNAP_CNT,
     SUNAP_AMT,
     JUSEOK,
     SEIP_GYEJWANO,
     SEQ_NO,
     GEUMGO_CODE
)

------------------------------

SELECT
     TRXDT,
     GJDT,
     CASE WHEN SUNP_SIGUMGO_HOIKYE_SMOK_C = 4000 AND SUNP_ICH_SIGUMGO_GUN_GU_C = 260
          THEN 0
          WHEN SUNP_ICH_SIGUMGO_GUN_GU_C IN (40,50,55,70,80,90,810,830,840,850,210,220,230)
          THEN TO_NUMBER(CONCAT('7',SUNP_ICH_SIGUMGO_GUN_GU_C))
          WHEN SUNP_ICH_SIGUMGO_GUN_GU_C = 100 AND SUNP_SIGUMGO_HOIKYE_SMOK_C = 9330
          THEN TO_NUMBER(CONCAT('7',SUNP_ICH_SIGUMGO_GUN_GU_C))
          ELSE SUNP_ICH_SIGUMGO_GUN_GU_C
     END AS GUNGU_CODE,
     CASE WHEN SIGUMGO_HOIKYE_YR = 9999 THEN SUBSTR(GJDT, 1, 4) ELSE SIGUMGO_HOIKYE_YR END AS HOIGYE_YEAR,
     DECODE(NEW_GU_YR_G, 0, 1, NEW_GU_YR_G) AS YEAR_GUBUN,
     26 AS BANK_GUBUN,
     1 AS JOJEONG_GUBUN,
     IPJI_G AS IPJI_GUBUN,
     TO_NUMBER(
          CASE WHEN SUNP_SIGUMGO_HOIKYE_SMOK_C = 4000 AND SUNP_ICH_SIGUMGO_GUN_GU_C = 260
               THEN '103000'
               
               WHEN 22 < ICH_SIGUMGO_HOIKYE_C AND ICH_SIGUMGO_HOIKYE_C < 44
               THEN CONCAT('21', CONCAT(ICH_SIGUMGO_HOIKYE_C, '00') )
               WHEN ICH_SIGUMGO_HOIKYE_C = 75
               THEN CONCAT('22', CONCAT(ICH_SIGUMGO_HOIKYE_C, '00') )
               WHEN SUNP_SIGUMGO_HOIKYE_SMOK_C IN (3000,4000)
               THEN CONCAT('10', SUNP_SIGUMGO_HOIKYE_SMOK_C)
               
               WHEN SUNP_SIGUMGO_HOIKYE_SMOK_C IN (10,20)
               THEN CONCAT('2000', SUNP_SIGUMGO_HOIKYE_SMOK_C)
               WHEN SUNP_SIGUMGO_HOIKYE_SMOK_C NOT IN (10,20,3000,4000)
               THEN CONCAT('20', SUNP_SIGUMGO_HOIKYE_SMOK_C)
          END
     ) AS JIBGYE_CODE,
     DECODE(CRT_CAN_G,1,-1,2,-1,33,-1,1) * EDTAX_AMT AS GYOYUKSE_AMT,
     DECODE(CRT_CAN_G,1,-1,2,-1,33,-1,1) * NTTAX_AMT AS NONGTEUKSE_AMT,
     0 AS JIBANGSE_CNT,
     DECODE(CRT_CAN_G,1,-1,2,-1,33,-1,1) * MTAX_AMT AS JIBANGSE_AMT,
     0 AS SEWOI_CNT,
     DECODE(CRT_CAN_G,1,-1,2,-1,33,-1,1) * TAX_OI_SUIP_AMT AS SEWOI_AMT,
     0 AS SUNAP_CNT,
     0 AS SUNAP_AMT,
     CMMT_CTNT AS JUSEOK,
     '' AS SEIP_GYEJWANO,
     ROWNUM AS SEQ_NO, -- 추후 SEQ관련 바이트작업 필요
     28 AS GEUMGO_CODE
FROM ACL_SIGUMGO_SLV
WHERE 1=1
  AND TRXDT BETWEEN 20260108 AND 20260108
  AND SIGUMGO_ORG_C = 28 
  AND SIGUMGO_TRX_G IN (13) 
  AND SUNP_SIGUMGO_HOIKYE_SMOK_C != 0