    SELECT 
        A.SUNP_ICH_SIGUMGO_GUN_GU_C, 
        A.SUNP_SIGUMGO_HOIKYE_SMOK_C, 
        A.ICH_SIGUMGO_HOIKYE_C,
        CONCAT('20', A.SUNP_SIGUMGO_HOIKYE_SMOK_C) AS JIBGYE_CODE,
        COUNT(A.ICH_SIGUMGO_HOIKYE_C) AS CNT
    FROM ACL_SIGUMGO_SLV A
    WHERE A.TRXDT BETWEEN '20250101' AND '20251231'
    AND A.SIGUMGO_ORG_C = 28
    AND A.SIGUMGO_TRX_G IN (13)
    AND NOT (A.SUNP_SIGUMGO_HOIKYE_SMOK_C = 4000 AND A.SUNP_ICH_SIGUMGO_GUN_GU_C = 260)
    AND NOT (22 < A.ICH_SIGUMGO_HOIKYE_C AND A.ICH_SIGUMGO_HOIKYE_C < 44)
    AND NOT (A.ICH_SIGUMGO_HOIKYE_C = 75)
    AND A.SUNP_SIGUMGO_HOIKYE_SMOK_C NOT IN (10,20,3000,4000)
    GROUP BY A.SUNP_ICH_SIGUMGO_GUN_GU_C, A.SUNP_SIGUMGO_HOIKYE_SMOK_C, A.ICH_SIGUMGO_HOIKYE_C

------------------------------
WITH SLV AS (
    SELECT 
        A.SUNP_ICH_SIGUMGO_GUN_GU_C,
        A.SUNP_SIGUMGO_HOIKYE_SMOK_C,
        A.ICH_SIGUMGO_HOIKYE_C
    FROM ACL_SIGUMGO_SLV A
    WHERE A.TRXDT BETWEEN '20260101' AND '20260108'
    AND A.SIGUMGO_ORG_C = 28
    AND A.SIGUMGO_TRX_G IN (13)
)
SELECT 
A.SUNP_ICH_SIGUMGO_GUN_GU_C,
A.SUNP_SIGUMGO_HOIKYE_SMOK_C,
A.ICH_SIGUMGO_HOIKYE_C,
 TO_NUMBER(
    CASE WHEN A.SUNP_SIGUMGO_HOIKYE_SMOK_C = 4000 AND A.SUNP_ICH_SIGUMGO_GUN_GU_C = 260
    THEN '103000'
    
    WHEN 22 < A.ICH_SIGUMGO_HOIKYE_C AND A.ICH_SIGUMGO_HOIKYE_C < 44
    THEN CONCAT('21', CONCAT(A.ICH_SIGUMGO_HOIKYE_C, '00'))
    
    WHEN A.ICH_SIGUMGO_HOIKYE_C = 75
    THEN CONCAT('22', CONCAT(A.ICH_SIGUMGO_HOIKYE_C, '00'))
    
    WHEN A.SUNP_SIGUMGO_HOIKYE_SMOK_C IN (3000,4000)
    THEN CONCAT('10', A.SUNP_SIGUMGO_HOIKYE_SMOK_C)
    
    WHEN A.SUNP_SIGUMGO_HOIKYE_SMOK_C IN (10,20)
    THEN CONCAT('2000', A.SUNP_SIGUMGO_HOIKYE_SMOK_C)
    
    WHEN A.SUNP_SIGUMGO_HOIKYE_SMOK_C NOT IN (10,20,3000,4000)
    THEN CONCAT('20', A.SUNP_SIGUMGO_HOIKYE_SMOK_C)
    END
    ) AS JIBGYE_CODE
FROM SLV A
WHERE A.TRXDT BETWEEN '20260101' AND '20260108'
AND A.SIGUMGO_ORG_C = 28
AND A.SIGUMGO_TRX_G IN (13)