-- 저축성예금

SELECT COUNT(*) AS CNT, SUM(JANAEK) AS J
 FROM RPT_UNYONG_JAN
WHERE KIJUNIL =  (SELECT BIZ_DT FROM MAP_JOB_DATE WHERE DW_BAS_DDT = '20231231')
AND GONGGEUM_GYEJWA IN (
SELECT DISTINCT GONGGEUM_GYEJWA
FROM RPT_GONGGEUM_JAN
WHERE GEUMGO_CODE = 28
AND GUNGU_CODE = 170
AND KEORAEIL = '20231231'
AND (GONGGEUM_GYEJWA LIKE '%99' OR GONGGEUM_GYEJWA LIKE '%23')
)

-- 공금예금잔액

 SELECT COUNT(*) AS CNT, SUM(JANAEK) AS J FROM RPT_GONGGEUM_JAN
WHERE GONGGEUM_GYEJWA IN (
SELECT DISTINCT GONGGEUM_GYEJWA
FROM RPT_GONGGEUM_JAN
WHERE GEUMGO_CODE = 28
AND GUNGU_CODE = 170
AND KEORAEIL = '20231231'
AND (GONGGEUM_GYEJWA LIKE '%99' OR GONGGEUM_GYEJWA LIKE '%23')
)
AND KEORAEIL = '20231231'

-- 세입세출외현금잔액
SELECT COUNT(*) AS CNT, SUM(JANAEK) AS J FROM RPT_GONGGEUM_JAN
WHERE GONGGEUM_GYEJWA IN (
SELECT DISTINCT GONGGEUM_GYEJWA
FROM RPT_GONGGEUM_JAN
WHERE GEUMGO_CODE = 28
AND GUNGU_CODE = 170
AND KEORAEIL = '20231231'
AND (GONGGEUM_GYEJWA LIKE '%99' OR GONGGEUM_GYEJWA LIKE '%23')
AND GONGGEUM_GYEJWA LIKE '0281708060%'
)
AND KEORAEIL = '20231231'

-- 업무처리현황

-- 구세(세외수입)금액

SELECT
 SUM(A.BON_CNT) BON_CNT,
 SUM(A.BON_SUM) BON_SUM,
 SUM(A.SEW_CNT) SEW_CNT,
 SUM(A.SEW_SUM) SEW_SUM
 FROM
(
  SELECT 
 SUM(A.BON_CNT) BON_CNT,
 SUM(A.BON_SUM) BON_SUM,
 SUM(A.SEW_CNT) SEW_CNT,
 SUM(A.SEW_SUM) SEW_SUM
FROM
(
SELECT 
  CASE WHEN (BONSE_AMT > 0 AND BONSE_CNT > 0) THEN BONSE_CNT 
  WHEN (BONSE_AMT > 0 AND BONSE_CNT = 0) THEN 1
  ELSE 0 END BON_CNT,
BONSE_AMT BON_SUM,
CASE WHEN  SEWOI_CNT > 0 THEN SEWOI_CNT ELSE 0 END SEW_CNT,
SEWOI_AMT SEW_SUM
FROM
  RPT_SUNAP_JIBGYE
WHERE
    GEORAE_GUBUN IN (1,2,4)
AND
  GEUMGO_CODE = 28
AND
  GUNGU_CODE = 170
AND
  SUNAPIL BETWEEN '20230101' AND '20231231'
AND
  JIBGYE_CODE = 104000
) A
  UNION ALL
  SELECT 
 SUM(A.BON_CNT) BON_CNT,
 SUM(A.BON_SUM) BON_SUM,
 SUM(A.SEW_CNT) SEW_CNT,
 SUM(A.SEW_SUM) SEW_SUM
FROM
(  
SELECT 
  CASE WHEN  IPJI_GUBUN = 2 AND JIBANGSE_AMT > 0  THEN -1 
  WHEN IPJI_GUBUN = 1 AND JIBANGSE_AMT > 0 THEN 1
  ELSE 0 END   BON_CNT,
  CASE WHEN  IPJI_GUBUN = 2 THEN JIBANGSE_AMT*-1 ELSE JIBANGSE_AMT END BON_SUM,
  
 CASE WHEN  IPJI_GUBUN = 2 AND SEWOI_AMT > 0  THEN -1 
  WHEN IPJI_GUBUN = 1 AND SEWOI_AMT > 0 THEN 1
  ELSE 0 END   SEW_CNT,
 CASE WHEN  IPJI_GUBUN = 2 THEN SEWOI_AMT*-1 ELSE SEWOI_AMT END SEW_SUM
FROM
  RPT_DANGSEIPJOJEONG
WHERE
    JOJEONG_GUBUN = 1
AND
  GEUMGO_CODE = 28
AND
  GUNGU_CODE = 170
AND
  SUNAPIL BETWEEN '20230101' AND '20231231'
AND
  JIBGYE_CODE = 104000  
) A
) A

-- 시세(세외수입)금액

    SELECT
SUM(A.BON_CNT) BON_CNT,
SUM(A.BON_SUM) BON_SUM,
SUM(A.SEW_CNT) SEW_CNT,
SUM(A.SEW_SUM) SEW_SUM
FROM
(
 SELECT 
SUM(A.BON_CNT) BON_CNT,
SUM(A.BON_SUM) BON_SUM,
SUM(A.SEW_CNT) SEW_CNT,
SUM(A.SEW_SUM) SEW_SUM
FROM
(
SELECT 
 CASE WHEN (BONSE_AMT > 0 AND BONSE_CNT > 0) THEN BONSE_CNT 
 WHEN (BONSE_AMT > 0 AND BONSE_CNT = 0) THEN 1
 ELSE 0 END BON_CNT,
BONSE_AMT BON_SUM,
 CASE WHEN (SEWOI_AMT > 0 AND SEWOI_CNT > 0) THEN SEWOI_CNT 
 WHEN (SEWOI_AMT > 0 AND SEWOI_CNT = 0) THEN 1
ELSE 0 END SEW_CNT,
SEWOI_AMT SEW_SUM
FROM
 RPT_SUNAP_JIBGYE
WHERE
  GEORAE_GUBUN IN (1,2,4)
AND
 GEUMGO_CODE = 28
AND
 GUNGU_CODE = 170
AND
 SUNAPIL BETWEEN '20230101' AND '20231231'
AND
 JIBGYE_CODE = 103000
) A
 UNION ALL
 SELECT 
SUM(A.BON_CNT) BON_CNT,
SUM(A.BON_SUM) BON_SUM,
SUM(A.SEW_CNT) SEW_CNT,
SUM(A.SEW_SUM) SEW_SUM
FROM
( 
SELECT 
 CASE WHEN IPJI_GUBUN = 2 AND JIBANGSE_AMT > 0 THEN -1 
 WHEN IPJI_GUBUN = 1 AND JIBANGSE_AMT > 0 THEN 1
 ELSE 0 END  BON_CNT,
 CASE WHEN IPJI_GUBUN = 2 THEN JIBANGSE_AMT*-1 ELSE JIBANGSE_AMT END BON_SUM,
 
CASE WHEN IPJI_GUBUN = 2 AND SEWOI_AMT > 0 THEN -1 
 WHEN IPJI_GUBUN = 1 AND SEWOI_AMT > 0 THEN 1
 ELSE 0 END  SEW_CNT,
CASE WHEN IPJI_GUBUN = 2 THEN SEWOI_AMT*-1 ELSE SEWOI_AMT END SEW_SUM
FROM
 RPT_DANGSEIPJOJEONG
WHERE
  JOJEONG_GUBUN = 1
AND
 GEUMGO_CODE = 28
AND
 GUNGU_CODE = 170
AND
 SUNAPIL BETWEEN '20230101' AND '20231231'
AND
 JIBGYE_CODE = 103000 
) A
) A

-- 배정금액

WITH GONGGEUM_KEORAE AS (
    SELECT
        SIGUMGO_HOIKYE_YR AS HOIGYE_YEAR,
        SIGUMGO_TRX_G AS GEORAE_GUBUN,
        SIGUMGO_IP_TRX_G AS IPGEUM_GEORAE,
        SIGUMGO_JI_TRX_G AS JIGEUB_GEORAE,
        DECODE(IPJI_G, 1, TRAMT, 0) AS IPGEUM_AMT,
        DECODE(IPJI_G, 2, TRAMT, 0) AS JIGEUB_AMT,
        DECODE(CRT_CAN_G, 1, 1, 2, 1, 33, 1, 0) AS JEONGJEONG,
        FIL_100_CTNT5 AS GONGGEUM_GYEJWA,
        GJDT AS KIJUNIL
    FROM ACL_SIGUMGO_SLV
    WHERE 1=1
    AND SIGUMGO_ORG_C = 28
    AND ICH_SIGUMGO_GUN_GU_C = 170
    AND GJDT BETWEEN '20230101' AND '20231231'
),
GYEJWA_INFO AS (
    SELECT
    FIL_100_CTNT5 AS GONGGEUM_GYEJWA,
    ICH_SIGUMGO_HOIKYE_C AS GONGGEUM_HOIGYE_CODE
    FROM ACL_SIGUMGO_MAS
    WHERE 1=1
    AND MNG_NO = 1
    AND SIGUMGO_ORG_C = 28
    AND ICH_SIGUMGO_GUN_GU_C = 170
)
SELECT 
SUM (CASE WHEN BAEJEONG > 0 THEN 1 
          WHEN BAEJEONG = 0 THEN 0
          WHEN BAEJEONG < 0 THEN -1
          END) AS CNT,
SUM(BAEJEONG) AS BJ
FROM (
SELECT 
GEORAE_GUBUN , JIGEUB_GEORAE , IPGEUM_GEORAE , JO,
                       CASE WHEN R_HOIGYE_YEAR = '2023' AND GEORAE_GUBUN = 61 AND JIGEUB_GEORAE = 1
                      THEN JIGEUB_AMT * JO
                      WHEN R_HOIGYE_YEAR = '2023' AND GEORAE_GUBUN = 61 AND JIGEUB_GEORAE = 2
                      THEN  JIGEUB_AMT * JO
                      WHEN R_HOIGYE_YEAR = '2023' AND GEORAE_GUBUN = 14 AND IPGEUM_GEORAE = 6
                      THEN  -IPGEUM_AMT * JO
                      WHEN R_HOIGYE_YEAR = '2023' AND GEORAE_GUBUN = 14 AND IPGEUM_GEORAE = 7
                      THEN  -IPGEUM_AMT * JO
                      WHEN R_HOIGYE_YEAR = '2023' AND GEORAE_GUBUN = 67 AND JIGEUB_GEORAE = 91
                      THEN  JIGEUB_AMT * JO
                      WHEN R_HOIGYE_YEAR = '2023' AND GEORAE_GUBUN = 67 AND JIGEUB_GEORAE = 93
                      THEN  JIGEUB_AMT * JO
                      ELSE 0 END BAEJEONG
FROM (
                       SELECT
                         B.GONGGEUM_HOIGYE_CODE, A.GEORAE_GUBUN, A.IPGEUM_AMT, A.JIGEUB_AMT, C.REF_D_C HOIGYE_GUBUN,
                         A.JIGEUB_GEORAE, A.IPGEUM_GEORAE,
                         A.KIJUNIL ILJA,
                         CASE WHEN A.JEONGJEONG <> 1     THEN 1         ELSE -1        END JO,
                         CASE WHEN A.HOIGYE_YEAR = 9999 THEN TO_NUMBER(SUBSTR(A.KIJUNIL,1,4))
                                   ELSE TO_NUMBER(A.HOIGYE_YEAR) END R_HOIGYE_YEAR              -- 귀속회계년도
                       FROM
                         GONGGEUM_KEORAE A, GYEJWA_INFO B, RPT_CODE_INFO C
                       WHERE 
                         1=1
                         AND A.GONGGEUM_GYEJWA = B.GONGGEUM_GYEJWA
                         AND C.REF_L_C = 100  AND C.REF_M_C = '28' AND C.REF_S_C = 3 AND C.REF_CTNT4 = B.GONGGEUM_HOIGYE_CODE
                       AND B.GONGGEUM_HOIGYE_CODE IN (01)
                       )
)

-- 세출금액

WITH GONGGEUM_KEORAE AS (
    SELECT
        SIGUMGO_ORG_C AS GEUMGO_CODE,
        ICH_SIGUMGO_GUN_GU_C AS GUNGU_CODE,
        ICH_SIGUMGO_HOIKYE_C AS HOIGYE_CODE,
        SIGUMGO_AC_B AS GYEJWA_BUNRYU,
        SIGUMGO_HOIKYE_YR AS HOIGYE_YEAR,
        SIGUMGO_TRX_G AS GEORAE_GUBUN,
        SIGUMGO_IP_TRX_G AS IPGEUM_GEORAE,
        SIGUMGO_JI_TRX_G AS JIGEUB_GEORAE,
        DECODE(IPJI_G, 1, TRAMT, 0) AS IPGEUM_AMT,
        DECODE(IPJI_G, 2, TRAMT, 0) AS JIGEUB_AMT,
        DECODE(CRT_CAN_G, 1, 1, 2, 1, 33, 1, 0) AS JEONGJEONG,
        FIL_100_CTNT5 AS GONGGEUM_GYEJWA,
        GJDT AS KIJUNIL
    FROM ACL_SIGUMGO_SLV
    WHERE 1=1
    AND SIGUMGO_ORG_C = 28
    AND ICH_SIGUMGO_GUN_GU_C = 170
    AND GJDT LIKE '2023%'
)
SELECT COUNT(*) AS CNT, SUM(JIGEUB_AMT*DECODE(JEONGJEONG,1,-1,1)) AS JA
 FROM GONGGEUM_KEORAE
WHERE 1=1
AND GEORAE_GUBUN = 67
AND HOIGYE_CODE = 1
AND GYEJWA_BUNRYU = 10

-- 반납금액
WITH GONGGEUM_KEORAE AS (
    SELECT
        SIGUMGO_ORG_C AS GEUMGO_CODE,
        ICH_SIGUMGO_GUN_GU_C AS GUNGU_CODE,
        ICH_SIGUMGO_HOIKYE_C AS HOIGYE_CODE,
        SIGUMGO_AC_B AS GYEJWA_BUNRYU,
        SIGUMGO_HOIKYE_YR AS HOIGYE_YEAR,
        SIGUMGO_TRX_G AS GEORAE_GUBUN,
        SIGUMGO_IP_TRX_G AS IPGEUM_GEORAE,
        SIGUMGO_JI_TRX_G AS JIGEUB_GEORAE,
        DECODE(IPJI_G, 1, TRAMT, 0) AS IPGEUM_AMT,
        DECODE(IPJI_G, 2, TRAMT, 0) AS JIGEUB_AMT,
        DECODE(CRT_CAN_G, 1, 1, 2, 1, 33, 1, 0) AS JEONGJEONG,
        FIL_100_CTNT5 AS GONGGEUM_GYEJWA,
        GJDT AS KIJUNIL
    FROM ACL_SIGUMGO_SLV
    WHERE 1=1
    AND SIGUMGO_ORG_C = 28
    AND ICH_SIGUMGO_GUN_GU_C = 170
    AND GJDT LIKE '2023%'
)
 SELECT 
SUM ( CASE WHEN JEONGJEONG = 1 THEN -1 ELSE 1 END) AS CNT,
SUM(CASE WHEN JEONGJEONG = 1 THEN -IPGEUM_AMT ELSE IPGEUM_AMT END) AS IA
FROM GONGGEUM_KEORAE
WHERE KIJUNIL LIKE '2023%'
AND GEUMGO_CODE = 28
AND GUNGU_CODE = 170
AND GEORAE_GUBUN = 17
AND HOIGYE_YEAR = '2023'
AND GONGGEUM_GYEJWA = '02817001100000023'
 

 ----------------------------------------------------------

 -- 과오납금 업무

-- 구세(세외수입)금액

    SELECT
SUM(A.BON_CNT) BON_CNT,
SUM(A.BON_SUM) BON_SUM,
SUM(A.SEW_CNT) SEW_CNT,
SUM(A.SEW_SUM) SEW_SUM
FROM
(
 SELECT 
SUM(A.BON_CNT) BON_CNT,
SUM(A.BON_SUM) BON_SUM,
SUM(A.SEW_CNT) SEW_CNT,
SUM(A.SEW_SUM) SEW_SUM
FROM
(
SELECT 
 CASE WHEN (BONSE_AMT > 0 AND BONSE_CNT > 0) THEN BONSE_CNT 
 WHEN (BONSE_AMT > 0 AND BONSE_CNT = 0) THEN 1
 ELSE 0 END BON_CNT,
BONSE_AMT BON_SUM,
 CASE WHEN (SEWOI_AMT > 0 AND SEWOI_CNT > 0) THEN SEWOI_CNT 
 WHEN (SEWOI_AMT > 0 AND SEWOI_CNT = 0) THEN 1
ELSE 0 END SEW_CNT,
SEWOI_AMT SEW_SUM
FROM
 RPT_SUNAP_JIBGYE
WHERE
  GEORAE_GUBUN IN (3)
AND
 GEUMGO_CODE = 28
AND
 GUNGU_CODE = 170
AND
 SUNAPIL BETWEEN '20230101' AND '20231231'
AND
 JIBGYE_CODE = 104000
) A
 UNION ALL
 SELECT 
SUM(A.BON_CNT) BON_CNT,
SUM(A.BON_SUM) BON_SUM,
SUM(A.SEW_CNT) SEW_CNT,
SUM(A.SEW_SUM) SEW_SUM
FROM
( 
SELECT 
 CASE WHEN IPJI_GUBUN = 2 AND JIBANGSE_AMT > 0 THEN -1 
 WHEN IPJI_GUBUN = 1 AND JIBANGSE_AMT > 0 THEN 1
 ELSE 0 END  BON_CNT,
 CASE WHEN IPJI_GUBUN = 2 THEN JIBANGSE_AMT*-1 ELSE JIBANGSE_AMT END BON_SUM,
 
CASE WHEN IPJI_GUBUN = 2 AND SEWOI_AMT > 0 THEN -1 
 WHEN IPJI_GUBUN = 1 AND SEWOI_AMT > 0 THEN 1
 ELSE 0 END  SEW_CNT,
CASE WHEN IPJI_GUBUN = 2 THEN SEWOI_AMT*-1 ELSE SEWOI_AMT END SEW_SUM
FROM
 RPT_DANGSEIPJOJEONG
WHERE
  JOJEONG_GUBUN = 2
AND
 GEUMGO_CODE = 28
AND
 GUNGU_CODE = 170
AND
 SUNAPIL BETWEEN '20230101' AND '20231231'
AND
 JIBGYE_CODE = 104000 
) A
) A

-- 시세(세외수입) 금액
SELECT
 SUM(A.BON_CNT) BON_CNT,
 SUM(A.BON_SUM) BON_SUM,
 SUM(A.SEW_CNT) SEW_CNT,
 SUM(A.SEW_SUM) SEW_SUM
 FROM
(
  SELECT 
 SUM(A.BON_CNT) BON_CNT,
 SUM(A.BON_SUM) BON_SUM,
 SUM(A.SEW_CNT) SEW_CNT,
 SUM(A.SEW_SUM) SEW_SUM
FROM
(
SELECT 
  CASE WHEN (BONSE_AMT > 0 AND BONSE_CNT > 0) THEN BONSE_CNT 
  WHEN (BONSE_AMT > 0 AND BONSE_CNT = 0) THEN 1
  ELSE 0 END BON_CNT,
BONSE_AMT BON_SUM,
CASE WHEN  SEWOI_CNT > 0 THEN SEWOI_CNT ELSE 0 END SEW_CNT,
SEWOI_AMT SEW_SUM
FROM
  RPT_SUNAP_JIBGYE
WHERE
    GEORAE_GUBUN IN (3)
AND
  GEUMGO_CODE = 28
AND
  GUNGU_CODE = 170
AND
  SUNAPIL BETWEEN '20230101' AND '20231231'
AND
  JIBGYE_CODE = 103000
) A
  UNION ALL
  SELECT 
 SUM(A.BON_CNT) BON_CNT,
 SUM(A.BON_SUM) BON_SUM,
 SUM(A.SEW_CNT) SEW_CNT,
 SUM(A.SEW_SUM) SEW_SUM
FROM
(  
SELECT 
  CASE WHEN  IPJI_GUBUN = 2 AND JIBANGSE_AMT > 0  THEN -1 
  WHEN IPJI_GUBUN = 1 AND JIBANGSE_AMT > 0 THEN 1
  ELSE 0 END   BON_CNT,
  CASE WHEN  IPJI_GUBUN = 2 THEN JIBANGSE_AMT*-1 ELSE JIBANGSE_AMT END BON_SUM,
  
 CASE WHEN  IPJI_GUBUN = 2 AND SEWOI_AMT > 0  THEN -1 
  WHEN IPJI_GUBUN = 1 AND SEWOI_AMT > 0 THEN 1
  ELSE 0 END   SEW_CNT,
 CASE WHEN  IPJI_GUBUN = 2 THEN SEWOI_AMT*-1 ELSE SEWOI_AMT END SEW_SUM
FROM
  RPT_DANGSEIPJOJEONG
WHERE
    JOJEONG_GUBUN = 2
AND
  GEUMGO_CODE = 28
AND
  GUNGU_CODE = 170
AND
  SUNAPIL BETWEEN '20230101' AND '20231231'
AND
  JIBGYE_CODE = 103000  
) A
) A
 