SELECT A.HOIGYE_CODE
     , A.HOIGYE_NAME
     , A.GONGGEUM_GYEJWA
     , SUM(CASE WHEN KWA = '160' THEN A.JI_IJA ELSE 0 END) AS GONGGEUM_IJA
     , SUM(CASE WHEN KWA = '100' THEN A.JI_IJA ELSE 0 END) AS BOTONG_IJA
     , SUM(CASE WHEN KWA = '140' THEN A.JI_IJA ELSE 0 END) AS MMDA_IJA
     , SUM(CASE WHEN KWA BETWEEN '200' AND '299' THEN A.JI_IJA ELSE 0 END) AS JUNGGI_IJA
FROM (
         WITH WT_GYEJWA_INFO AS
                  (
                      SELECT T2.SIGUMGO_C AS GONGGEUM_GEUMGO_CD
                           , T2.SIGUMGO_HOIKYE_YR AS GONGGEUM_HOIGYE_YEAR
                           , T2.SIGUMGO_ACNO AS GONGGEUM_GYEJWA
                           , TO_NUMBER(T2.SIGUMGO_HOIKYE_C) AS GONGGEUM_HOIGYE_CODE
                           , T3.HOIKYE_NM AS HOIGYE_NAME
                      FROM  RPT_AC_BY_HOIKYE_MAPP T2
                                INNER JOIN RPT_HOIKYE_CD T3
                                           ON T2.SIGUMGO_C = T3.SIGUMGO_C
                                               AND T2.SIGUMGO_HOIKYE_C = T3.SIGUMGO_HOIKYE_C
                                               AND T3.SIGUMGO_HOIKYE_C != 98
             AND T3.USE_YN = 'Y'
         WHERE T2.SIGUMGO_C = '110'
     )
SELECT
    B.GONGGEUM_HOIGYE_CODE HOIGYE_CODE,
    B.HOIGYE_NAME,
    B.GONGGEUM_GYEJWA,
    '' AS GYEJWA_NAME,
    A.UNYONG_GYEJWA,
    D.SANGPUM_NAME,
    D.MKDT,
    A.DUDT,
    A.IYUL,
    A.JANAEK,
    TRIM(A.KIJUNIL) KIJUNIL,
    A.JI_IJA,
    SUBSTR(A.UNYONG_GYEJWA,1,3) AS KWA
FROM RPT_UNYONG_JAN A, WT_GYEJWA_INFO B, RPT_HOIGYE_IWOL C, RPT_UNYONG_GYEJWA D
WHERE A.GONGGEUM_GYEJWA = B.GONGGEUM_GYEJWA
  AND A.GONGGEUM_GYEJWA = D.GONGGEUM_GYEJWA
  AND A.UNYONG_GYEJWA = D.UNYONG_GYEJWA
  AND A.KIJUNIL BETWEEN '20240101' AND '20241231'
  AND A.GEUMGO_CODE = '110'
  AND A.GEUMGO_CODE = B.GONGGEUM_GEUMGO_CD
  AND A.GEUMGO_CODE = D.GEUMGO_CODE
  AND B.GONGGEUM_HOIGYE_CODE = C.HOIGYE_CODE(+)
  AND B.GONGGEUM_HOIGYE_YEAR = C.HOIGYE_YEAR(+)
  AND B.GONGGEUM_GEUMGO_CD = C.GEUMGO_CODE(+)
  AND C.GUBUN_CODE(+) = 1
  AND ('ALL' = NVL('','ALL') OR B.GONGGEUM_HOIGYE_CODE IN (''))
  AND A.JI_IJA > 0
  AND (
    'ALL' = NVL('2024','ALL')
        OR
    (
        CASE WHEN B.GONGGEUM_HOIGYE_YEAR = 9999 THEN SUBSTR(A.KIJUNIL,1,4)
             WHEN B.GONGGEUM_HOIGYE_YEAR=SUBSTR(A.KIJUNIL,1,4) THEN B.GONGGEUM_HOIGYE_YEAR
             WHEN SUBSTR(A.KIJUNIL,1,8) >= C.KIJUNIL THEN TO_CHAR(B.GONGGEUM_HOIGYE_YEAR + 1)
             WHEN SUBSTR(A.KIJUNIL,1,8) <  C.KIJUNIL THEN B.GONGGEUM_HOIGYE_YEAR
             ELSE B.GONGGEUM_HOIGYE_YEAR END
        ) = '2024')
  AND ('ALL' = NVL('','ALL') OR B.GONGGEUM_GYEJWA = '')
  AND ('ALL' = NVL('','ALL') OR B.GONGGEUM_HOIGYE_CODE IN (''))

UNION ALL

SELECT A.GONGGEUM_HOIGYE_CODE HOIGYE_CODE, A.HOIGYE_NAME,
       A.GONGGEUM_GYEJWA,
       '', '', '',
       '', '', 0, 0, '', 0, ''
FROM WT_GYEJWA_INFO A
WHERE 1 = 1
  AND (   ('ALL' = NVL('2024','ALL'))
    OR (A.GONGGEUM_HOIGYE_YEAR = '2024')
    OR (A.GONGGEUM_HOIGYE_YEAR='9999' AND SUBSTR('20240101',1,4) = '2024'))
  AND ('ALL' = NVL('','ALL') OR A.GONGGEUM_HOIGYE_CODE IN (''))
  AND ('ALL' = NVL('','ALL') OR A.GONGGEUM_GYEJWA  = '')

UNION ALL

SELECT A.HOIGYE_CODE, A.HOIGYE_NAME, A.GONGGEUM_GYEJWA, A.GYEJWA_NAME,
       B.UNYONG_GYEJWA, B.SANGPUM_NAME,
       C.MKDT, C.DUDT, C.IYUL, C.JANAEK, TRIM(C.KIJUNIL) KIJUNIL,
       C.JI_IJA, SUBSTR(B.UNYONG_GYEJWA,1,3) KWA
FROM (SELECT A.REF_D_NM GONGGEUM_GYEJWA, A.REF_CTNT1 GYEJWA_NAME,
             A.REF_CTNT1 HOIGYE_NAME, A.REF_S_C MNGBR,
             TO_NUMBER(SUBSTR(A.REF_D_NM,4,3)) GUNGU_CODE,
             A.REF_D_C + 900 HOIGYE_CODE, 99 GYEJWA_BUNRYU
      FROM  RPT_CODE_INFO A
      WHERE A.REF_L_C = 50
        AND A.REF_M_C = '110'
        AND A.YUHYO_YN = 0 ) A
   , RPT_UNYONG_GYEJWA B
   , RPT_UNYONG_JAN C
WHERE A.GONGGEUM_GYEJWA = B.GONGGEUM_GYEJWA
  AND B.GONGGEUM_GYEJWA = C.GONGGEUM_GYEJWA
  AND A.GONGGEUM_GYEJWA = B.GONGGEUM_GYEJWA
  AND B.UNYONG_GYEJWA = C.UNYONG_GYEJWA
  AND SUBSTR(NVL(B.MKDT,B.IN_DATE),1,8) <= '20241231'
  AND (B.OUT_DATE IS NULL OR B.OUT_DATE > '20240101' )
  AND (B.HJI_DT IS NULL OR B.HJI_DT > '20240101')
  AND B.BANK_GUBUN = 0
  AND C.KIJUNIL BETWEEN '20240101' AND '20241231'
  AND C.JI_IJA > 0
  AND ('ALL' = NVL('2024','ALL') OR SUBSTR('20240101',1,4) = '2024')
  AND ('ALL' = NVL('','ALL') OR A.GONGGEUM_GYEJWA = '')
  AND ('ALL' = NVL('','ALL') OR A.HOIGYE_CODE IN (''))

UNION ALL

SELECT A.REF_D_C + 900 HOIGYE_CODE, A.REF_CTNT1 HOIGYE_NAME,
       A.REF_D_NM GONGGEUM_GYEJWA, '', '',
       '', '', '', 0, 0, '', 0, ''
FROM RPT_CODE_INFO A
WHERE A.REF_L_C = 50
  AND A.REF_M_C = '110'
  AND ('ALL' = NVL('2024','ALL') OR SUBSTR('20240101',1,4) = '2024')
  AND ('ALL' = NVL('','ALL') OR A.REF_D_NM = '')
  AND ('ALL' = NVL('','ALL') OR (A.REF_D_C + 900) IN (''))

UNION ALL

SELECT
    C.GONGGEUM_HOIGYE_CODE, C.HOIGYE_NAME,
    C.GONGGEUM_GYEJWA, '',  '',
    '', '', '', 0, 0, '', A.IJA AS JI_IJA, '160' AS KWA
FROM RPT_GONGGEUM_GYULSAN_TMP A, WT_GYEJWA_INFO C
WHERE A.GEUMGO_CODE = '110'
  AND A.GYULSAN_IL IN (SELECT REF_S_NM FROM RPT_CODE_INFO WHERE REF_L_C = 200 AND REF_M_C = 999 AND REF_S_NM BETWEEN '20240101' AND '20241231')
  AND A.GONGGEUM_GYEJWA = C.GONGGEUM_GYEJWA
  AND A.IJA  > 0
  AND ('ALL' = NVL('2024','ALL') OR SUBSTR(A.GONGGEUM_GYEJWA,16,2) IN (SUBSTR('2024',3,2),99))

    ) A
GROUP BY A.HOIGYE_CODE, A.HOIGYE_NAME, A.GONGGEUM_GYEJWA
ORDER BY CASE WHEN SUBSTR(A.GONGGEUM_GYEJWA, 16, 2) = '99' THEN  '1'|| A.GONGGEUM_GYEJWA ELSE '2' || A.GONGGEUM_GYEJWA END , A.HOIGYE_NAME