SELECT RNUM 
   ,T5.JINGSU_CD 
   ,T5.JINGSU_NM
   ,T5.GYULJAE_DT    
   ,T5.GYULJAE_G
   ,T5.JI_ACCNO
   ,T5.GYULJAE_G_NM
   ,T5.IP_ACCNO
   ,T5.SEIP_HOIGYE_D_BUNRYU_CD
   ,T5.SEIP_HOIGYE_D_BUNRYU_NM
   ,T5.SIDO_CD
   ,T5.PADM_DONG_C
   ,T5.PADM_DONG_NM
   ,T5.HOIKYE_CD
   ,T5.KWA_CD
   ,T5.SMOK_CD
   ,T5.NEW_SMOK_OP_CD
   ,T5.SMOK_NM
   ,T5.CD_SUNP_G
   ,T5.FIRE_SPEC_HOIKYE_G
   ,T5.IMPN_YYYY
   ,T5.IMPN_MM
   ,T5.GIBUN_CD        
   ,T5.SUNP_DT
   ,T5.REP_BNK_CD
   ,T5.BNK_NM
   ,T5.DDAC_BR_CD
   ,T5.SUNP_MDIA_CD
   ,T5.NAPGI_G
   ,T5.OCR_GUBUN_CD
   ,T5.JD_MOM_GUBUN
   ,T5.NEW_GU_YR_G
   ,T5.REP_MDIA_CD
   ,T5.SUNP_CNT
   ,T5.SUNP_AMT
   ,T5.POINT_AMT
   ,T5.SISE_BON_MTAX_AMT
   ,T5.GUSE_BON_MTAX_AMT
   ,T5.SISE_CITY_AREA_AMT
   ,T5.SISE_CITY_TAX_AMT
   ,T5.SISE_FACL_TAX_AMT
   ,T5.SISE_JIBANG_EDTAX_AMT
   ,T5.KUKSE_AREA_AMT
   ,T5.KUKSE_EDTAX_AMT
   ,T5.KUKSE_NTTAX_AMT
   ,T5.KUKSE_BANGWI_AMT
   ,T5.SISE_OI_AMT
   ,T5.GUSE_OI_AMT
   ,T5.KUKSE_OI_AMT
   ,T5.KUK_BUGASE_SI_AMT
   ,T5.KUK_BUGASE_GU_AMT
   ,T5.SI_GIGM_AMT
   ,T5.GU_GIGM_AMT
   ,T5.IBHAK_AMT
   ,T5.SUEOB_AMT
   ,T5.KISEONG_AMT
   ,T5.SANGSD_AMT
   ,T5.HASD_AMT
   ,T5.WATER_USE_AMT
   ,T5.SUTAK_GONGSA_AMT
   ,T5.SUTAK_SUDO_AMT
   ,T5.SANGSD_MNG_AMT
   ,T5.CAR_AMT
   ,T5.FACL_AMT
   ,T5.GYULJAE_DT_G
   ,T5.GYULJAE_DT_G_NM
   ,T5.IP_SUNP_AMT
FROM (    
 SELECT ROW_NUMBER() OVER(ORDER BY T3.JINGSU_CD ,T3.GYULJAE_G ,T3.GYULJAE_G,T3.HOIKYE_CD ,T3.KWA_CD ,T3.SMOK_CD) AS RNUM
    ,T3.JINGSU_CD
    ,T3.JINGSU_NM
    ,T3.GYULJAE_DT    
    ,T3.GYULJAE_G
    ,T3.JI_ACCNO
    ,T3.GYULJAE_G_NM
    ,LISTAGG(T3.IP_ACCNO, ',') WITHIN GROUP(ORDER BY T3.IP_ACCNO) AS IP_ACCNO
    ,T3.SEIP_HOIGYE_D_BUNRYU_CD
    ,T3.SEIP_HOIGYE_D_BUNRYU_NM
    ,T3.SIDO_CD
    ,T3.PADM_DONG_C
    ,T3.PADM_DONG_NM
    ,T3.HOIKYE_CD
    ,T3.KWA_CD
    ,T3.SMOK_CD
    ,T3.NEW_SMOK_OP_CD
    ,T3.SMOK_NM
    ,T3.CD_SUNP_G
    ,T3.FIRE_SPEC_HOIKYE_G
    ,T3.IMPN_YYYY
    ,T3.IMPN_MM
    ,T3.GIBUN_CD        
    ,T3.SUNP_DT
    ,T3.REP_BNK_CD
    ,T3.BNK_NM
    ,T3.DDAC_BR_CD
    ,T3.SUNP_MDIA_CD
    ,T3.NAPGI_G
    ,T3.OCR_GUBUN_CD
    ,T3.JD_MOM_GUBUN
    ,T3.NEW_GU_YR_G
    ,T3.REP_MDIA_CD
    ,MAX(T3.SUNP_CNT) AS SUNP_CNT
    ,MAX(T3.SUNP_AMT) AS SUNP_AMT
    ,MAX(T3.POINT_AMT) AS POINT_AMT
    ,MAX(T3.SISE_BON_MTAX_AMT) AS SISE_BON_MTAX_AMT
    ,MAX(T3.GUSE_BON_MTAX_AMT) AS GUSE_BON_MTAX_AMT
    ,MAX(T3.SISE_CITY_AREA_AMT) AS SISE_CITY_AREA_AMT
    ,MAX(T3.SISE_CITY_TAX_AMT) AS SISE_CITY_TAX_AMT
    ,MAX(T3.SISE_FACL_TAX_AMT) AS SISE_FACL_TAX_AMT
    ,MAX(T3.SISE_JIBANG_EDTAX_AMT) AS SISE_JIBANG_EDTAX_AMT
    ,MAX(T3.KUKSE_AREA_AMT) AS KUKSE_AREA_AMT
    ,MAX(T3.KUKSE_EDTAX_AMT) AS KUKSE_EDTAX_AMT
    ,MAX(T3.KUKSE_NTTAX_AMT) AS KUKSE_NTTAX_AMT
    ,MAX(T3.KUKSE_BANGWI_AMT) AS KUKSE_BANGWI_AMT
    ,MAX(T3.SISE_OI_AMT) AS SISE_OI_AMT
    ,MAX(T3.GUSE_OI_AMT) AS GUSE_OI_AMT
    ,MAX(T3.KUKSE_OI_AMT) AS KUKSE_OI_AMT
    ,MAX(T3.KUK_BUGASE_SI_AMT) AS KUK_BUGASE_SI_AMT
    ,MAX(T3.KUK_BUGASE_GU_AMT) AS KUK_BUGASE_GU_AMT
    ,MAX(T3.SI_GIGM_AMT) AS SI_GIGM_AMT
    ,MAX(T3.GU_GIGM_AMT) AS GU_GIGM_AMT
    ,MAX(T3.IBHAK_AMT) AS IBHAK_AMT
    ,MAX(T3.SUEOB_AMT) AS SUEOB_AMT
    ,MAX(T3.KISEONG_AMT) AS KISEONG_AMT
    ,MAX(T3.SANGSD_AMT) AS SANGSD_AMT
    ,MAX(T3.HASD_AMT) AS HASD_AMT
    ,MAX(T3.WATER_USE_AMT) AS WATER_USE_AMT
    ,MAX(T3.SUTAK_GONGSA_AMT) AS SUTAK_GONGSA_AMT
    ,MAX(T3.SUTAK_SUDO_AMT) AS SUTAK_SUDO_AMT
    ,MAX(T3.SANGSD_MNG_AMT) AS SANGSD_MNG_AMT
    ,MAX(T3.CAR_AMT) AS CAR_AMT
    ,MAX(T3.FACL_AMT) AS FACL_AMT
    ,MAX(T3.GYULJAE_DT_G) AS GYULJAE_DT_G
    ,MAX(T3.GYULJAE_DT_G_NM) AS GYULJAE_DT_G_NM
    ,MAX(T3.IP_SUNP_AMT) AS IP_SUNP_AMT
 FROM (
 SELECT T2.JINGSU_CD, T2.JINGSU_CD_OLD
     ,CASE WHEN T2.JINGSU_CD = '500' THEN '환경개선'
        WHEN T2.JINGSU_CD = '900' THEN '상하수도'
        ELSE (SELECT GUCHUNG_NM FROM NIO_GUCHUNG_INF_TAB 
           WHERE TAX_K = 'CC'
           AND GUCHUNG_CD = T2.JINGSU_CD) 
      END JINGSU_NM
    ,T2.GYULJAE_DT
    ,T2.GYULJAE_G
    ,T2.JI_ACCNO
    ,T2.GYULJAE_G_NM
    ,T2.IP_ACCNO
    ,T2.SEIP_HOIGYE_D_BUNRYU_CD
    ,CASE WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '1' THEN '지방세'
       WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '2' THEN '세외수입'
       WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '3' THEN '상하수도'
       WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '4' THEN '환경개선'
       WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '5' THEN '비OCR'
       ELSE ''
     END SEIP_HOIGYE_D_BUNRYU_NM
    ,T2.SIDO_CD
    ,T2.PADM_DONG_C
    , CASE WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '2' THEN (
 SELECT DEPT_NM
 FROM NIO_DEPT_INF_TAB
 WHERE GUCHUNG_CD = (
  SELECT CVT_GUCHUNG_CD
  FROM NIO_GUCHUNG_INF_TAB 
  WHERE GUCHUNG_CD = T2.JINGSU_CD
  AND TAX_K = 'CC')
 AND DEPT_CD =T2.PADM_DONG_C AND ROWNUM = 1)
 ELSE '' END AS PADM_DONG_NM 
    ,T2.HOIKYE_CD
    ,T2.KWA_CD
    ,T2.SMOK_CD
    ,T2.NEW_SMOK_OP_CD
    ,CASE WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '2'
       THEN (SELECT NEW_SMOK_NM FROM NIO_SMOK_MAPP_TAB
        WHERE NEW_SMOK_CD = T2.SMOK_CD 
          AND NEW_SMOK_OP_CD = T2.NEW_SMOK_OP_CD
          AND ROWNUM = 1)
       ELSE (SELECT SMOK_NM FROM  NIO_SMOK_INF_TAB 
        WHERE TAX_K = CASE WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '1' THEN 'JB'
            WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '2' THEN 'SW'
            WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '3' THEN 'SD'
            WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '4' THEN 'HW'
            WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '5' THEN 'JB'
            ELSE ''
            END
          AND HOIKYE_CD = T2.HOIKYE_CD AND SMOK_CD = T2.SMOK_CD)
     END AS SMOK_NM  
    ,T2.CD_SUNP_G
    ,T2.FIRE_SPEC_HOIKYE_G
    ,T2.IMPN_YYYY
    ,T2.IMPN_MM
    ,T2.GIBUN_CD        
    ,T2.SUNP_DT
    ,T2.REP_BNK_CD
    ,(SELECT BNK_NM FROM NIO_BNK_INF_TAB WHERE BNK_C = T2.REP_BNK_CD) AS BNK_NM
    ,T2.DDAC_BR_CD
    ,T2.SUNP_MDIA_CD
    ,T2.NAPGI_G
    ,T2.OCR_GUBUN_CD
    ,T2.JD_MOM_GUBUN
    ,T2.NEW_GU_YR_G
    ,T2.REP_MDIA_CD
    ,MAX(T2.SUNP_CNT) AS SUNP_CNT
    ,MAX(T2.SUNP_AMT) AS SUNP_AMT
    ,MAX(T2.POINT_AMT) AS POINT_AMT
    ,MAX(T2.SISE_BON_MTAX_AMT) AS SISE_BON_MTAX_AMT
    ,MAX(T2.GUSE_BON_MTAX_AMT) AS GUSE_BON_MTAX_AMT
    ,MAX(T2.SISE_CITY_AREA_AMT) AS SISE_CITY_AREA_AMT
    ,MAX(T2.SISE_CITY_TAX_AMT) AS SISE_CITY_TAX_AMT
    ,MAX(T2.SISE_FACL_TAX_AMT) AS SISE_FACL_TAX_AMT
    ,MAX(T2.SISE_JIBANG_EDTAX_AMT) AS SISE_JIBANG_EDTAX_AMT
    ,MAX(T2.KUKSE_AREA_AMT) AS KUKSE_AREA_AMT
    ,MAX(T2.KUKSE_EDTAX_AMT) AS KUKSE_EDTAX_AMT
    ,MAX(T2.KUKSE_NTTAX_AMT) AS KUKSE_NTTAX_AMT
    ,MAX(T2.KUKSE_BANGWI_AMT) AS KUKSE_BANGWI_AMT
    ,MAX(T2.SISE_OI_AMT) AS SISE_OI_AMT
    ,MAX(T2.GUSE_OI_AMT) AS GUSE_OI_AMT
    ,MAX(T2.KUKSE_OI_AMT) AS KUKSE_OI_AMT
    ,MAX(T2.KUK_BUGASE_SI_AMT) AS KUK_BUGASE_SI_AMT
    ,MAX(T2.KUK_BUGASE_GU_AMT) AS KUK_BUGASE_GU_AMT
    ,MAX(T2.SI_GIGM_AMT) AS SI_GIGM_AMT
    ,MAX(T2.GU_GIGM_AMT) AS GU_GIGM_AMT
    ,MAX(T2.IBHAK_AMT) AS IBHAK_AMT
    ,MAX(T2.SUEOB_AMT) AS SUEOB_AMT
    ,MAX(T2.KISEONG_AMT) AS KISEONG_AMT
    ,MAX(T2.SANGSD_AMT) AS SANGSD_AMT
    ,MAX(T2.HASD_AMT) AS HASD_AMT
    ,MAX(T2.WATER_USE_AMT) AS WATER_USE_AMT
    ,MAX(T2.SUTAK_GONGSA_AMT) AS SUTAK_GONGSA_AMT
    ,MAX(T2.SUTAK_SUDO_AMT) AS SUTAK_SUDO_AMT
    ,MAX(T2.SANGSD_MNG_AMT) AS SANGSD_MNG_AMT
    ,MAX(T2.CAR_AMT) AS CAR_AMT
    ,MAX(T2.FACL_AMT) AS FACL_AMT
    ,MAX(T2.GYULJAE_DT_G) AS GYULJAE_DT_G
    ,MAX(T2.GYULJAE_DT_G_NM) AS GYULJAE_DT_G_NM
    ,SUM(IP_SUNP_AMT) AS IP_SUNP_AMT       
   FROM (
     SELECT T2.IMPN_HOIKYE_SM_B,            
      T1.GYULJAE_DT
     ,T1.GYULJAE_G
     ,DECODE(T1.GYULJAE_G, '02', SUBSTR(T3.ACCNO, 1, 10), T3.ACCNO) AS JI_ACCNO
     ,T3.ACCNO_NM AS GYULJAE_G_NM
     ,TRIM(T2.SIGUMGO_IP_REF_NO) AS IP_ACCNO        
     ,T1.SUNP_DT
     ,T1.SEIP_HOIGYE_D_BUNRYU_CD
     ,T1.SIDO_CD
     ,T1.JINGSU_CD
     ,T1.JINGSU_CD_OLD    
     ,T1.HOIKYE_CD
     ,T1.KWA_CD
     ,T1.SMOK_CD
     ,T1.CD_SUNP_G
     ,T1.REP_MDIA_CD
     ,T1.SUNP_MDIA_CD
     ,T1.FIRE_SPEC_HOIKYE_G
     ,T1.REP_BNK_CD
     ,T1.PADM_DONG_C
     ,T1.DDAC_BR_CD
     ,T1.NEW_GU_YR_G
     ,T1.NAPGI_G
     ,T1.OCR_GUBUN_CD
     ,T1.NEW_SMOK_OP_CD
     ,T1.IMPN_YYYY
     ,T1.IMPN_MM
     ,T1.GIBUN_CD
     ,T1.JD_MOM_GUBUN     
     ,T1.SUNP_CNT
     ,T1.SUNP_AMT
     ,T1.POINT_AMT
     ,T1.SISE_BON_MTAX_AMT
     ,T1.GUSE_BON_MTAX_AMT
     ,T1.SISE_CITY_AREA_AMT
     ,T1.SISE_CITY_TAX_AMT
     ,T1.SISE_FACL_TAX_AMT
     ,T1.SISE_JIBANG_EDTAX_AMT
     ,T1.KUKSE_AREA_AMT
     ,T1.KUKSE_EDTAX_AMT
     ,T1.KUKSE_NTTAX_AMT
     ,T1.KUKSE_BANGWI_AMT
     ,T1.SISE_OI_AMT
     ,T1.GUSE_OI_AMT
     ,T1.KUKSE_OI_AMT
     ,T1.KUK_BUGASE_SI_AMT
     ,T1.KUK_BUGASE_GU_AMT
     ,T1.SI_GIGM_AMT
     ,T1.GU_GIGM_AMT
     ,T1.IBHAK_AMT
     ,T1.SUEOB_AMT
     ,T1.KISEONG_AMT
     ,T1.SANGSD_AMT
     ,T1.HASD_AMT
     ,T1.WATER_USE_AMT
     ,T1.SUTAK_GONGSA_AMT
     ,T1.SUTAK_SUDO_AMT
     ,T1.SANGSD_MNG_AMT
     ,T1.CAR_AMT
     ,T1.FACL_AMT
     ,CASE
        WHEN T2.IMPN_HOIKYE_SM_B = '101' 
        THEN T1.SISE_BON_MTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '102' 
        THEN T1.GUSE_BON_MTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '103' 
        THEN T1.SISE_CITY_TAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '104' 
        THEN T1.SISE_FACL_TAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '105' 
        THEN T1.SISE_JIBANG_EDTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '106' 
        THEN T1.KUKSE_EDTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '107' 
        THEN T1.KUKSE_NTTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '108' 
        THEN T1.KUKSE_BANGWI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '201' 
        THEN T1.SISE_OI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '202' 
        THEN T1.GUSE_OI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '203' 
        THEN T1.KUKSE_OI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '205' 
        THEN T1.KUK_BUGASE_SI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '206' 
        THEN T1.KUK_BUGASE_GU_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '207' 
        THEN T1.SI_GIGM_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '208' 
        THEN T1.GU_GIGM_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '301' 
        THEN T1.IBHAK_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '302' 
        THEN T1.SUEOB_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '303' 
        THEN T1.KISEONG_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '401' 
        THEN T1.SANGSD_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '402' 
        THEN T1.HASD_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '403' 
        THEN T1.WATER_USE_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '404' 
        THEN T1.SUTAK_GONGSA_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '405' 
        THEN T1.SUTAK_SUDO_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '406' 
        THEN T1.SANGSD_MNG_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '501' 
        THEN T1.FACL_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '502' 
        THEN T1.CAR_AMT
        WHEN T2.SIGUMGO_IP_REF_NO IS NULL THEN T1.SUNP_AMT
        ELSE 0
      END AS IP_SUNP_AMT
     ,CASE WHEN T4.LVL = 7 THEN '1'    
        WHEN T4.LVL = 8 THEN '2'    
        ELSE '3'        
      END  GYULJAE_DT_G
     ,CASE WHEN T4.LVL = 7 THEN '7영업일'   
        WHEN T4.LVL = 8 THEN '8영업일'   
        ELSE '카드결제'      
      END  GYULJAE_DT_G_NM
    FROM
      (SELECT  
        T1.GYULJAE_G
       ,T1.GYULJAE_DT
       ,T1.SUNP_DT
       ,T1.SEIP_HOIGYE_D_BUNRYU_CD
       ,T1.SIDO_CD
       ,CASE WHEN T1.SEIP_HOIGYE_D_BUNRYU_CD = '3' THEN '900' 
             WHEN T1.SEIP_HOIGYE_D_BUNRYU_CD = '4' AND T1.JINGSU_CD NOT IN ('710','720') THEN '500' 
             ELSE T1.JINGSU_CD
           END JINGSU_CD
       ,T1.JINGSU_CD AS JINGSU_CD_OLD    
       ,T1.HOIKYE_CD
       ,T1.KWA_CD
       ,T1.SMOK_CD
       ,T1.CD_SUNP_G
       ,T1.REP_MDIA_CD
       ,T1.SUNP_MDIA_CD
       ,T1.FIRE_SPEC_HOIKYE_G
       ,T1.REP_BNK_CD
       ,T1.PADM_DONG_C
       ,T1.DDAC_BR_CD
       ,T1.NEW_GU_YR_G
       ,T1.NAPGI_G
       ,T1.OCR_GUBUN_CD
       ,T1.NEW_SMOK_OP_CD
       ,T1.IMPN_YYYY
       ,T1.IMPN_MM
       ,T1.GIBUN_CD
       ,T1.JD_MOM_GUBUN                            
       ,T1.SUNP_CNT
       ,T1.SUNP_AMT
       ,T1.POINT_AMT
       ,T1.SISE_BON_MTAX_AMT
       ,T1.GUSE_BON_MTAX_AMT
       ,T1.SISE_CITY_AREA_AMT
       ,T1.SISE_CITY_TAX_AMT
       ,T1.SISE_FACL_TAX_AMT
       ,T1.SISE_JIBANG_EDTAX_AMT
       ,T1.KUKSE_AREA_AMT
       ,T1.KUKSE_EDTAX_AMT
       ,T1.KUKSE_NTTAX_AMT
       ,T1.KUKSE_BANGWI_AMT
       ,T1.SISE_OI_AMT
       ,T1.GUSE_OI_AMT
       ,T1.KUKSE_OI_AMT
       ,T1.KUK_BUGASE_SI_AMT
       ,T1.KUK_BUGASE_GU_AMT
       ,T1.SI_GIGM_AMT
       ,T1.GU_GIGM_AMT
       ,T1.IBHAK_AMT
       ,T1.SUEOB_AMT
       ,T1.KISEONG_AMT
       ,T1.SANGSD_AMT
       ,T1.HASD_AMT
       ,T1.WATER_USE_AMT
       ,T1.SUTAK_GONGSA_AMT
       ,T1.SUTAK_SUDO_AMT
       ,T1.SANGSD_MNG_AMT
       ,T1.CAR_AMT
       ,T1.FACL_AMT
      FROM NIO_TAX_IP_CLR_TOT T1
      WHERE T1.SUNP_DT >= '20241201'
      ) T1
     ,ACL_INCHMAP_INF T2
     ,NIO_FUND_CRT_AC_TAB T3
     ,(SELECT LEVEL AS LVL 
       ,DW_BAS_DDT
      FROM MAP_JOB_DATE
        WHERE DW_BAS_DDT > TO_CHAR(TO_DATE('20250513', 'YYYYMMDD') - 20, 'YYYYMMDD') 
      CONNECT BY PRIOR BF1_BIZ_DT = DW_BAS_DDT
        START WITH DW_BAS_DDT = '20250513') T4        
    WHERE T1.SUNP_DT = T4.DW_BAS_DDT(+)
      AND (CASE WHEN T1.JINGSU_CD_OLD IN ('710', '720') THEN TO_CHAR(TO_NUMBER(T1.GYULJAE_G)) ELSE '0' END) = T2.SIGUMGO_FUND_CENT_JI_G(+)
      AND T1.JINGSU_CD_OLD = T2.IMPN_ORG_C(+)
      AND T1.PADM_DONG_C = T2.IMPN_PADM_DONGBUS_C(+)
      AND T1.HOIKYE_CD = T2.IMPN_HOIKYE_C(+)
      AND T1.SMOK_CD = T2.IMPN_TAX_IP_C(+)
      AND T1.NEW_SMOK_OP_CD = T2.IMPN_UNYUNG_SMOK_C(+)
      AND ( CASE WHEN T1.CD_SUNP_G IN ('098', '099') THEN '099' ELSE '000' END ) = T2.SUNP_CD_G(+)
      AND TO_CHAR(TO_NUMBER(T1.GYULJAE_G)) = T3.JI_ACCNO_G(+)
      AND T2.SIGUMGO_ORG_C(+) = '28'
      AND T3.IPGI_G(+) = '1'
      AND T1.GYULJAE_DT = '20250513'
      AND ('all' = 'all' OR T1.JINGSU_CD = 'all')       
      AND (CASE WHEN 'all' = 'all' THEN DECODE(GYULJAE_G, '99', '99', 'all') ELSE GYULJAE_G END)  = 'all'
      AND ('all' = NVL('all', 'all') OR T1.JD_MOM_GUBUN = 'all')
      AND ('all' = NVL('61', 'all') OR T1.HOIKYE_CD = '61')
      AND ('all' = NVL('', 'all') OR T1.SMOK_CD = '')
    ) T2
    WHERE 1=1
    AND ('all' = NVL('3', 'all') OR T2.GYULJAE_DT_G = '3')
    AND ('all' = NVL('all', 'all')  OR (T2.IP_ACCNO = 'all' AND T2.IP_SUNP_AMT > 0 ))
    GROUP BY T2.GYULJAE_DT
    ,T2.GYULJAE_G
    ,T2.SUNP_DT
    ,T2.SEIP_HOIGYE_D_BUNRYU_CD
    ,T2.SIDO_CD
    ,T2.JINGSU_CD
    ,T2.JINGSU_CD_OLD
    ,T2.HOIKYE_CD
    ,T2.KWA_CD
    ,T2.SMOK_CD
    ,T2.CD_SUNP_G
    ,T2.REP_MDIA_CD
    ,T2.SUNP_MDIA_CD
    ,T2.FIRE_SPEC_HOIKYE_G
    ,T2.REP_BNK_CD
    ,T2.PADM_DONG_C
    ,T2.DDAC_BR_CD
    ,T2.NEW_GU_YR_G
    ,T2.NAPGI_G
    ,T2.OCR_GUBUN_CD
    ,T2.NEW_SMOK_OP_CD
    ,T2.IMPN_YYYY
    ,T2.IMPN_MM
    ,T2.GIBUN_CD
    ,T2.JD_MOM_GUBUN
    ,T2.JI_ACCNO
    ,T2.GYULJAE_G_NM
    ,T2.IP_ACCNO
 ) T3
 GROUP BY 
  T3.GYULJAE_DT
 ,T3.GYULJAE_G
 ,T3.SUNP_DT
 ,T3.SEIP_HOIGYE_D_BUNRYU_CD
 ,T3.SEIP_HOIGYE_D_BUNRYU_NM
 ,T3.SIDO_CD
 ,T3.JINGSU_CD
 ,T3.JINGSU_CD_OLD
 ,T3.JINGSU_NM
 ,T3.HOIKYE_CD
 ,T3.KWA_CD
 ,T3.SMOK_CD
 ,T3.SMOK_NM
 ,T3.CD_SUNP_G
 ,T3.REP_MDIA_CD
 ,T3.SUNP_MDIA_CD
 ,T3.FIRE_SPEC_HOIKYE_G
 ,T3.REP_BNK_CD
 ,T3.BNK_NM
 ,T3.PADM_DONG_C
 ,T3.PADM_DONG_NM
 ,T3.DDAC_BR_CD
 ,T3.NEW_GU_YR_G
 ,T3.NAPGI_G
 ,T3.OCR_GUBUN_CD
 ,T3.NEW_SMOK_OP_CD
 ,T3.IMPN_YYYY
 ,T3.IMPN_MM
 ,T3.GIBUN_CD
 ,T3.JD_MOM_GUBUN
 ,T3.JI_ACCNO
 ,T3.GYULJAE_G_NM
) T5
WHERE RNUM > '0'  AND  RNUM <= '2000'
ORDER BY RNUM

------------------------------------------------

SELECT RNUM 
   ,T5.JINGSU_CD 
   ,T5.JINGSU_NM
   ,T5.GYULJAE_DT    
   ,T5.GYULJAE_G
   ,T5.JI_ACCNO
   ,T5.GYULJAE_G_NM
   ,T5.IP_ACCNO
   ,T5.SEIP_HOIGYE_D_BUNRYU_CD
   ,T5.SEIP_HOIGYE_D_BUNRYU_NM
   ,T5.SIDO_CD
   ,T5.PADM_DONG_C
   ,T5.PADM_DONG_NM
   ,T5.HOIKYE_CD
   ,T5.KWA_CD
   ,T5.SMOK_CD
   ,T5.NEW_SMOK_OP_CD
   ,T5.SMOK_NM
   ,T5.CD_SUNP_G
   ,T5.FIRE_SPEC_HOIKYE_G
   ,T5.IMPN_YYYY
   ,T5.IMPN_MM
   ,T5.GIBUN_CD        
   ,T5.SUNP_DT
   ,T5.REP_BNK_CD
   ,T5.BNK_NM
   ,T5.DDAC_BR_CD
   ,T5.SUNP_MDIA_CD
   ,T5.NAPGI_G
   ,T5.OCR_GUBUN_CD
   ,T5.JD_MOM_GUBUN
   ,T5.NEW_GU_YR_G
   ,T5.REP_MDIA_CD
   ,T5.SUNP_CNT
   ,T5.SUNP_AMT
   ,T5.POINT_AMT
   ,T5.SISE_BON_MTAX_AMT
   ,T5.GUSE_BON_MTAX_AMT
   ,T5.SISE_CITY_AREA_AMT
   ,T5.SISE_CITY_TAX_AMT
   ,T5.SISE_FACL_TAX_AMT
   ,T5.SISE_JIBANG_EDTAX_AMT
   ,T5.KUKSE_AREA_AMT
   ,T5.KUKSE_EDTAX_AMT
   ,T5.KUKSE_NTTAX_AMT
   ,T5.KUKSE_BANGWI_AMT
   ,T5.SISE_OI_AMT
   ,T5.GUSE_OI_AMT
   ,T5.KUKSE_OI_AMT
   ,T5.KUK_BUGASE_SI_AMT
   ,T5.KUK_BUGASE_GU_AMT
   ,T5.SI_GIGM_AMT
   ,T5.GU_GIGM_AMT
   ,T5.IBHAK_AMT
   ,T5.SUEOB_AMT
   ,T5.KISEONG_AMT
   ,T5.SANGSD_AMT
   ,T5.HASD_AMT
   ,T5.WATER_USE_AMT
   ,T5.SUTAK_GONGSA_AMT
   ,T5.SUTAK_SUDO_AMT
   ,T5.SANGSD_MNG_AMT
   ,T5.CAR_AMT
   ,T5.FACL_AMT
   ,T5.GYULJAE_DT_G
   ,T5.GYULJAE_DT_G_NM
   ,T5.IP_SUNP_AMT
FROM (    
 SELECT ROW_NUMBER() OVER(ORDER BY T3.JINGSU_CD ,T3.GYULJAE_G ,T3.GYULJAE_G,T3.HOIKYE_CD ,T3.KWA_CD ,T3.SMOK_CD) AS RNUM
    ,T3.JINGSU_CD
    ,T3.JINGSU_NM
    ,T3.GYULJAE_DT    
    ,T3.GYULJAE_G
    ,T3.JI_ACCNO
    ,T3.GYULJAE_G_NM
    ,LISTAGG(T3.IP_ACCNO, ',') WITHIN GROUP(ORDER BY T3.IP_ACCNO) AS IP_ACCNO
    ,T3.SEIP_HOIGYE_D_BUNRYU_CD
    ,T3.SEIP_HOIGYE_D_BUNRYU_NM
    ,T3.SIDO_CD
    ,T3.PADM_DONG_C
    ,T3.PADM_DONG_NM
    ,T3.HOIKYE_CD
    ,T3.KWA_CD
    ,T3.SMOK_CD
    ,T3.NEW_SMOK_OP_CD
    ,T3.SMOK_NM
    ,T3.CD_SUNP_G
    ,T3.FIRE_SPEC_HOIKYE_G
    ,T3.IMPN_YYYY
    ,T3.IMPN_MM
    ,T3.GIBUN_CD        
    ,T3.SUNP_DT
    ,T3.REP_BNK_CD
    ,T3.BNK_NM
    ,T3.DDAC_BR_CD
    ,T3.SUNP_MDIA_CD
    ,T3.NAPGI_G
    ,T3.OCR_GUBUN_CD
    ,T3.JD_MOM_GUBUN
    ,T3.NEW_GU_YR_G
    ,T3.REP_MDIA_CD
    ,MAX(T3.SUNP_CNT) AS SUNP_CNT
    ,MAX(T3.SUNP_AMT) AS SUNP_AMT
    ,MAX(T3.POINT_AMT) AS POINT_AMT
    ,MAX(T3.SISE_BON_MTAX_AMT) AS SISE_BON_MTAX_AMT
    ,MAX(T3.GUSE_BON_MTAX_AMT) AS GUSE_BON_MTAX_AMT
    ,MAX(T3.SISE_CITY_AREA_AMT) AS SISE_CITY_AREA_AMT
    ,MAX(T3.SISE_CITY_TAX_AMT) AS SISE_CITY_TAX_AMT
    ,MAX(T3.SISE_FACL_TAX_AMT) AS SISE_FACL_TAX_AMT
    ,MAX(T3.SISE_JIBANG_EDTAX_AMT) AS SISE_JIBANG_EDTAX_AMT
    ,MAX(T3.KUKSE_AREA_AMT) AS KUKSE_AREA_AMT
    ,MAX(T3.KUKSE_EDTAX_AMT) AS KUKSE_EDTAX_AMT
    ,MAX(T3.KUKSE_NTTAX_AMT) AS KUKSE_NTTAX_AMT
    ,MAX(T3.KUKSE_BANGWI_AMT) AS KUKSE_BANGWI_AMT
    ,MAX(T3.SISE_OI_AMT) AS SISE_OI_AMT
    ,MAX(T3.GUSE_OI_AMT) AS GUSE_OI_AMT
    ,MAX(T3.KUKSE_OI_AMT) AS KUKSE_OI_AMT
    ,MAX(T3.KUK_BUGASE_SI_AMT) AS KUK_BUGASE_SI_AMT
    ,MAX(T3.KUK_BUGASE_GU_AMT) AS KUK_BUGASE_GU_AMT
    ,MAX(T3.SI_GIGM_AMT) AS SI_GIGM_AMT
    ,MAX(T3.GU_GIGM_AMT) AS GU_GIGM_AMT
    ,MAX(T3.IBHAK_AMT) AS IBHAK_AMT
    ,MAX(T3.SUEOB_AMT) AS SUEOB_AMT
    ,MAX(T3.KISEONG_AMT) AS KISEONG_AMT
    ,MAX(T3.SANGSD_AMT) AS SANGSD_AMT
    ,MAX(T3.HASD_AMT) AS HASD_AMT
    ,MAX(T3.WATER_USE_AMT) AS WATER_USE_AMT
    ,MAX(T3.SUTAK_GONGSA_AMT) AS SUTAK_GONGSA_AMT
    ,MAX(T3.SUTAK_SUDO_AMT) AS SUTAK_SUDO_AMT
    ,MAX(T3.SANGSD_MNG_AMT) AS SANGSD_MNG_AMT
    ,MAX(T3.CAR_AMT) AS CAR_AMT
    ,MAX(T3.FACL_AMT) AS FACL_AMT
    ,MAX(T3.GYULJAE_DT_G) AS GYULJAE_DT_G
    ,MAX(T3.GYULJAE_DT_G_NM) AS GYULJAE_DT_G_NM
    ,MAX(T3.IP_SUNP_AMT) AS IP_SUNP_AMT
 FROM (
 SELECT T2.JINGSU_CD, T2.JINGSU_CD_OLD
     ,CASE WHEN T2.JINGSU_CD = '500' THEN '환경개선'
        WHEN T2.JINGSU_CD = '900' THEN '상하수도'
        ELSE (SELECT GUCHUNG_NM FROM NIO_GUCHUNG_INF_TAB 
           WHERE TAX_K = 'CC'
           AND GUCHUNG_CD = T2.JINGSU_CD) 
      END JINGSU_NM
    ,T2.GYULJAE_DT
    ,T2.GYULJAE_G
    ,T2.JI_ACCNO
    ,T2.GYULJAE_G_NM
    ,T2.IP_ACCNO
    ,T2.SEIP_HOIGYE_D_BUNRYU_CD
    ,CASE WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '1' THEN '지방세'
       WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '2' THEN '세외수입'
       WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '3' THEN '상하수도'
       WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '4' THEN '환경개선'
       WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '5' THEN '비OCR'
       ELSE ''
     END SEIP_HOIGYE_D_BUNRYU_NM
    ,T2.SIDO_CD
    ,T2.PADM_DONG_C
    , CASE WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '2' THEN (
 SELECT DEPT_NM
 FROM NIO_DEPT_INF_TAB
 WHERE GUCHUNG_CD = (
  SELECT CVT_GUCHUNG_CD
  FROM NIO_GUCHUNG_INF_TAB 
  WHERE GUCHUNG_CD = T2.JINGSU_CD
  AND TAX_K = 'CC')
 AND DEPT_CD =T2.PADM_DONG_C AND ROWNUM = 1)
 ELSE '' END AS PADM_DONG_NM 
    ,T2.HOIKYE_CD
    ,T2.KWA_CD
    ,T2.SMOK_CD
    ,T2.NEW_SMOK_OP_CD
    ,CASE WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '2'
       THEN (SELECT NEW_SMOK_NM FROM NIO_SMOK_MAPP_TAB
        WHERE NEW_SMOK_CD = T2.SMOK_CD 
          AND NEW_SMOK_OP_CD = T2.NEW_SMOK_OP_CD
          AND ROWNUM = 1)
       ELSE (SELECT SMOK_NM FROM  NIO_SMOK_INF_TAB 
        WHERE TAX_K = CASE WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '1' THEN 'JB'
            WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '2' THEN 'SW'
            WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '3' THEN 'SD'
            WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '4' THEN 'HW'
            WHEN T2.SEIP_HOIGYE_D_BUNRYU_CD = '5' THEN 'JB'
            ELSE ''
            END
          AND HOIKYE_CD = T2.HOIKYE_CD AND SMOK_CD = T2.SMOK_CD)
     END AS SMOK_NM  
    ,T2.CD_SUNP_G
    ,T2.FIRE_SPEC_HOIKYE_G
    ,T2.IMPN_YYYY
    ,T2.IMPN_MM
    ,T2.GIBUN_CD        
    ,T2.SUNP_DT
    ,T2.REP_BNK_CD
    ,(SELECT BNK_NM FROM NIO_BNK_INF_TAB WHERE BNK_C = T2.REP_BNK_CD) AS BNK_NM
    ,T2.DDAC_BR_CD
    ,T2.SUNP_MDIA_CD
    ,T2.NAPGI_G
    ,T2.OCR_GUBUN_CD
    ,T2.JD_MOM_GUBUN
    ,T2.NEW_GU_YR_G
    ,T2.REP_MDIA_CD
    ,MAX(T2.SUNP_CNT) AS SUNP_CNT
    ,MAX(T2.SUNP_AMT) AS SUNP_AMT
    ,MAX(T2.POINT_AMT) AS POINT_AMT
    ,MAX(T2.SISE_BON_MTAX_AMT) AS SISE_BON_MTAX_AMT
    ,MAX(T2.GUSE_BON_MTAX_AMT) AS GUSE_BON_MTAX_AMT
    ,MAX(T2.SISE_CITY_AREA_AMT) AS SISE_CITY_AREA_AMT
    ,MAX(T2.SISE_CITY_TAX_AMT) AS SISE_CITY_TAX_AMT
    ,MAX(T2.SISE_FACL_TAX_AMT) AS SISE_FACL_TAX_AMT
    ,MAX(T2.SISE_JIBANG_EDTAX_AMT) AS SISE_JIBANG_EDTAX_AMT
    ,MAX(T2.KUKSE_AREA_AMT) AS KUKSE_AREA_AMT
    ,MAX(T2.KUKSE_EDTAX_AMT) AS KUKSE_EDTAX_AMT
    ,MAX(T2.KUKSE_NTTAX_AMT) AS KUKSE_NTTAX_AMT
    ,MAX(T2.KUKSE_BANGWI_AMT) AS KUKSE_BANGWI_AMT
    ,MAX(T2.SISE_OI_AMT) AS SISE_OI_AMT
    ,MAX(T2.GUSE_OI_AMT) AS GUSE_OI_AMT
    ,MAX(T2.KUKSE_OI_AMT) AS KUKSE_OI_AMT
    ,MAX(T2.KUK_BUGASE_SI_AMT) AS KUK_BUGASE_SI_AMT
    ,MAX(T2.KUK_BUGASE_GU_AMT) AS KUK_BUGASE_GU_AMT
    ,MAX(T2.SI_GIGM_AMT) AS SI_GIGM_AMT
    ,MAX(T2.GU_GIGM_AMT) AS GU_GIGM_AMT
    ,MAX(T2.IBHAK_AMT) AS IBHAK_AMT
    ,MAX(T2.SUEOB_AMT) AS SUEOB_AMT
    ,MAX(T2.KISEONG_AMT) AS KISEONG_AMT
    ,MAX(T2.SANGSD_AMT) AS SANGSD_AMT
    ,MAX(T2.HASD_AMT) AS HASD_AMT
    ,MAX(T2.WATER_USE_AMT) AS WATER_USE_AMT
    ,MAX(T2.SUTAK_GONGSA_AMT) AS SUTAK_GONGSA_AMT
    ,MAX(T2.SUTAK_SUDO_AMT) AS SUTAK_SUDO_AMT
    ,MAX(T2.SANGSD_MNG_AMT) AS SANGSD_MNG_AMT
    ,MAX(T2.CAR_AMT) AS CAR_AMT
    ,MAX(T2.FACL_AMT) AS FACL_AMT
    ,MAX(T2.GYULJAE_DT_G) AS GYULJAE_DT_G
    ,MAX(T2.GYULJAE_DT_G_NM) AS GYULJAE_DT_G_NM
    ,SUM(IP_SUNP_AMT) AS IP_SUNP_AMT       
   FROM (
     SELECT T2.IMPN_HOIKYE_SM_B,            
      T1.GYULJAE_DT
     ,T1.GYULJAE_G
     ,DECODE(T1.GYULJAE_G, '02', SUBSTR(T3.ACCNO, 1, 10), T3.ACCNO) AS JI_ACCNO
     ,T3.ACCNO_NM AS GYULJAE_G_NM
     ,TRIM(T2.SIGUMGO_IP_REF_NO) AS IP_ACCNO        
     ,T1.SUNP_DT
     ,T1.SEIP_HOIGYE_D_BUNRYU_CD
     ,T1.SIDO_CD
     ,T1.JINGSU_CD
     ,T1.JINGSU_CD_OLD    
     ,T1.HOIKYE_CD
     ,T1.KWA_CD
     ,T1.SMOK_CD
     ,T1.CD_SUNP_G
     ,T1.REP_MDIA_CD
     ,T1.SUNP_MDIA_CD
     ,T1.FIRE_SPEC_HOIKYE_G
     ,T1.REP_BNK_CD
     ,T1.PADM_DONG_C
     ,T1.DDAC_BR_CD
     ,T1.NEW_GU_YR_G
     ,T1.NAPGI_G
     ,T1.OCR_GUBUN_CD
     ,T1.NEW_SMOK_OP_CD
     ,T1.IMPN_YYYY
     ,T1.IMPN_MM
     ,T1.GIBUN_CD
     ,T1.JD_MOM_GUBUN     
     ,T1.SUNP_CNT
     ,T1.SUNP_AMT
     ,T1.POINT_AMT
     ,T1.SISE_BON_MTAX_AMT
     ,T1.GUSE_BON_MTAX_AMT
     ,T1.SISE_CITY_AREA_AMT
     ,T1.SISE_CITY_TAX_AMT
     ,T1.SISE_FACL_TAX_AMT
     ,T1.SISE_JIBANG_EDTAX_AMT
     ,T1.KUKSE_AREA_AMT
     ,T1.KUKSE_EDTAX_AMT
     ,T1.KUKSE_NTTAX_AMT
     ,T1.KUKSE_BANGWI_AMT
     ,T1.SISE_OI_AMT
     ,T1.GUSE_OI_AMT
     ,T1.KUKSE_OI_AMT
     ,T1.KUK_BUGASE_SI_AMT
     ,T1.KUK_BUGASE_GU_AMT
     ,T1.SI_GIGM_AMT
     ,T1.GU_GIGM_AMT
     ,T1.IBHAK_AMT
     ,T1.SUEOB_AMT
     ,T1.KISEONG_AMT
     ,T1.SANGSD_AMT
     ,T1.HASD_AMT
     ,T1.WATER_USE_AMT
     ,T1.SUTAK_GONGSA_AMT
     ,T1.SUTAK_SUDO_AMT
     ,T1.SANGSD_MNG_AMT
     ,T1.CAR_AMT
     ,T1.FACL_AMT
     ,CASE
        WHEN T2.IMPN_HOIKYE_SM_B = '101' 
        THEN T1.SISE_BON_MTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '102' 
        THEN T1.GUSE_BON_MTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '103' 
        THEN T1.SISE_CITY_TAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '104' 
        THEN T1.SISE_FACL_TAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '105' 
        THEN T1.SISE_JIBANG_EDTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '106' 
        THEN T1.KUKSE_EDTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '107' 
        THEN T1.KUKSE_NTTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '108' 
        THEN T1.KUKSE_BANGWI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '201' 
        THEN T1.SISE_OI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '202' 
        THEN T1.GUSE_OI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '203' 
        THEN T1.KUKSE_OI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '205' 
        THEN T1.KUK_BUGASE_SI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '206' 
        THEN T1.KUK_BUGASE_GU_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '207' 
        THEN T1.SI_GIGM_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '208' 
        THEN T1.GU_GIGM_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '301' 
        THEN T1.IBHAK_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '302' 
        THEN T1.SUEOB_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '303' 
        THEN T1.KISEONG_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '401' 
        THEN T1.SANGSD_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '402' 
        THEN T1.HASD_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '403' 
        THEN T1.WATER_USE_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '404' 
        THEN T1.SUTAK_GONGSA_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '405' 
        THEN T1.SUTAK_SUDO_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '406' 
        THEN T1.SANGSD_MNG_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '501' 
        THEN T1.FACL_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '502' 
        THEN T1.CAR_AMT
        WHEN T2.SIGUMGO_IP_REF_NO IS NULL THEN T1.SUNP_AMT
        ELSE 0
      END AS IP_SUNP_AMT
     ,CASE WHEN T4.LVL = 7 AND T1.CD_SUNP_G = '000' THEN '1'    
        WHEN T4.LVL = 8 AND T1.CD_SUNP_G = '000' THEN '2'    
        ELSE '3'        
      END  GYULJAE_DT_G
     ,CASE WHEN T4.LVL = 7 AND T1.CD_SUNP_G = '000' THEN '7영업일'   
        WHEN T4.LVL = 8 AND T1.CD_SUNP_G = '000' THEN '8영업일'   
        ELSE '카드결제'      
      END  GYULJAE_DT_G_NM
    FROM
      (SELECT  
        T1.GYULJAE_G
       ,T1.GYULJAE_DT
       ,T1.SUNP_DT
       ,T1.SEIP_HOIGYE_D_BUNRYU_CD
       ,T1.SIDO_CD
       ,CASE WHEN T1.SEIP_HOIGYE_D_BUNRYU_CD = '3' THEN '900' 
             WHEN T1.SEIP_HOIGYE_D_BUNRYU_CD = '4' AND T1.JINGSU_CD NOT IN ('710','720') THEN '500' 
             ELSE T1.JINGSU_CD
           END JINGSU_CD
       ,T1.JINGSU_CD AS JINGSU_CD_OLD    
       ,T1.HOIKYE_CD
       ,T1.KWA_CD
       ,T1.SMOK_CD
       ,T1.CD_SUNP_G
       ,T1.REP_MDIA_CD
       ,T1.SUNP_MDIA_CD
       ,T1.FIRE_SPEC_HOIKYE_G
       ,T1.REP_BNK_CD
       ,T1.PADM_DONG_C
       ,T1.DDAC_BR_CD
       ,T1.NEW_GU_YR_G
       ,T1.NAPGI_G
       ,T1.OCR_GUBUN_CD
       ,T1.NEW_SMOK_OP_CD
       ,T1.IMPN_YYYY
       ,T1.IMPN_MM
       ,T1.GIBUN_CD
       ,T1.JD_MOM_GUBUN                            
       ,T1.SUNP_CNT
       ,T1.SUNP_AMT
       ,T1.POINT_AMT
       ,T1.SISE_BON_MTAX_AMT
       ,T1.GUSE_BON_MTAX_AMT
       ,T1.SISE_CITY_AREA_AMT
       ,T1.SISE_CITY_TAX_AMT
       ,T1.SISE_FACL_TAX_AMT
       ,T1.SISE_JIBANG_EDTAX_AMT
       ,T1.KUKSE_AREA_AMT
       ,T1.KUKSE_EDTAX_AMT
       ,T1.KUKSE_NTTAX_AMT
       ,T1.KUKSE_BANGWI_AMT
       ,T1.SISE_OI_AMT
       ,T1.GUSE_OI_AMT
       ,T1.KUKSE_OI_AMT
       ,T1.KUK_BUGASE_SI_AMT
       ,T1.KUK_BUGASE_GU_AMT
       ,T1.SI_GIGM_AMT
       ,T1.GU_GIGM_AMT
       ,T1.IBHAK_AMT
       ,T1.SUEOB_AMT
       ,T1.KISEONG_AMT
       ,T1.SANGSD_AMT
       ,T1.HASD_AMT
       ,T1.WATER_USE_AMT
       ,T1.SUTAK_GONGSA_AMT
       ,T1.SUTAK_SUDO_AMT
       ,T1.SANGSD_MNG_AMT
       ,T1.CAR_AMT
       ,T1.FACL_AMT
      FROM NIO_TAX_IP_CLR_TOT T1
      WHERE T1.SUNP_DT >= '20241201'
      ) T1
     ,ACL_INCHMAP_INF T2
     ,NIO_FUND_CRT_AC_TAB T3
     ,(SELECT LEVEL AS LVL 
       ,DW_BAS_DDT
      FROM MAP_JOB_DATE
        WHERE DW_BAS_DDT > TO_CHAR(TO_DATE('20250513', 'YYYYMMDD') - 20, 'YYYYMMDD') 
      CONNECT BY PRIOR BF1_BIZ_DT = DW_BAS_DDT
        START WITH DW_BAS_DDT = '20250513') T4        
    WHERE T1.SUNP_DT = T4.DW_BAS_DDT(+)
      AND (CASE WHEN T1.JINGSU_CD_OLD IN ('710', '720') THEN TO_CHAR(TO_NUMBER(T1.GYULJAE_G)) ELSE '0' END) = T2.SIGUMGO_FUND_CENT_JI_G(+)
      AND T1.JINGSU_CD_OLD = T2.IMPN_ORG_C(+)
      AND T1.PADM_DONG_C = T2.IMPN_PADM_DONGBUS_C(+)
      AND T1.HOIKYE_CD = T2.IMPN_HOIKYE_C(+)
      AND T1.SMOK_CD = T2.IMPN_TAX_IP_C(+)
      AND T1.NEW_SMOK_OP_CD = T2.IMPN_UNYUNG_SMOK_C(+)
      AND ( CASE WHEN T1.CD_SUNP_G IN ('098', '099') THEN '099' ELSE '000' END ) = T2.SUNP_CD_G(+)
      AND TO_CHAR(TO_NUMBER(T1.GYULJAE_G)) = T3.JI_ACCNO_G(+)
      AND T2.SIGUMGO_ORG_C(+) = '28'
      AND T3.IPGI_G(+) = '1'
      AND T1.GYULJAE_DT = '20250513'
      AND ('all' = 'all' OR T1.JINGSU_CD = 'all')       
      AND (CASE WHEN 'all' = 'all' THEN DECODE(GYULJAE_G, '99', '99', 'all') ELSE GYULJAE_G END)  = 'all'
      AND ('all' = NVL('all', 'all') OR T1.JD_MOM_GUBUN = 'all')
      AND ('all' = NVL('61', 'all') OR T1.HOIKYE_CD = '61')
      AND ('all' = NVL('', 'all') OR T1.SMOK_CD = '')
    ) T2
    WHERE 1=1
    AND ('all' = NVL('3', 'all') OR T2.GYULJAE_DT_G = '3')
    AND ('all' = NVL('all', 'all')  OR (T2.IP_ACCNO = 'all' AND T2.IP_SUNP_AMT > 0 ))
    GROUP BY T2.GYULJAE_DT
    ,T2.GYULJAE_G
    ,T2.SUNP_DT
    ,T2.SEIP_HOIGYE_D_BUNRYU_CD
    ,T2.SIDO_CD
    ,T2.JINGSU_CD
    ,T2.JINGSU_CD_OLD
    ,T2.HOIKYE_CD
    ,T2.KWA_CD
    ,T2.SMOK_CD
    ,T2.CD_SUNP_G
    ,T2.REP_MDIA_CD
    ,T2.SUNP_MDIA_CD
    ,T2.FIRE_SPEC_HOIKYE_G
    ,T2.REP_BNK_CD
    ,T2.PADM_DONG_C
    ,T2.DDAC_BR_CD
    ,T2.NEW_GU_YR_G
    ,T2.NAPGI_G
    ,T2.OCR_GUBUN_CD
    ,T2.NEW_SMOK_OP_CD
    ,T2.IMPN_YYYY
    ,T2.IMPN_MM
    ,T2.GIBUN_CD
    ,T2.JD_MOM_GUBUN
    ,T2.JI_ACCNO
    ,T2.GYULJAE_G_NM
    ,T2.IP_ACCNO
 ) T3
 GROUP BY 
  T3.GYULJAE_DT
 ,T3.GYULJAE_G
 ,T3.SUNP_DT
 ,T3.SEIP_HOIGYE_D_BUNRYU_CD
 ,T3.SEIP_HOIGYE_D_BUNRYU_NM
 ,T3.SIDO_CD
 ,T3.JINGSU_CD
 ,T3.JINGSU_CD_OLD
 ,T3.JINGSU_NM
 ,T3.HOIKYE_CD
 ,T3.KWA_CD
 ,T3.SMOK_CD
 ,T3.SMOK_NM
 ,T3.CD_SUNP_G
 ,T3.REP_MDIA_CD
 ,T3.SUNP_MDIA_CD
 ,T3.FIRE_SPEC_HOIKYE_G
 ,T3.REP_BNK_CD
 ,T3.BNK_NM
 ,T3.PADM_DONG_C
 ,T3.PADM_DONG_NM
 ,T3.DDAC_BR_CD
 ,T3.NEW_GU_YR_G
 ,T3.NAPGI_G
 ,T3.OCR_GUBUN_CD
 ,T3.NEW_SMOK_OP_CD
 ,T3.IMPN_YYYY
 ,T3.IMPN_MM
 ,T3.GIBUN_CD
 ,T3.JD_MOM_GUBUN
 ,T3.JI_ACCNO
 ,T3.GYULJAE_G_NM
) T5
WHERE RNUM > '0'  AND  RNUM <= '2000'
ORDER BY RNUM


---------------------------------------------

SELECT 
    SUM(SUNP_AMT) AS AMT 
FROM NIO_TAX_IP_CLR_TOT
WHERE SUNP_DT >= '20250401'
AND GYULJAE_DT = '20250513'
AND CD_SUNP_G <> '000'
AND SEIP_HOIGYE_D_BUNRYU_CD = '2'
AND HOIKYE_CD = '61'

-----------------------------------------

SELECT T2.IMPN_HOIKYE_SM_B,            
      T1.GYULJAE_DT
     ,T1.GYULJAE_G
     ,DECODE(T1.GYULJAE_G, '02', SUBSTR(T3.ACCNO, 1, 10), T3.ACCNO) AS JI_ACCNO
     ,T3.ACCNO_NM AS GYULJAE_G_NM
     ,TRIM(T2.SIGUMGO_IP_REF_NO) AS IP_ACCNO        
     ,T1.SUNP_DT
     ,T1.SEIP_HOIGYE_D_BUNRYU_CD
     ,T1.SIDO_CD
     ,T1.JINGSU_CD
     ,T1.JINGSU_CD_OLD    
     ,T1.HOIKYE_CD
     ,T1.KWA_CD
     ,T1.SMOK_CD
     ,T1.CD_SUNP_G
     ,T1.REP_MDIA_CD
     ,T1.SUNP_MDIA_CD
     ,T1.FIRE_SPEC_HOIKYE_G
     ,T1.REP_BNK_CD
     ,T1.PADM_DONG_C
     ,T1.DDAC_BR_CD
     ,T1.NEW_GU_YR_G
     ,T1.NAPGI_G
     ,T1.OCR_GUBUN_CD
     ,T1.NEW_SMOK_OP_CD
     ,T1.IMPN_YYYY
     ,T1.IMPN_MM
     ,T1.GIBUN_CD
     ,T1.JD_MOM_GUBUN     
     ,T1.SUNP_CNT
     ,T1.SUNP_AMT
     ,T1.POINT_AMT
     ,T1.SISE_BON_MTAX_AMT
     ,T1.GUSE_BON_MTAX_AMT
     ,T1.SISE_CITY_AREA_AMT
     ,T1.SISE_CITY_TAX_AMT
     ,T1.SISE_FACL_TAX_AMT
     ,T1.SISE_JIBANG_EDTAX_AMT
     ,T1.KUKSE_AREA_AMT
     ,T1.KUKSE_EDTAX_AMT
     ,T1.KUKSE_NTTAX_AMT
     ,T1.KUKSE_BANGWI_AMT
     ,T1.SISE_OI_AMT
     ,T1.GUSE_OI_AMT
     ,T1.KUKSE_OI_AMT
     ,T1.KUK_BUGASE_SI_AMT
     ,T1.KUK_BUGASE_GU_AMT
     ,T1.SI_GIGM_AMT
     ,T1.GU_GIGM_AMT
     ,T1.IBHAK_AMT
     ,T1.SUEOB_AMT
     ,T1.KISEONG_AMT
     ,T1.SANGSD_AMT
     ,T1.HASD_AMT
     ,T1.WATER_USE_AMT
     ,T1.SUTAK_GONGSA_AMT
     ,T1.SUTAK_SUDO_AMT
     ,T1.SANGSD_MNG_AMT
     ,T1.CAR_AMT
     ,T1.FACL_AMT
     ,CASE
        WHEN T2.IMPN_HOIKYE_SM_B = '101' 
        THEN T1.SISE_BON_MTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '102' 
        THEN T1.GUSE_BON_MTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '103' 
        THEN T1.SISE_CITY_TAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '104' 
        THEN T1.SISE_FACL_TAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '105' 
        THEN T1.SISE_JIBANG_EDTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '106' 
        THEN T1.KUKSE_EDTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '107' 
        THEN T1.KUKSE_NTTAX_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '108' 
        THEN T1.KUKSE_BANGWI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '201' 
        THEN T1.SISE_OI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '202' 
        THEN T1.GUSE_OI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '203' 
        THEN T1.KUKSE_OI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '205' 
        THEN T1.KUK_BUGASE_SI_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '206' 
        THEN T1.KUK_BUGASE_GU_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '207' 
        THEN T1.SI_GIGM_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '208' 
        THEN T1.GU_GIGM_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '301' 
        THEN T1.IBHAK_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '302' 
        THEN T1.SUEOB_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '303' 
        THEN T1.KISEONG_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '401' 
        THEN T1.SANGSD_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '402' 
        THEN T1.HASD_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '403' 
        THEN T1.WATER_USE_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '404' 
        THEN T1.SUTAK_GONGSA_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '405' 
        THEN T1.SUTAK_SUDO_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '406' 
        THEN T1.SANGSD_MNG_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '501' 
        THEN T1.FACL_AMT
        WHEN T2.IMPN_HOIKYE_SM_B = '502' 
        THEN T1.CAR_AMT
        WHEN T2.SIGUMGO_IP_REF_NO IS NULL THEN T1.SUNP_AMT
        ELSE 0
      END AS IP_SUNP_AMT
     ,CASE WHEN T4.LVL = 7 AND T1.CD_SUNP_G = '000' THEN '1'    
        WHEN T4.LVL = 8 AND T1.CD_SUNP_G = '000' THEN '2'    
        ELSE '3'        
      END  GYULJAE_DT_G
     ,CASE WHEN T4.LVL = 7 AND T1.CD_SUNP_G = '000' THEN '7영업일'   
        WHEN T4.LVL = 8 AND T1.CD_SUNP_G = '000' THEN '8영업일'   
        ELSE '카드결제'      
      END  GYULJAE_DT_G_NM
    FROM
      (SELECT  
        T1.GYULJAE_G
       ,T1.GYULJAE_DT
       ,T1.SUNP_DT
       ,T1.SEIP_HOIGYE_D_BUNRYU_CD
       ,T1.SIDO_CD
       ,CASE WHEN T1.SEIP_HOIGYE_D_BUNRYU_CD = '3' THEN '900' 
             WHEN T1.SEIP_HOIGYE_D_BUNRYU_CD = '4' AND T1.JINGSU_CD NOT IN ('710','720') THEN '500' 
             ELSE T1.JINGSU_CD
           END JINGSU_CD
       ,T1.JINGSU_CD AS JINGSU_CD_OLD    
       ,T1.HOIKYE_CD
       ,T1.KWA_CD
       ,T1.SMOK_CD
       ,T1.CD_SUNP_G
       ,T1.REP_MDIA_CD
       ,T1.SUNP_MDIA_CD
       ,T1.FIRE_SPEC_HOIKYE_G
       ,T1.REP_BNK_CD
       ,T1.PADM_DONG_C
       ,T1.DDAC_BR_CD
       ,T1.NEW_GU_YR_G
       ,T1.NAPGI_G
       ,T1.OCR_GUBUN_CD
       ,T1.NEW_SMOK_OP_CD
       ,T1.IMPN_YYYY
       ,T1.IMPN_MM
       ,T1.GIBUN_CD
       ,T1.JD_MOM_GUBUN                            
       ,T1.SUNP_CNT
       ,T1.SUNP_AMT
       ,T1.POINT_AMT
       ,T1.SISE_BON_MTAX_AMT
       ,T1.GUSE_BON_MTAX_AMT
       ,T1.SISE_CITY_AREA_AMT
       ,T1.SISE_CITY_TAX_AMT
       ,T1.SISE_FACL_TAX_AMT
       ,T1.SISE_JIBANG_EDTAX_AMT
       ,T1.KUKSE_AREA_AMT
       ,T1.KUKSE_EDTAX_AMT
       ,T1.KUKSE_NTTAX_AMT
       ,T1.KUKSE_BANGWI_AMT
       ,T1.SISE_OI_AMT
       ,T1.GUSE_OI_AMT
       ,T1.KUKSE_OI_AMT
       ,T1.KUK_BUGASE_SI_AMT
       ,T1.KUK_BUGASE_GU_AMT
       ,T1.SI_GIGM_AMT
       ,T1.GU_GIGM_AMT
       ,T1.IBHAK_AMT
       ,T1.SUEOB_AMT
       ,T1.KISEONG_AMT
       ,T1.SANGSD_AMT
       ,T1.HASD_AMT
       ,T1.WATER_USE_AMT
       ,T1.SUTAK_GONGSA_AMT
       ,T1.SUTAK_SUDO_AMT
       ,T1.SANGSD_MNG_AMT
       ,T1.CAR_AMT
       ,T1.FACL_AMT
      FROM NIO_TAX_IP_CLR_TOT T1
      WHERE T1.SUNP_DT >= '20241201'
      ) T1
     ,ACL_INCHMAP_INF T2
     ,NIO_FUND_CRT_AC_TAB T3
     ,(SELECT LEVEL AS LVL 
       ,DW_BAS_DDT
      FROM MAP_JOB_DATE
        WHERE DW_BAS_DDT > TO_CHAR(TO_DATE('20250513', 'YYYYMMDD') - 20, 'YYYYMMDD') 
      CONNECT BY PRIOR BF1_BIZ_DT = DW_BAS_DDT
        START WITH DW_BAS_DDT = '20250513') T4        
    WHERE T1.SUNP_DT = T4.DW_BAS_DDT(+)
      -- AND (CASE WHEN T1.JINGSU_CD_OLD IN ('710', '720') THEN TO_CHAR(TO_NUMBER(T1.GYULJAE_G)) ELSE '0' END) = T2.SIGUMGO_FUND_CENT_JI_G(+)
      AND T1.JINGSU_CD_OLD = T2.IMPN_ORG_C(+)
      AND T1.PADM_DONG_C = T2.IMPN_PADM_DONGBUS_C(+)
      AND T1.HOIKYE_CD = T2.IMPN_HOIKYE_C(+)
      AND T1.SMOK_CD = T2.IMPN_TAX_IP_C(+)
      AND T1.NEW_SMOK_OP_CD = T2.IMPN_UNYUNG_SMOK_C(+)
      AND ( CASE WHEN T1.CD_SUNP_G IN ('098', '099') THEN '099' ELSE '000' END ) = T2.SUNP_CD_G(+)
      AND TO_CHAR(TO_NUMBER(T1.GYULJAE_G)) = T3.JI_ACCNO_G(+)
      AND T2.SIGUMGO_ORG_C(+) = '28'
      AND T3.IPGI_G(+) = '1'
      AND T1.GYULJAE_DT = '20250513'
      AND ('all' = 'all' OR T1.JINGSU_CD = 'all')       
      AND (CASE WHEN 'all' = 'all' THEN DECODE(GYULJAE_G, '99', '99', 'all') ELSE GYULJAE_G END)  = 'all'
      AND ('all' = NVL('all', 'all') OR T1.JD_MOM_GUBUN = 'all')
      AND ('all' = NVL('61', 'all') OR T1.HOIKYE_CD = '61')
      AND ('all' = NVL('', 'all') OR T1.SMOK_CD = '')
      AND  T1.CD_SUNP_G <> '000'

-------------------------------------------------


SELECT 
    *
FROM NIO_TAX_IP_CLR_TOT
WHERE SUNP_DT >= '20250401'
AND GYULJAE_DT = '20250513'
AND CD_SUNP_G <> '000'
AND SEIP_HOIGYE_D_BUNRYU_CD = '2'
AND HOIKYE_CD = '61'
AND TAX_IP_SEQ_NO NOT IN (
    SELECT 
        T1.TAX_IP_SEQ_NO
    FROM
      (SELECT  
        T1.GYULJAE_G
       ,T1.GYULJAE_DT
       ,T1.SUNP_DT
       ,T1.SEIP_HOIGYE_D_BUNRYU_CD
       ,T1.SIDO_CD
       ,CASE WHEN T1.SEIP_HOIGYE_D_BUNRYU_CD = '3' THEN '900' 
             WHEN T1.SEIP_HOIGYE_D_BUNRYU_CD = '4' AND T1.JINGSU_CD NOT IN ('710','720') THEN '500' 
             ELSE T1.JINGSU_CD
           END JINGSU_CD
       ,T1.JINGSU_CD AS JINGSU_CD_OLD    
       ,T1.HOIKYE_CD
       ,T1.KWA_CD
       ,T1.SMOK_CD
       ,T1.CD_SUNP_G
       ,T1.REP_MDIA_CD
       ,T1.SUNP_MDIA_CD
       ,T1.FIRE_SPEC_HOIKYE_G
       ,T1.REP_BNK_CD
       ,T1.PADM_DONG_C
       ,T1.DDAC_BR_CD
       ,T1.NEW_GU_YR_G
       ,T1.NAPGI_G
       ,T1.OCR_GUBUN_CD
       ,T1.NEW_SMOK_OP_CD
       ,T1.IMPN_YYYY
       ,T1.IMPN_MM
       ,T1.GIBUN_CD
       ,T1.JD_MOM_GUBUN                            
       ,T1.SUNP_CNT
       ,T1.SUNP_AMT
       ,T1.POINT_AMT
       ,T1.SISE_BON_MTAX_AMT
       ,T1.GUSE_BON_MTAX_AMT
       ,T1.SISE_CITY_AREA_AMT
       ,T1.SISE_CITY_TAX_AMT
       ,T1.SISE_FACL_TAX_AMT
       ,T1.SISE_JIBANG_EDTAX_AMT
       ,T1.KUKSE_AREA_AMT
       ,T1.KUKSE_EDTAX_AMT
       ,T1.KUKSE_NTTAX_AMT
       ,T1.KUKSE_BANGWI_AMT
       ,T1.SISE_OI_AMT
       ,T1.GUSE_OI_AMT
       ,T1.KUKSE_OI_AMT
       ,T1.KUK_BUGASE_SI_AMT
       ,T1.KUK_BUGASE_GU_AMT
       ,T1.SI_GIGM_AMT
       ,T1.GU_GIGM_AMT
       ,T1.IBHAK_AMT
       ,T1.SUEOB_AMT
       ,T1.KISEONG_AMT
       ,T1.SANGSD_AMT
       ,T1.HASD_AMT
       ,T1.WATER_USE_AMT
       ,T1.SUTAK_GONGSA_AMT
       ,T1.SUTAK_SUDO_AMT
       ,T1.SANGSD_MNG_AMT
       ,T1.CAR_AMT
       ,T1.FACL_AMT
       ,T1.TAX_IP_SEQ_NO
      FROM NIO_TAX_IP_CLR_TOT T1
      WHERE T1.SUNP_DT >= '20241201'
      ) T1
     ,ACL_INCHMAP_INF T2
     ,NIO_FUND_CRT_AC_TAB T3
     ,(SELECT LEVEL AS LVL 
       ,DW_BAS_DDT
      FROM MAP_JOB_DATE
        WHERE DW_BAS_DDT > TO_CHAR(TO_DATE('20250513', 'YYYYMMDD') - 20, 'YYYYMMDD') 
      CONNECT BY PRIOR BF1_BIZ_DT = DW_BAS_DDT
        START WITH DW_BAS_DDT = '20250513') T4        
    WHERE T1.SUNP_DT = T4.DW_BAS_DDT(+)
      AND (CASE WHEN T1.JINGSU_CD_OLD IN ('710', '720') THEN TO_CHAR(TO_NUMBER(T1.GYULJAE_G)) ELSE '0' END) = T2.SIGUMGO_FUND_CENT_JI_G(+)
      AND T1.JINGSU_CD_OLD = T2.IMPN_ORG_C(+)
      AND T1.PADM_DONG_C = T2.IMPN_PADM_DONGBUS_C(+)
      AND T1.HOIKYE_CD = T2.IMPN_HOIKYE_C(+)
      AND T1.SMOK_CD = T2.IMPN_TAX_IP_C(+)
      AND T1.NEW_SMOK_OP_CD = T2.IMPN_UNYUNG_SMOK_C(+)
      AND ( CASE WHEN T1.CD_SUNP_G IN ('098', '099') THEN '099' ELSE '000' END ) = T2.SUNP_CD_G(+)
      AND TO_CHAR(TO_NUMBER(T1.GYULJAE_G)) = T3.JI_ACCNO_G(+)
      AND T2.SIGUMGO_ORG_C(+) = '28'
      AND T3.IPGI_G(+) = '1'
      AND T1.GYULJAE_DT = '20250513'
      AND ('all' = 'all' OR T1.JINGSU_CD = 'all')       
      AND (CASE WHEN 'all' = 'all' THEN DECODE(GYULJAE_G, '99', '99', 'all') ELSE GYULJAE_G END)  = 'all'
      AND ('all' = NVL('all', 'all') OR T1.JD_MOM_GUBUN = 'all')
      AND ('all' = NVL('61', 'all') OR T1.HOIKYE_CD = '61')
      AND ('all' = NVL('', 'all') OR T1.SMOK_CD = '')
      AND  T1.CD_SUNP_G <> '000'
)


select * from rpt_txio_ddac_tab
where upd_dttm like '20250515%'
order by upd_dttm desc
