SELECT   BB.SIGUMGO_HOIKYE_C 
  ,BB.HOIKYE_NM NUGYE_HOIGYE_NAME
                ,TO_CHAR((SUM(NVL(SUNP_AMT,0)) + SUM(NVL(TAX_BAEJUNG_IP_AMT,0)) + SUM(NVL(IWOL_GONGGEUM,0)))) AS NUGYE_SEIB_SUIP
                ,TO_CHAR(SUM(NVL(SEIB_BANNAB,0))) AS NUGYE_SEIB_BANNAB 
                ,TO_CHAR(SUM(NVL(SEIB_GYEONGJEONG_IB,0))) AS NUGYE_SEIB_GYEONGJEONG_IB
                ,TO_CHAR(SUM(NVL(SEIB_GYEONGJEONG_JI,0))*-1) AS NUGYE_SEIB_GYEONGJEONG_JI
                ,TO_CHAR(SUM(NVL(SECHUL_BAEJEONG,0))) AS NUGYE_SECHUL_BAEJEONG
                ,TO_CHAR(SUM(NVL(SECHUL_HWANSU,0))*-1) AS NUGYE_SECHUL_HWANSU
                ,TO_CHAR(SUM(NVL(SECHUL_JI,0))) AS NUGYE_SECHUL_JI
                ,TO_CHAR(SUM(NVL(SECHUL_BANNAB,0))*-1) AS NUGYE_SECHUL_BANNAB
                ,TO_CHAR(SUM(NVL(SECHUL_GYEONGJEONG_IB,0))) AS NUGYE_SECHUL_GYEONGJEONG_IB
                ,TO_CHAR(SUM(NVL(SECHUL_GYEONGJEONG_JI,0))) AS NUGYE_SECHUL_GYEONGJEONG_JI 
                ,TO_CHAR(SUM(NVL(SEIB_GYULSANBF_IIB,0))) AS NUGYE_SEIB_GYULSANBF_IIB
                ,TO_CHAR(SUM(NVL(SECHUL_GYULSANBF_IWOL,0))) AS NUGYE_SECHUL_GYULSANBF_IWOL
                ,TO_CHAR(SUM(NVL(DEP,0)) + SUM(NVL(IWOL_GONGGEUM_DEP,0))) AS NUGYE_DEP
               ,TO_CHAR(SUM(NVL(MMDA,0)) + SUM(NVL(IWOL_MMDA,0))) AS NUGYE_MMDA
               ,TO_CHAR(SUM(NVL(SUNP_AMT,0)) - SUM(NVL(SEIB_SUIP,0)) + SUM(NVL(IWOL_MIJUNGSAN,0))) AS NUGYE_MIICHE
                ,TO_CHAR((SUM(NVL(SUNP_AMT2,0)) + SUM(NVL(TAX_BAEJUNG_IP_AMT2,0)) + SUM(NVL(IWOL_GONGGEUM2,0)))) AS ILGYE_SEIB_SUIP
                ,TO_CHAR(SUM(NVL(SEIB_BANNAB2,0))) AS ILGYE_SEIB_BANNAB
                ,TO_CHAR(SUM(NVL(SEIB_GYEONGJEONG_IB2,0))) AS ILGYE_SEIB_GYEONGJEONG_IB
                ,TO_CHAR(SUM(NVL(SEIB_GYEONGJEONG_JI2,0))*-1) AS ILGYE_SEIB_GYEONGJEONG_JI
                ,TO_CHAR(SUM(NVL(SECHUL_BAEJEONG2,0))) AS ILGYE_SECHUL_BAEJEONG
                ,TO_CHAR(SUM(NVL(SECHUL_HWANSU2,0))*-1) AS ILGYE_SECHUL_HWANSU
                ,TO_CHAR(SUM(NVL(SECHUL_JI2,0))) AS ILGYE_SECHUL_JI
                ,TO_CHAR(SUM(NVL(SECHUL_BANNAB2,0))*-1) AS ILGYE_SECHUL_BANNAB
                ,TO_CHAR(SUM(NVL(SECHUL_GYEONGJEONG_IB2,0))) AS ILGYE_SECHUL_GYEONGJEONG_IB  
                ,TO_CHAR(SUM(NVL(SECHUL_GYEONGJEONG_JI2,0))) AS ILGYE_SECHUL_GYEONGJEONG_JI  
                ,TO_CHAR(SUM(NVL(SEIB_GYULSANBF_IIB2,0))) AS ILGYE_SEIB_GYULSANBF_IIB
                ,TO_CHAR(SUM(NVL(SECHUL_GYULSANBF_IWOL2,0))) AS ILGYE_SECHUL_GYULSANBF_IWOL
                ,TO_CHAR(SUM(NVL(DEP2,0)) + SUM(NVL(IWOL_GONGGEUM_DEP2,0))) AS ILGYE_DEP
               ,TO_CHAR(SUM(NVL(MMDA2,0)) + SUM(NVL(IWOL_MMDA2,0))) AS ILGYE_MMDA
               ,TO_CHAR(SUM(NVL(SUNP_AMT2,0)) - SUM(NVL(SEIB_SUIP2,0)) + SUM(NVL(IWOL_MIJUNGSAN2,0))) AS ILGYE_MIICHE
FROM
(

 WITH AC_LIST AS (
  SELECT     
    T2.SIGUMGO_ORG_C
    ,T3.SIGUMGO_HOIKYE_C AS RPT_HOIKYE_C
    ,T2.GONGGEUM_GYEJWA
    ,T2.GONGGEUM_GYEJWA_NM
    ,T2.SIGUMGO_HOIKYE_YR
  FROM
    (
 iaㅁㅑa SELECT
    T1.SIGUMGO_ORG_C
    ,T1.ICH_SIGUMGO_GUN_GU_C
    ,T1.ICH_SIGUMGO_HOIKYE_C
    ,T1.SIGUMGO_AC_B
    ,T1.SIGUMGO_AC_SER
    ,T1.SIGUMGO_HOIKYE_YR
    ,LPAD(T1.SIGUMGO_ORG_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_GUN_GU_C, 3, 0)||LPAD(T1.ICH_SIGUMGO_HOIKYE_C, 2, 0)||RPAD(T1.SIGUMGO_AC_B, 2, 0)||LPAD(T1.SIGUMGO_AC_SER, 5, '0')||SUBSTR(T1.SIGUMGO_HOIKYE_YR, 3, 2) AS  GONGGEUM_GYEJWA    
    ,T1.LINKAC_KWA_C ||'000'|| T1.LINK_ACSER AS GONGGEUM_YUDONG_ACNO
    ,T1.SIGUMGO_AC_NM AS GONGGEUM_GYEJWA_NM
  FROM
    ACL_SIGUMGO_MAS T1
  WHERE 1=1
    AND T1.SIGUMGO_ORG_C = '110'
    AND T1.SIGUMGO_HOIKYE_YR IN ('2025', '9999')
    AND T1.MNG_NO = 1
    ) T2
    ,RPT_AC_BY_HOIKYE_MAPP T3
  WHERE 1=1
    AND T2.GONGGEUM_GYEJWA = T3.SIGUMGO_ACNO
    AND T2.SIGUMGO_HOIKYE_YR = T3.SIGUMGO_HOIKYE_YR
    AND T2.SIGUMGO_ORG_C = T3.SIGUMGO_C
 )
 SELECT
    HOIGYE_CODE,
    SIGUMGO_ORG_C,
           NVL(TAX_SUNP_IP_AMT,0) AS SEIB_SUIP,           
    NVL(TAX_BAEJUNG_IP_AMT,0) AS TAX_BAEJUNG_IP_AMT,    
    NVL(GWAON_PROC_JI_AMT,0) AS SEIB_BANNAB,                  
    NVL(TAX_IP_CRT_IP_AMT,0) AS SEIB_GYEONGJEONG_IB,       
    NVL(TAX_IP_CRT_JI_AMT,0) AS SEIB_GYEONGJEONG_JI,                  
    NVL(BIZPLC_BAEJUNG_JI_AMT,0)+NVL(GAM_BAEJUNG_JI_AMT,0) AS SECHUL_BAEJEONG,                 
    NVL(BIZPLC_GAM_BAEJUNG_IP_AMT,0) AS SECHUL_HWANSU,                
    NVL(TAXO_JI_AMT,0) AS SECHUL_JI,                       
    NVL(TAXO_RTRN_AMT,0) AS SECHUL_BANNAB,                    
    NVL(KWA_CRRC_IP_AMT,0) AS SECHUL_GYEONGJEONG_IB,                 
    NVL(KWA_CRRC_JI_AMT,0) AS SECHUL_GYEONGJEONG_JI,                 
    NVL(GA_IWOL_IP_AMT,0) AS SEIB_GYULSANBF_IIB,                   
    NVL(GA_IWOL_JI_AMT,0) AS SECHUL_GYULSANBF_IWOL,                  
    NVL(DEP_MK_JI_AMT,0) - NVL(DEP_HJI_AMT,0) AS DEP,                       
    NVL(MMDA,0) AS MMDA,                       
    NVL(SUNP_AMT,0) AS SUNP_AMT,           
    NVL(IWOL_GONGGEUM,0) AS IWOL_GONGGEUM,      
    NVL(IWOL_MIJUNGSAN,0) AS IWOL_MIJUNGSAN ,      
    NVL(IWOL_MMDA,0) AS IWOL_MMDA,         
     NVL(IWOL_GONGGEUM_DEP,0) AS IWOL_GONGGEUM_DEP,    
    0 AS SEIB_SUIP2,                
    0 AS TAX_BAEJUNG_IP_AMT2,           
    0 AS SEIB_BANNAB2,                        
    0 AS SEIB_GYEONGJEONG_IB2,             
    0 AS SEIB_GYEONGJEONG_JI2,                        
    0 AS SECHUL_BAEJEONG2,                        
    0 AS SECHUL_HWANSU2,                        
    0 AS SECHUL_JI2,                           
    0 AS SECHUL_BANNAB2,                         
    0 AS SECHUL_GYEONGJEONG_IB2,                       
    0 AS SECHUL_GYEONGJEONG_JI2,                       
    0 AS SEIB_GYULSANBF_IIB2,                        
    0 AS SECHUL_GYULSANBF_IWOL2,                       
    0 AS DEP2,                            
    0 AS MMDA2,                          
    0 AS SUNP_AMT2,              
    0 AS IWOL_GONGGEUM2,           
    0 AS IWOL_MIJUNGSAN2 ,            
    0 AS IWOL_MMDA2,             
     0 AS IWOL_GONGGEUM_DEP2          
 FROM
 (
  SELECT   
      RPT_HOIKYE_C AS HOIGYE_CODE
     ,A.SIGUMGO_ORG_C
     ,SUM(TAX_SUNP_IP_AMT) AS TAX_SUNP_IP_AMT
     ,SUM(SUIP_CHULNAP_BAEJUNG_AMT)
        +SUM(FUND_UNYONG_INT_AMT)
        +SUM(PMNY_DEP_INT_AMT)
        +SUM(BTDEP_INT_AMT)
        +SUM(JICULWO_BAEJUNG_IP_AMT) AS TAX_BAEJUNG_IP_AMT
     ,SUM(GWAON_PROC_JI_AMT) AS GWAON_PROC_JI_AMT
     ,SUM(TAX_IP_CRT_IP_AMT) AS TAX_IP_CRT_IP_AMT
     ,SUM(TAX_IP_CRT_JI_AMT) AS TAX_IP_CRT_JI_AMT
     ,SUM(BIZPLC_BAEJUNG_JI_AMT) AS BIZPLC_BAEJUNG_JI_AMT
     ,SUM(BIZPLC_GAM_BAEJUNG_IP_AMT) AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,SUM(TAXO_FUND_BAEJUNG_JI_AMT)
     +SUM(TAXO_HNDO_BAEJUNG_JI_AMT)
     +SUM(TAXO_FUND_GETBK_JI_AMT)
     +SUM(TAXO_HNDO_JICHUL_JI_AMT)
     +SUM(TAXO_HNDO_GETBK_JI_AMT)  AS TAXO_JI_AMT
    ,SUM(TAXO_RTRN_AMT) AS TAXO_RTRN_AMT
    ,SUM(KWA_CRRC_IP_AMT) AS KWA_CRRC_IP_AMT
    ,SUM(KWA_CRRC_JI_AMT) AS KWA_CRRC_JI_AMT
    ,SUM(GA_IWOL_IP_AMT) AS GA_IWOL_IP_AMT
    ,SUM(GA_IWOL_JI_AMT) AS GA_IWOL_JI_AMT
    ,SUM(DEP_MK_JI_AMT) AS DEP_MK_JI_AMT
    ,SUM(MR_FUND_AMT) AS MMDA
    ,SUM(DEP_HJI_AMT) AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
    ,SUM(GAM_BAEJUNG_JI_AMT) GAM_BAEJUNG_JI_AMT
  FROM RPT_TXIO_DDAC_TAB A, AC_LIST B
  WHERE  A.SGG_ACNO(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.BAS_DT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.BAS_DT(+) BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20250812'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  -- 25.08.11 11-11, 11-12, 11-13 금액을 수입액에 잡아줌

  SELECT   
    RPT_HOIKYE_C AS HOIGYE_CODE
    , A.SIGUMGO_ORG_C
    , 0 AS TAX_SUNP_IP_AMT
    , 0 AS TAX_BAEJUNG_IP_AMT
    , 0 AS GWAON_PROC_JI_AMT
    , 0 AS TAX_IP_CRT_IP_AMT
    , 0 AS TAX_IP_CRT_JI_AMT
    , 0 AS BIZPLC_BAEJUNG_JI_AMT
    , 0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    , 0 AS TAXO_JI_AMT
    , 0 AS TAXO_RTRN_AMT
    , 0 AS KWA_CRRC_IP_AMT
    , 0 AS KWA_CRRC_JI_AMT
    , 0 AS GA_IWOL_IP_AMT
    , 0 AS GA_IWOL_JI_AMT
    , 0 AS DEP_MK_JI_AMT
    , 0 AS MMDA
    , 0 AS DEP_HJI_AMT
    , SUM(DECODE(CRT_CAN_G, 1 ,-1, 2, -1, 33, -1, 1) * DECODE(IPJI_G, 2, -1, 1) * TRAMT) AS SUNP_AMT
    , 0 AS IWOL_GONGGEUM
    , 0 AS IWOL_MIJUNGSAN
    , 0 AS IWOL_MMDA
    , 0 AS IWOL_GONGGEUM_DEP
    , 0 AS GAM_BAEJUNG_JI_AMT
  FROM ACL_SIGUMGO_SLV A, AC_LIST B
  WHERE  A.FIL_100_CTNT5(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.GJDT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.GJDT(+) BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20250812'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  AND A.SIGUMGO_TRX_G = 11
  AND A.SIGUMGO_IP_TRX_G IN (11, 12, 13)
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  SELECT  TO_CHAR(ICH_SIGUMGO_HOIKYE_C) HOIGYE_CODE
    ,A.SIGUMGO_ORG_C
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,SUM(JIBANGSE_AMT)  AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
    ,0 GAM_BAEJUNG_JI_AMT
   FROM   RPT_TXI_DDAC_TAB A
   WHERE  A.SIGUMGO_HOIKYE_YR = ( '2025' ) 
     AND A.SIGUMGO_ORG_C = '110'
     AND A.SUNAP_DT BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20250812'
     AND A.ICH_SIGUMGO_GUN_GU_C = 0    
     GROUP BY ICH_SIGUMGO_HOIKYE_C, A.SIGUMGO_ORG_C
  UNION ALL
  SELECT  TO_CHAR(HOIGYE_CODE) HOIGYE_CODE
    ,GEUMGO_CODE
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,SUM(CASE WHEN GUBUN_CODE = 1 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM
    ,SUM(CASE WHEN GUBUN_CODE = 5 THEN AMT1 ELSE 0 END) AS IWOL_MIJUNGSAN
    ,SUM(CASE WHEN GUBUN_CODE = 4 THEN AMT1 ELSE 0 END) AS IWOL_MMDA
    ,SUM(CASE WHEN GUBUN_CODE = 2 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM_DEP
    ,0 GAM_BAEJUNG_JI_AMT
   FROM   RPT_HOIGYE_IWOL A
   WHERE  A.HOIGYE_YEAR = ( '2025' - 1 )
     AND A.GEUMGO_CODE = '110'
     AND A.GUBUN_CODE IN (1, 2, 4, 5)
     AND A.KIJUNIL BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20250812'
     AND A.GUNGU_CODE = 0
     GROUP BY HOIGYE_CODE, GEUMGO_CODE
 ) 
 UNION ALL
 SELECT   
    HOIGYE_CODE,
    SIGUMGO_ORG_C,
           0 AS SEIB_SUIP,                
    0 AS TAX_BAEJUNG_IP_AMT,           
    0 AS SEIB_BANNAB,                        
    0 AS SEIB_GYEONGJEONG_IB,             
    0 AS SEIB_GYEONGJEONG_JI,                        
    0 AS SECHUL_BAEJEONG,                        
    0 AS SECHUL_HWANSU,                        
    0 AS SECHUL_JI,                           
    0 AS SECHUL_BANNAB,                         
    0 AS SECHUL_GYEONGJEONG_IB,                       
    0 AS SECHUL_GYEONGJEONG_JI,                       
    0 AS SEIB_GYULSANBF_IIB,                         
    0 AS SECHUL_GYULSANBF_IWOL,                       
    0 AS DEP,                            
    0 AS MMDA,                          
    0 AS SUNP_AMT,               
    0 AS IWOL_GONGGEUM,            
    0 AS IWOL_MIJUNGSAN ,            
    0 AS IWOL_MMDA,             
     0 AS IWOL_GONGGEUM_DEP,           
           NVL(TAX_SUNP_IP_AMT,0) AS SEIB_SUIP2,          
    NVL(TAX_BAEJUNG_IP_AMT,0) AS TAX_BAEJUNG_IP_AMT2,    
    NVL(GWAON_PROC_JI_AMT,0) AS SEIB_BANNAB2,                 
    NVL(TAX_IP_CRT_IP_AMT,0) AS SEIB_GYEONGJEONG_IB2,       
    NVL(TAX_IP_CRT_JI_AMT,0) AS SEIB_GYEONGJEONG_JI2,                  
    NVL(BIZPLC_BAEJUNG_JI_AMT,0) AS SECHUL_BAEJEONG2,                
    NVL(BIZPLC_GAM_BAEJUNG_IP_AMT,0) AS SECHUL_HWANSU2,                
    NVL(TAXO_JI_AMT,0) AS SECHUL_JI2,                      
    NVL(TAXO_RTRN_AMT,0) AS SECHUL_BANNAB2,                    
    NVL(KWA_CRRC_IP_AMT,0) AS SECHUL_GYEONGJEONG_IB2,                 
    NVL(KWA_CRRC_JI_AMT,0) AS SECHUL_GYEONGJEONG_JI2,                 
    NVL(GA_IWOL_IP_AMT,0) AS SEIB_GYULSANBF_IIB2,                   
    NVL(GA_IWOL_JI_AMT,0) AS SECHUL_GYULSANBF_IWOL2,                  
    NVL(DEP_MK_JI_AMT,0) - NVL(DEP_HJI_AMT,0) AS DEP2,                       
    NVL(MMDA,0) AS MMDA2,                       
    NVL(SUNP_AMT,0) AS SUNP_AMT2,          
    NVL(IWOL_GONGGEUM,0) AS IWOL_GONGGEUM2,      
    NVL(IWOL_MIJUNGSAN,0) AS IWOL_MIJUNGSAN2,      
    NVL(IWOL_MMDA,0) AS IWOL_MMDA2,         
    NVL(IWOL_GONGGEUM_DEP,0) AS IWOL_GONGGEUM_DEP2
     
 FROM
 (
  SELECT   
      RPT_HOIKYE_C AS HOIGYE_CODE
     ,A.SIGUMGO_ORG_C
     ,SUM(TAX_SUNP_IP_AMT) AS TAX_SUNP_IP_AMT
     ,SUM(SUIP_CHULNAP_BAEJUNG_AMT)
        +SUM(FUND_UNYONG_INT_AMT)
        +SUM(PMNY_DEP_INT_AMT)
        +SUM(BTDEP_INT_AMT)
        +SUM(JICULWO_BAEJUNG_IP_AMT) AS TAX_BAEJUNG_IP_AMT
     ,SUM(GWAON_PROC_JI_AMT) AS GWAON_PROC_JI_AMT
     ,SUM(TAX_IP_CRT_IP_AMT) AS TAX_IP_CRT_IP_AMT
     ,SUM(TAX_IP_CRT_JI_AMT) AS TAX_IP_CRT_JI_AMT
     ,SUM(BIZPLC_BAEJUNG_JI_AMT) AS BIZPLC_BAEJUNG_JI_AMT
     ,SUM(BIZPLC_GAM_BAEJUNG_IP_AMT) AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,SUM(TAXO_FUND_BAEJUNG_JI_AMT)
     +SUM(TAXO_HNDO_BAEJUNG_JI_AMT)
     +SUM(TAXO_FUND_GETBK_JI_AMT)
     +SUM(TAXO_HNDO_JICHUL_JI_AMT)
     +SUM(TAXO_HNDO_GETBK_JI_AMT)  AS TAXO_JI_AMT
    ,SUM(TAXO_RTRN_AMT) AS TAXO_RTRN_AMT
    ,SUM(KWA_CRRC_IP_AMT) AS KWA_CRRC_IP_AMT
    ,SUM(KWA_CRRC_JI_AMT) AS KWA_CRRC_JI_AMT
    ,SUM(GA_IWOL_IP_AMT) AS GA_IWOL_IP_AMT
    ,SUM(GA_IWOL_JI_AMT) AS GA_IWOL_JI_AMT
    ,SUM(DEP_MK_JI_AMT) AS DEP_MK_JI_AMT
    ,SUM(MR_FUND_AMT) AS MMDA
    ,SUM(DEP_HJI_AMT) AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
    ,SUM(GAM_BAEJUNG_JI_AMT) GAM_BAEJUNG_JI_AMT
  FROM RPT_TXIO_DDAC_TAB A, AC_LIST B
  WHERE  A.SGG_ACNO(+) = B.GONGGEUM_GYEJWA
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.BAS_DT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.BAS_DT(+) BETWEEN '20250812' AND '20250812'
  AND A.SIGUMGO_ORG_C(+) = '110'
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  -- 25.08.11 11-11, 11-12, 11-13 금액을 수입액에 잡아줌

  SELECT   
    RPT_HOIKYE_C AS HOIGYE_CODE
    , A.SIGUMGO_ORG_C
    , 0 AS TAX_SUNP_IP_AMT
    , 0 AS TAX_BAEJUNG_IP_AMT
    , 0 AS GWAON_PROC_JI_AMT
    , 0 AS TAX_IP_CRT_IP_AMT
    , 0 AS TAX_IP_CRT_JI_AMT
    , 0 AS BIZPLC_BAEJUNG_JI_AMT
    , 0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    , 0 AS TAXO_JI_AMT
    , 0 AS TAXO_RTRN_AMT
    , 0 AS KWA_CRRC_IP_AMT
    , 0 AS KWA_CRRC_JI_AMT
    , 0 AS GA_IWOL_IP_AMT
    , 0 AS GA_IWOL_JI_AMT
    , 0 AS DEP_MK_JI_AMT
    , 0 AS MMDA
    , 0 AS DEP_HJI_AMT
    , SUM(DECODE(CRT_CAN_G, 1 ,-1, 2, -1, 33, -1, 1) * DECODE(IPJI_G, 2, -1, 1) * TRAMT) AS SUNP_AMT
    , 0 AS IWOL_GONGGEUM
    , 0 AS IWOL_MIJUNGSAN
    , 0 AS IWOL_MMDA
    , 0 AS IWOL_GONGGEUM_DEP
    , 0 AS GAM_BAEJUNG_JI_AMT
  FROM ACL_SIGUMGO_SLV A, AC_LIST B
  WHERE  A.FIL_100_CTNT5(+) = B.GONGGEUM_GYEJWA 
       AND CASE WHEN A.SIGUMGO_HOIKYE_YR(+) = 9999 THEN TO_NUMBER(SUBSTR(A.GJDT(+),1,4))
                   ELSE TO_NUMBER(A.SIGUMGO_HOIKYE_YR(+)) END  = '2025'
  AND A.GJDT(+) BETWEEN '20250812' AND '20250812'
  AND A.SIGUMGO_ORG_C(+)  = '110'  
  AND A.ICH_SIGUMGO_GUN_GU_C = 0
  AND A.SIGUMGO_TRX_G = 11
  AND A.SIGUMGO_IP_TRX_G IN (11, 12, 13)
  GROUP BY RPT_HOIKYE_C, A.SIGUMGO_ORG_C

  UNION ALL
  SELECT  TO_CHAR(ICH_SIGUMGO_HOIKYE_C) HOIGYE_CODE
    ,A.SIGUMGO_ORG_C
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,SUM(JIBANGSE_AMT)  AS SUNP_AMT
    ,0 AS IWOL_GONGGEUM
    ,0 AS IWOL_MIJUNGSAN
    ,0 AS IWOL_MMDA
    ,0 AS IWOL_GONGGEUM_DEP
   , 0 GAM_BAEJUNG_JI_AMT
   FROM   RPT_TXI_DDAC_TAB A
   WHERE  A.SIGUMGO_HOIKYE_YR = ( '2025' ) 
     AND A.SIGUMGO_ORG_C = '110'
     AND A.SUNAP_DT BETWEEN '20250812' AND '20250812'
     AND A.ICH_SIGUMGO_GUN_GU_C = 0
     GROUP BY ICH_SIGUMGO_HOIKYE_C, A.SIGUMGO_ORG_C
  UNION ALL 
  SELECT  TO_CHAR(HOIGYE_CODE) HOIGYE_CODE
    ,A.GEUMGO_CODE
    ,0 AS TAX_SUNP_IP_AMT
    ,0 AS TAX_BAEJUNG_IP_AMT
    ,0 AS GWAON_PROC_JI_AMT
    ,0 AS TAX_IP_CRT_IP_AMT
    ,0 AS TAX_IP_CRT_JI_AMT
    ,0 AS BIZPLC_BAEJUNG_JI_AMT
    ,0 AS BIZPLC_GAM_BAEJUNG_IP_AMT
    ,0 AS TAXO_JI_AMT
    ,0 AS TAXO_RTRN_AMT
    ,0 AS KWA_CRRC_IP_AMT
    ,0 AS KWA_CRRC_JI_AMT
    ,0 AS GA_IWOL_IP_AMT
    ,0 AS GA_IWOL_JI_AMT
    ,0 AS DEP_MK_JI_AMT
    ,0 AS MR_FUND_AMT
    ,0 AS DEP_HJI_AMT
    ,0 AS SUNP_AMT
    ,SUM(CASE WHEN GUBUN_CODE = 1 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM
    ,SUM(CASE WHEN GUBUN_CODE = 5 THEN AMT1 ELSE 0 END) AS IWOL_MIJUNGSAN
    ,SUM(CASE WHEN GUBUN_CODE = 4 THEN AMT1 ELSE 0 END) AS IWOL_MMDA
    ,SUM(CASE WHEN GUBUN_CODE = 2 THEN AMT1 ELSE 0 END) AS IWOL_GONGGEUM_DEP
   ,0 GAM_BAEJUNG_JI_AMT
    FROM   RPT_HOIGYE_IWOL A
   WHERE  A.HOIGYE_YEAR = ( '2025' - 1 ) 
     AND A.GEUMGO_CODE = '110'
     AND A.GUBUN_CODE IN (1, 2, 4, 5)
     AND A.KIJUNIL BETWEEN '20250812' AND '20250812'
     AND A.GUNGU_CODE = 0
     GROUP BY HOIGYE_CODE, A.GEUMGO_CODE
 )
) AA, RPT_HOIKYE_CD BB
WHERE AA.SIGUMGO_ORG_C(+) = BB.SIGUMGO_C
AND AA.HOIGYE_CODE(+) = BB.SIGUMGO_HOIKYE_C
 
AND BB.SIGUMGO_C = '110'
AND BB.USE_YN = 'Y'
GROUP BY BB.SIGUMGO_HOIKYE_C, BB.HOIKYE_NM
ORDER BY TO_NUMBER(BB.SIGUMGO_HOIKYE_C), BB.HOIKYE_NM


-- 11000080900006025 160000138590
select * from ACL_SIGUMGO_MAS where 1=1







  SELECT  *
   FROM   RPT_HOIGYE_IWOL A
   WHERE  A.HOIGYE_YEAR = ( '2025' - 1 )
     AND A.GEUMGO_CODE = '110'
     AND A.KIJUNIL BETWEEN SUBSTR('20250101',0,4)||'0101' AND '20250812'
     AND A.GUNGU_CODE = 0


select * from RPT_AC_BY_HOIKYE_MAPP where sigumgo_c = 110 and sigumgo_hoikye_yr in (2025, 9999)     

select * from rpt_txi_ddac_tab 
where sigumgo_hoikye_yr = 2025 
and sigumgo_org_c = 110 
and sunap_dt between '20250101' and '20250812'